/**
 * Autogenerated by Thrift for cachelib/navy/serialization/objects.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated @nocommit
 */
#include "cachelib/navy/serialization/gen-cpp2/objects_types_custom_protocol.h"
#include "cachelib/navy/serialization/gen-cpp2/objects_data.h"

#include <thrift/lib/cpp2/gen/module_types_cpp.h>


namespace apache {
namespace thrift {
namespace detail {

void TccStructTraits<::facebook::cachelib::navy::serialization::IndexEntry>::translateFieldName(
    std::string_view _fname,
    int16_t& fid,
    apache::thrift::protocol::TType& _ftype) {
  using data = apache::thrift::TStructDataStorage<::facebook::cachelib::navy::serialization::IndexEntry>;
  static const st::translate_field_name_table table{
      data::fields_size,
      data::fields_names.data(),
      data::fields_ids.data(),
      data::fields_types.data()};
  st::translate_field_name_or_id(_fname, fid, _ftype, table);
}

} // namespace detail
} // namespace thrift
} // namespace apache

namespace apache {
namespace thrift {
namespace detail {

void TccStructTraits<::facebook::cachelib::navy::serialization::IndexBucket>::translateFieldName(
    std::string_view _fname,
    int16_t& fid,
    apache::thrift::protocol::TType& _ftype) {
  using data = apache::thrift::TStructDataStorage<::facebook::cachelib::navy::serialization::IndexBucket>;
  static const st::translate_field_name_table table{
      data::fields_size,
      data::fields_names.data(),
      data::fields_ids.data(),
      data::fields_types.data()};
  st::translate_field_name_or_id(_fname, fid, _ftype, table);
}

} // namespace detail
} // namespace thrift
} // namespace apache

namespace apache {
namespace thrift {
namespace detail {

void TccStructTraits<::facebook::cachelib::navy::serialization::Region>::translateFieldName(
    std::string_view _fname,
    int16_t& fid,
    apache::thrift::protocol::TType& _ftype) {
  using data = apache::thrift::TStructDataStorage<::facebook::cachelib::navy::serialization::Region>;
  static const st::translate_field_name_table table{
      data::fields_size,
      data::fields_names.data(),
      data::fields_ids.data(),
      data::fields_types.data()};
  st::translate_field_name_or_id(_fname, fid, _ftype, table);
}

} // namespace detail
} // namespace thrift
} // namespace apache

namespace apache {
namespace thrift {
namespace detail {

void TccStructTraits<::facebook::cachelib::navy::serialization::RegionData>::translateFieldName(
    std::string_view _fname,
    int16_t& fid,
    apache::thrift::protocol::TType& _ftype) {
  using data = apache::thrift::TStructDataStorage<::facebook::cachelib::navy::serialization::RegionData>;
  static const st::translate_field_name_table table{
      data::fields_size,
      data::fields_names.data(),
      data::fields_ids.data(),
      data::fields_types.data()};
  st::translate_field_name_or_id(_fname, fid, _ftype, table);
}

} // namespace detail
} // namespace thrift
} // namespace apache

namespace apache {
namespace thrift {
namespace detail {

void TccStructTraits<::facebook::cachelib::navy::serialization::FifoPolicyNodeData>::translateFieldName(
    std::string_view _fname,
    int16_t& fid,
    apache::thrift::protocol::TType& _ftype) {
  using data = apache::thrift::TStructDataStorage<::facebook::cachelib::navy::serialization::FifoPolicyNodeData>;
  static const st::translate_field_name_table table{
      data::fields_size,
      data::fields_names.data(),
      data::fields_ids.data(),
      data::fields_types.data()};
  st::translate_field_name_or_id(_fname, fid, _ftype, table);
}

} // namespace detail
} // namespace thrift
} // namespace apache

namespace apache {
namespace thrift {
namespace detail {

void TccStructTraits<::facebook::cachelib::navy::serialization::FifoPolicyData>::translateFieldName(
    std::string_view _fname,
    int16_t& fid,
    apache::thrift::protocol::TType& _ftype) {
  using data = apache::thrift::TStructDataStorage<::facebook::cachelib::navy::serialization::FifoPolicyData>;
  static const st::translate_field_name_table table{
      data::fields_size,
      data::fields_names.data(),
      data::fields_ids.data(),
      data::fields_types.data()};
  st::translate_field_name_or_id(_fname, fid, _ftype, table);
}

} // namespace detail
} // namespace thrift
} // namespace apache

namespace apache {
namespace thrift {
namespace detail {

void TccStructTraits<::facebook::cachelib::navy::serialization::AccessStats>::translateFieldName(
    std::string_view _fname,
    int16_t& fid,
    apache::thrift::protocol::TType& _ftype) {
  using data = apache::thrift::TStructDataStorage<::facebook::cachelib::navy::serialization::AccessStats>;
  static const st::translate_field_name_table table{
      data::fields_size,
      data::fields_names.data(),
      data::fields_ids.data(),
      data::fields_types.data()};
  st::translate_field_name_or_id(_fname, fid, _ftype, table);
}

} // namespace detail
} // namespace thrift
} // namespace apache

namespace apache {
namespace thrift {
namespace detail {

void TccStructTraits<::facebook::cachelib::navy::serialization::AccessStatsPair>::translateFieldName(
    std::string_view _fname,
    int16_t& fid,
    apache::thrift::protocol::TType& _ftype) {
  using data = apache::thrift::TStructDataStorage<::facebook::cachelib::navy::serialization::AccessStatsPair>;
  static const st::translate_field_name_table table{
      data::fields_size,
      data::fields_names.data(),
      data::fields_ids.data(),
      data::fields_types.data()};
  st::translate_field_name_or_id(_fname, fid, _ftype, table);
}

} // namespace detail
} // namespace thrift
} // namespace apache

namespace apache {
namespace thrift {
namespace detail {

void TccStructTraits<::facebook::cachelib::navy::serialization::AccessTracker>::translateFieldName(
    std::string_view _fname,
    int16_t& fid,
    apache::thrift::protocol::TType& _ftype) {
  using data = apache::thrift::TStructDataStorage<::facebook::cachelib::navy::serialization::AccessTracker>;
  static const st::translate_field_name_table table{
      data::fields_size,
      data::fields_names.data(),
      data::fields_ids.data(),
      data::fields_types.data()};
  st::translate_field_name_or_id(_fname, fid, _ftype, table);
}

} // namespace detail
} // namespace thrift
} // namespace apache

namespace apache {
namespace thrift {
namespace detail {

void TccStructTraits<::facebook::cachelib::navy::serialization::BlockCacheConfig>::translateFieldName(
    std::string_view _fname,
    int16_t& fid,
    apache::thrift::protocol::TType& _ftype) {
  using data = apache::thrift::TStructDataStorage<::facebook::cachelib::navy::serialization::BlockCacheConfig>;
  static const st::translate_field_name_table table{
      data::fields_size,
      data::fields_names.data(),
      data::fields_ids.data(),
      data::fields_types.data()};
  st::translate_field_name_or_id(_fname, fid, _ftype, table);
}

} // namespace detail
} // namespace thrift
} // namespace apache

namespace apache {
namespace thrift {
namespace detail {

void TccStructTraits<::facebook::cachelib::navy::serialization::ValidBucketCheckerState>::translateFieldName(
    std::string_view _fname,
    int16_t& fid,
    apache::thrift::protocol::TType& _ftype) {
  using data = apache::thrift::TStructDataStorage<::facebook::cachelib::navy::serialization::ValidBucketCheckerState>;
  static const st::translate_field_name_table table{
      data::fields_size,
      data::fields_names.data(),
      data::fields_ids.data(),
      data::fields_types.data()};
  st::translate_field_name_or_id(_fname, fid, _ftype, table);
}

} // namespace detail
} // namespace thrift
} // namespace apache

namespace apache {
namespace thrift {
namespace detail {

void TccStructTraits<::facebook::cachelib::navy::serialization::BigHashPersistentData>::translateFieldName(
    std::string_view _fname,
    int16_t& fid,
    apache::thrift::protocol::TType& _ftype) {
  using data = apache::thrift::TStructDataStorage<::facebook::cachelib::navy::serialization::BigHashPersistentData>;
  static const st::translate_field_name_table table{
      data::fields_size,
      data::fields_names.data(),
      data::fields_ids.data(),
      data::fields_types.data()};
  st::translate_field_name_or_id(_fname, fid, _ftype, table);
}

} // namespace detail
} // namespace thrift
} // namespace apache

namespace apache {
namespace thrift {
namespace detail {

void TccStructTraits<::facebook::cachelib::navy::serialization::FixedSizeIndexConfig>::translateFieldName(
    std::string_view _fname,
    int16_t& fid,
    apache::thrift::protocol::TType& _ftype) {
  using data = apache::thrift::TStructDataStorage<::facebook::cachelib::navy::serialization::FixedSizeIndexConfig>;
  static const st::translate_field_name_table table{
      data::fields_size,
      data::fields_names.data(),
      data::fields_ids.data(),
      data::fields_types.data()};
  st::translate_field_name_or_id(_fname, fid, _ftype, table);
}

} // namespace detail
} // namespace thrift
} // namespace apache

namespace facebook::cachelib::navy::serialization {


template void IndexEntry::readNoXfer<>(apache::thrift::SimpleJSONProtocolReader*);
template uint32_t IndexEntry::write<>(apache::thrift::SimpleJSONProtocolWriter*) const;
template uint32_t IndexEntry::serializedSize<>(apache::thrift::SimpleJSONProtocolWriter const*) const;
template uint32_t IndexEntry::serializedSizeZC<>(apache::thrift::SimpleJSONProtocolWriter const*) const;



template void IndexBucket::readNoXfer<>(apache::thrift::SimpleJSONProtocolReader*);
template uint32_t IndexBucket::write<>(apache::thrift::SimpleJSONProtocolWriter*) const;
template uint32_t IndexBucket::serializedSize<>(apache::thrift::SimpleJSONProtocolWriter const*) const;
template uint32_t IndexBucket::serializedSizeZC<>(apache::thrift::SimpleJSONProtocolWriter const*) const;



template void Region::readNoXfer<>(apache::thrift::SimpleJSONProtocolReader*);
template uint32_t Region::write<>(apache::thrift::SimpleJSONProtocolWriter*) const;
template uint32_t Region::serializedSize<>(apache::thrift::SimpleJSONProtocolWriter const*) const;
template uint32_t Region::serializedSizeZC<>(apache::thrift::SimpleJSONProtocolWriter const*) const;



template void RegionData::readNoXfer<>(apache::thrift::SimpleJSONProtocolReader*);
template uint32_t RegionData::write<>(apache::thrift::SimpleJSONProtocolWriter*) const;
template uint32_t RegionData::serializedSize<>(apache::thrift::SimpleJSONProtocolWriter const*) const;
template uint32_t RegionData::serializedSizeZC<>(apache::thrift::SimpleJSONProtocolWriter const*) const;



template void FifoPolicyNodeData::readNoXfer<>(apache::thrift::SimpleJSONProtocolReader*);
template uint32_t FifoPolicyNodeData::write<>(apache::thrift::SimpleJSONProtocolWriter*) const;
template uint32_t FifoPolicyNodeData::serializedSize<>(apache::thrift::SimpleJSONProtocolWriter const*) const;
template uint32_t FifoPolicyNodeData::serializedSizeZC<>(apache::thrift::SimpleJSONProtocolWriter const*) const;



template void FifoPolicyData::readNoXfer<>(apache::thrift::SimpleJSONProtocolReader*);
template uint32_t FifoPolicyData::write<>(apache::thrift::SimpleJSONProtocolWriter*) const;
template uint32_t FifoPolicyData::serializedSize<>(apache::thrift::SimpleJSONProtocolWriter const*) const;
template uint32_t FifoPolicyData::serializedSizeZC<>(apache::thrift::SimpleJSONProtocolWriter const*) const;



template void AccessStats::readNoXfer<>(apache::thrift::SimpleJSONProtocolReader*);
template uint32_t AccessStats::write<>(apache::thrift::SimpleJSONProtocolWriter*) const;
template uint32_t AccessStats::serializedSize<>(apache::thrift::SimpleJSONProtocolWriter const*) const;
template uint32_t AccessStats::serializedSizeZC<>(apache::thrift::SimpleJSONProtocolWriter const*) const;



template void AccessStatsPair::readNoXfer<>(apache::thrift::SimpleJSONProtocolReader*);
template uint32_t AccessStatsPair::write<>(apache::thrift::SimpleJSONProtocolWriter*) const;
template uint32_t AccessStatsPair::serializedSize<>(apache::thrift::SimpleJSONProtocolWriter const*) const;
template uint32_t AccessStatsPair::serializedSizeZC<>(apache::thrift::SimpleJSONProtocolWriter const*) const;



template void AccessTracker::readNoXfer<>(apache::thrift::SimpleJSONProtocolReader*);
template uint32_t AccessTracker::write<>(apache::thrift::SimpleJSONProtocolWriter*) const;
template uint32_t AccessTracker::serializedSize<>(apache::thrift::SimpleJSONProtocolWriter const*) const;
template uint32_t AccessTracker::serializedSizeZC<>(apache::thrift::SimpleJSONProtocolWriter const*) const;



template void BlockCacheConfig::readNoXfer<>(apache::thrift::SimpleJSONProtocolReader*);
template uint32_t BlockCacheConfig::write<>(apache::thrift::SimpleJSONProtocolWriter*) const;
template uint32_t BlockCacheConfig::serializedSize<>(apache::thrift::SimpleJSONProtocolWriter const*) const;
template uint32_t BlockCacheConfig::serializedSizeZC<>(apache::thrift::SimpleJSONProtocolWriter const*) const;



template void ValidBucketCheckerState::readNoXfer<>(apache::thrift::SimpleJSONProtocolReader*);
template uint32_t ValidBucketCheckerState::write<>(apache::thrift::SimpleJSONProtocolWriter*) const;
template uint32_t ValidBucketCheckerState::serializedSize<>(apache::thrift::SimpleJSONProtocolWriter const*) const;
template uint32_t ValidBucketCheckerState::serializedSizeZC<>(apache::thrift::SimpleJSONProtocolWriter const*) const;



template void BigHashPersistentData::readNoXfer<>(apache::thrift::SimpleJSONProtocolReader*);
template uint32_t BigHashPersistentData::write<>(apache::thrift::SimpleJSONProtocolWriter*) const;
template uint32_t BigHashPersistentData::serializedSize<>(apache::thrift::SimpleJSONProtocolWriter const*) const;
template uint32_t BigHashPersistentData::serializedSizeZC<>(apache::thrift::SimpleJSONProtocolWriter const*) const;



template void FixedSizeIndexConfig::readNoXfer<>(apache::thrift::SimpleJSONProtocolReader*);
template uint32_t FixedSizeIndexConfig::write<>(apache::thrift::SimpleJSONProtocolWriter*) const;
template uint32_t FixedSizeIndexConfig::serializedSize<>(apache::thrift::SimpleJSONProtocolWriter const*) const;
template uint32_t FixedSizeIndexConfig::serializedSizeZC<>(apache::thrift::SimpleJSONProtocolWriter const*) const;


} // namespace facebook::cachelib::navy::serialization
