/**
 * Autogenerated by Thrift for cachelib/navy/serialization/objects.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated @nocommit
 */
#pragma once

#include "cachelib/navy/serialization/gen-cpp2/objects_types.h"
#include <thrift/lib/cpp2/visitation/visit_union.h>

namespace apache {
namespace thrift {
namespace detail {

} // namespace detail
} // namespace thrift
} // namespace apache
