/**
 * Autogenerated by Thrift for cachelib/navy/serialization/objects.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated @nocommit
 */
#include "cachelib/navy/serialization/gen-cpp2/objects_types_custom_protocol.h"

namespace facebook::cachelib::navy::serialization {

template void IndexEntry::readNoXfer<>(apache::thrift::CompactProtocolReader*);
template uint32_t IndexEntry::write<>(apache::thrift::CompactProtocolWriter*) const;
template uint32_t IndexEntry::serializedSize<>(apache::thrift::CompactProtocolWriter const*) const;
template uint32_t IndexEntry::serializedSizeZC<>(apache::thrift::CompactProtocolWriter const*) const;

template void IndexBucket::readNoXfer<>(apache::thrift::CompactProtocolReader*);
template uint32_t IndexBucket::write<>(apache::thrift::CompactProtocolWriter*) const;
template uint32_t IndexBucket::serializedSize<>(apache::thrift::CompactProtocolWriter const*) const;
template uint32_t IndexBucket::serializedSizeZC<>(apache::thrift::CompactProtocolWriter const*) const;

template void Region::readNoXfer<>(apache::thrift::CompactProtocolReader*);
template uint32_t Region::write<>(apache::thrift::CompactProtocolWriter*) const;
template uint32_t Region::serializedSize<>(apache::thrift::CompactProtocolWriter const*) const;
template uint32_t Region::serializedSizeZC<>(apache::thrift::CompactProtocolWriter const*) const;

template void RegionData::readNoXfer<>(apache::thrift::CompactProtocolReader*);
template uint32_t RegionData::write<>(apache::thrift::CompactProtocolWriter*) const;
template uint32_t RegionData::serializedSize<>(apache::thrift::CompactProtocolWriter const*) const;
template uint32_t RegionData::serializedSizeZC<>(apache::thrift::CompactProtocolWriter const*) const;

template void FifoPolicyNodeData::readNoXfer<>(apache::thrift::CompactProtocolReader*);
template uint32_t FifoPolicyNodeData::write<>(apache::thrift::CompactProtocolWriter*) const;
template uint32_t FifoPolicyNodeData::serializedSize<>(apache::thrift::CompactProtocolWriter const*) const;
template uint32_t FifoPolicyNodeData::serializedSizeZC<>(apache::thrift::CompactProtocolWriter const*) const;

template void FifoPolicyData::readNoXfer<>(apache::thrift::CompactProtocolReader*);
template uint32_t FifoPolicyData::write<>(apache::thrift::CompactProtocolWriter*) const;
template uint32_t FifoPolicyData::serializedSize<>(apache::thrift::CompactProtocolWriter const*) const;
template uint32_t FifoPolicyData::serializedSizeZC<>(apache::thrift::CompactProtocolWriter const*) const;

template void AccessStats::readNoXfer<>(apache::thrift::CompactProtocolReader*);
template uint32_t AccessStats::write<>(apache::thrift::CompactProtocolWriter*) const;
template uint32_t AccessStats::serializedSize<>(apache::thrift::CompactProtocolWriter const*) const;
template uint32_t AccessStats::serializedSizeZC<>(apache::thrift::CompactProtocolWriter const*) const;

template void AccessStatsPair::readNoXfer<>(apache::thrift::CompactProtocolReader*);
template uint32_t AccessStatsPair::write<>(apache::thrift::CompactProtocolWriter*) const;
template uint32_t AccessStatsPair::serializedSize<>(apache::thrift::CompactProtocolWriter const*) const;
template uint32_t AccessStatsPair::serializedSizeZC<>(apache::thrift::CompactProtocolWriter const*) const;

template void AccessTracker::readNoXfer<>(apache::thrift::CompactProtocolReader*);
template uint32_t AccessTracker::write<>(apache::thrift::CompactProtocolWriter*) const;
template uint32_t AccessTracker::serializedSize<>(apache::thrift::CompactProtocolWriter const*) const;
template uint32_t AccessTracker::serializedSizeZC<>(apache::thrift::CompactProtocolWriter const*) const;

template void BlockCacheConfig::readNoXfer<>(apache::thrift::CompactProtocolReader*);
template uint32_t BlockCacheConfig::write<>(apache::thrift::CompactProtocolWriter*) const;
template uint32_t BlockCacheConfig::serializedSize<>(apache::thrift::CompactProtocolWriter const*) const;
template uint32_t BlockCacheConfig::serializedSizeZC<>(apache::thrift::CompactProtocolWriter const*) const;

template void ValidBucketCheckerState::readNoXfer<>(apache::thrift::CompactProtocolReader*);
template uint32_t ValidBucketCheckerState::write<>(apache::thrift::CompactProtocolWriter*) const;
template uint32_t ValidBucketCheckerState::serializedSize<>(apache::thrift::CompactProtocolWriter const*) const;
template uint32_t ValidBucketCheckerState::serializedSizeZC<>(apache::thrift::CompactProtocolWriter const*) const;

template void BigHashPersistentData::readNoXfer<>(apache::thrift::CompactProtocolReader*);
template uint32_t BigHashPersistentData::write<>(apache::thrift::CompactProtocolWriter*) const;
template uint32_t BigHashPersistentData::serializedSize<>(apache::thrift::CompactProtocolWriter const*) const;
template uint32_t BigHashPersistentData::serializedSizeZC<>(apache::thrift::CompactProtocolWriter const*) const;

template void FixedSizeIndexConfig::readNoXfer<>(apache::thrift::CompactProtocolReader*);
template uint32_t FixedSizeIndexConfig::write<>(apache::thrift::CompactProtocolWriter*) const;
template uint32_t FixedSizeIndexConfig::serializedSize<>(apache::thrift::CompactProtocolWriter const*) const;
template uint32_t FixedSizeIndexConfig::serializedSizeZC<>(apache::thrift::CompactProtocolWriter const*) const;

} // namespace facebook::cachelib::navy::serialization
