/**
 * Autogenerated by Thrift for cachelib/navy/serialization/objects.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated @nocommit
 */
#include "cachelib/navy/serialization/gen-cpp2/objects_types.tcc"
#include "cachelib/navy/serialization/gen-cpp2/objects_constants.h"
#include "cachelib/navy/serialization/gen-cpp2/objects_data.h"

#include <thrift/lib/cpp2/gen/module_types_cpp.h>

[[maybe_unused]] static constexpr std::string_view kModuleName = "objects";



namespace facebook::cachelib::navy::serialization {

std::string_view IndexEntry::__fbthrift_get_field_name(::apache::thrift::FieldOrdinal ord) {
  if (ord == ::apache::thrift::FieldOrdinal{0}) { return {}; }
  return apache::thrift::TStructDataStorage<IndexEntry>::fields_names[folly::to_underlying(ord) - 1];
}
std::string_view IndexEntry::__fbthrift_get_class_name() {
  return apache::thrift::TStructDataStorage<IndexEntry>::name;
}

IndexEntry::IndexEntry(const IndexEntry&) = default;
IndexEntry& IndexEntry::operator=(const IndexEntry&) = default;
IndexEntry::IndexEntry([[maybe_unused]] IndexEntry&& other) noexcept :
    __fbthrift_field_key(std::move(other.__fbthrift_field_key)),
    __fbthrift_field_address(std::move(other.__fbthrift_field_address)),
    __fbthrift_field_sizeHint(std::move(other.__fbthrift_field_sizeHint)),
    __fbthrift_field_totalHits(std::move(other.__fbthrift_field_totalHits)),
    __fbthrift_field_currentHits(std::move(other.__fbthrift_field_currentHits)),
    __isset(other.__isset) {
}

IndexEntry& IndexEntry::operator=([[maybe_unused]] IndexEntry&& other) noexcept {
    this->__fbthrift_field_key = std::move(other.__fbthrift_field_key);
    this->__fbthrift_field_address = std::move(other.__fbthrift_field_address);
    this->__fbthrift_field_sizeHint = std::move(other.__fbthrift_field_sizeHint);
    this->__fbthrift_field_totalHits = std::move(other.__fbthrift_field_totalHits);
    this->__fbthrift_field_currentHits = std::move(other.__fbthrift_field_currentHits);
    __isset = other.__isset;
    return *this;
}


IndexEntry::IndexEntry(apache::thrift::FragileConstructor, ::std::int32_t key__arg, ::std::int32_t address__arg, ::std::int16_t sizeHint__arg, ::std::int8_t totalHits__arg, ::std::int8_t currentHits__arg) :
    __fbthrift_field_key(std::move(key__arg)),
    __fbthrift_field_address(std::move(address__arg)),
    __fbthrift_field_sizeHint(std::move(sizeHint__arg)),
    __fbthrift_field_totalHits(std::move(totalHits__arg)),
    __fbthrift_field_currentHits(std::move(currentHits__arg)) { 
  __isset.set(folly::index_constant<0>(), true);
  __isset.set(folly::index_constant<1>(), true);
  __isset.set(folly::index_constant<2>(), true);
  __isset.set(folly::index_constant<3>(), true);
  __isset.set(folly::index_constant<4>(), true);
}

void IndexEntry::__fbthrift_clear() {
  // clear all fields
  this->__fbthrift_field_key = ::std::int32_t();
  this->__fbthrift_field_address = ::std::int32_t();
  this->__fbthrift_field_sizeHint = ::std::int16_t();
  this->__fbthrift_field_totalHits = ::std::int8_t();
  this->__fbthrift_field_currentHits = ::std::int8_t();
  __isset = {};
}

bool IndexEntry::__fbthrift_is_empty() const {
  return false;
}

bool IndexEntry::operator==([[maybe_unused]] const IndexEntry& rhs) const {
  return ::apache::thrift::op::detail::StructEquality{}(*this, rhs);
}

bool IndexEntry::operator<([[maybe_unused]] const IndexEntry& rhs) const {
  return ::apache::thrift::op::detail::StructLessThan{}(*this, rhs);
}


::std::int32_t IndexEntry::get_key() const {
  return __fbthrift_field_key;
}

::std::int32_t& IndexEntry::set_key(::std::int32_t key_) {
  key_ref() = key_;
  return __fbthrift_field_key;
}

::std::int32_t IndexEntry::get_address() const {
  return __fbthrift_field_address;
}

::std::int32_t& IndexEntry::set_address(::std::int32_t address_) {
  address_ref() = address_;
  return __fbthrift_field_address;
}

::std::int16_t IndexEntry::get_sizeHint() const {
  return __fbthrift_field_sizeHint;
}

::std::int16_t& IndexEntry::set_sizeHint(::std::int16_t sizeHint_) {
  sizeHint_ref() = sizeHint_;
  return __fbthrift_field_sizeHint;
}

::std::int8_t IndexEntry::get_totalHits() const {
  return __fbthrift_field_totalHits;
}

::std::int8_t& IndexEntry::set_totalHits(::std::int8_t totalHits_) {
  totalHits_ref() = totalHits_;
  return __fbthrift_field_totalHits;
}

::std::int8_t IndexEntry::get_currentHits() const {
  return __fbthrift_field_currentHits;
}

::std::int8_t& IndexEntry::set_currentHits(::std::int8_t currentHits_) {
  currentHits_ref() = currentHits_;
  return __fbthrift_field_currentHits;
}

void swap([[maybe_unused]] IndexEntry& a, [[maybe_unused]] IndexEntry& b) {
  using ::std::swap;
  swap(a.__fbthrift_field_key, b.__fbthrift_field_key);
  swap(a.__fbthrift_field_address, b.__fbthrift_field_address);
  swap(a.__fbthrift_field_sizeHint, b.__fbthrift_field_sizeHint);
  swap(a.__fbthrift_field_totalHits, b.__fbthrift_field_totalHits);
  swap(a.__fbthrift_field_currentHits, b.__fbthrift_field_currentHits);
  swap(a.__isset, b.__isset);
}


} // namespace facebook::cachelib::navy::serialization


namespace facebook::cachelib::navy::serialization {

std::string_view IndexBucket::__fbthrift_get_field_name(::apache::thrift::FieldOrdinal ord) {
  if (ord == ::apache::thrift::FieldOrdinal{0}) { return {}; }
  return apache::thrift::TStructDataStorage<IndexBucket>::fields_names[folly::to_underlying(ord) - 1];
}
std::string_view IndexBucket::__fbthrift_get_class_name() {
  return apache::thrift::TStructDataStorage<IndexBucket>::name;
}

IndexBucket::IndexBucket(const IndexBucket&) = default;
IndexBucket& IndexBucket::operator=(const IndexBucket&) = default;
IndexBucket::IndexBucket() :
    __fbthrift_field_bucketId(static_cast<::std::int32_t>(0)) {
}


IndexBucket::~IndexBucket() {}

IndexBucket::IndexBucket([[maybe_unused]] IndexBucket&& other) noexcept :
    __fbthrift_field_bucketId(std::move(other.__fbthrift_field_bucketId)),
    __fbthrift_field_entries(std::move(other.__fbthrift_field_entries)),
    __isset(other.__isset) {
}

IndexBucket& IndexBucket::operator=([[maybe_unused]] IndexBucket&& other) noexcept {
    this->__fbthrift_field_bucketId = std::move(other.__fbthrift_field_bucketId);
    this->__fbthrift_field_entries = std::move(other.__fbthrift_field_entries);
    __isset = other.__isset;
    return *this;
}


IndexBucket::IndexBucket(apache::thrift::FragileConstructor, ::std::int32_t bucketId__arg, ::std::vector<::facebook::cachelib::navy::serialization::IndexEntry> entries__arg) :
    __fbthrift_field_bucketId(std::move(bucketId__arg)),
    __fbthrift_field_entries(std::move(entries__arg)) { 
  __isset.set(folly::index_constant<0>(), true);
  __isset.set(folly::index_constant<1>(), true);
}

void IndexBucket::__fbthrift_clear() {
  // clear all fields
  this->__fbthrift_field_bucketId = ::std::int32_t();
  this->__fbthrift_field_entries.clear();
  __isset = {};
}

bool IndexBucket::__fbthrift_is_empty() const {
  return false;
}

bool IndexBucket::operator==([[maybe_unused]] const IndexBucket& rhs) const {
  return ::apache::thrift::op::detail::StructEquality{}(*this, rhs);
}

bool IndexBucket::operator<([[maybe_unused]] const IndexBucket& rhs) const {
  return ::apache::thrift::op::detail::StructLessThan{}(*this, rhs);
}


::std::int32_t IndexBucket::get_bucketId() const {
  return __fbthrift_field_bucketId;
}

::std::int32_t& IndexBucket::set_bucketId(::std::int32_t bucketId_) {
  bucketId_ref() = bucketId_;
  return __fbthrift_field_bucketId;
}

const ::std::vector<::facebook::cachelib::navy::serialization::IndexEntry>& IndexBucket::get_entries() const& {
  return __fbthrift_field_entries;
}

::std::vector<::facebook::cachelib::navy::serialization::IndexEntry> IndexBucket::get_entries() && {
  return static_cast<::std::vector<::facebook::cachelib::navy::serialization::IndexEntry>&&>(__fbthrift_field_entries);
}

void swap([[maybe_unused]] IndexBucket& a, [[maybe_unused]] IndexBucket& b) {
  using ::std::swap;
  swap(a.__fbthrift_field_bucketId, b.__fbthrift_field_bucketId);
  swap(a.__fbthrift_field_entries, b.__fbthrift_field_entries);
  swap(a.__isset, b.__isset);
}

static_assert(
    ::apache::thrift::detail::st::gen_check_json<
        IndexBucket,
        ::apache::thrift::type_class::list<::apache::thrift::type_class::structure>,
        ::std::vector<::facebook::cachelib::navy::serialization::IndexEntry>>,
    "inconsistent use of json option");

} // namespace facebook::cachelib::navy::serialization


namespace facebook::cachelib::navy::serialization {

std::string_view Region::__fbthrift_get_field_name(::apache::thrift::FieldOrdinal ord) {
  if (ord == ::apache::thrift::FieldOrdinal{0}) { return {}; }
  return apache::thrift::TStructDataStorage<Region>::fields_names[folly::to_underlying(ord) - 1];
}
std::string_view Region::__fbthrift_get_class_name() {
  return apache::thrift::TStructDataStorage<Region>::name;
}


Region::Region(apache::thrift::FragileConstructor, ::std::int32_t regionId__arg, ::std::int32_t lastEntryEndOffset__arg, ::std::int32_t classId__arg, ::std::int32_t numItems__arg, bool pinned__arg, ::std::int32_t priority__arg) :
    __fbthrift_field_regionId(std::move(regionId__arg)),
    __fbthrift_field_lastEntryEndOffset(std::move(lastEntryEndOffset__arg)),
    __fbthrift_field_classId(std::move(classId__arg)),
    __fbthrift_field_numItems(std::move(numItems__arg)),
    __fbthrift_field_pinned(std::move(pinned__arg)),
    __fbthrift_field_priority(std::move(priority__arg)) { 
  __isset.set(folly::index_constant<0>(), true);
  __isset.set(folly::index_constant<1>(), true);
  __isset.set(folly::index_constant<2>(), true);
  __isset.set(folly::index_constant<3>(), true);
  __isset.set(folly::index_constant<4>(), true);
  __isset.set(folly::index_constant<5>(), true);
}

void Region::__fbthrift_clear() {
  // clear all fields
  this->__fbthrift_field_regionId = ::std::int32_t();
  this->__fbthrift_field_lastEntryEndOffset = ::std::int32_t();
  this->__fbthrift_field_classId = ::std::int32_t();
  this->__fbthrift_field_numItems = ::std::int32_t();
  this->__fbthrift_field_pinned = bool();
  this->__fbthrift_field_priority = ::std::int32_t();
  __isset = {};
}

bool Region::__fbthrift_is_empty() const {
  return false;
}

bool Region::operator==([[maybe_unused]] const Region& rhs) const {
  return ::apache::thrift::op::detail::StructEquality{}(*this, rhs);
}

bool Region::operator<([[maybe_unused]] const Region& rhs) const {
  return ::apache::thrift::op::detail::StructLessThan{}(*this, rhs);
}


::std::int32_t Region::get_regionId() const {
  return __fbthrift_field_regionId;
}

::std::int32_t& Region::set_regionId(::std::int32_t regionId_) {
  regionId_ref() = regionId_;
  return __fbthrift_field_regionId;
}

::std::int32_t Region::get_lastEntryEndOffset() const {
  return __fbthrift_field_lastEntryEndOffset;
}

::std::int32_t& Region::set_lastEntryEndOffset(::std::int32_t lastEntryEndOffset_) {
  lastEntryEndOffset_ref() = lastEntryEndOffset_;
  return __fbthrift_field_lastEntryEndOffset;
}

::std::int32_t Region::get_classId() const {
  return __fbthrift_field_classId;
}

::std::int32_t& Region::set_classId(::std::int32_t classId_) {
  classId_ref() = classId_;
  return __fbthrift_field_classId;
}

::std::int32_t Region::get_numItems() const {
  return __fbthrift_field_numItems;
}

::std::int32_t& Region::set_numItems(::std::int32_t numItems_) {
  numItems_ref() = numItems_;
  return __fbthrift_field_numItems;
}

bool Region::get_pinned() const {
  return __fbthrift_field_pinned;
}

bool& Region::set_pinned(bool pinned_) {
  pinned_ref() = pinned_;
  return __fbthrift_field_pinned;
}

::std::int32_t Region::get_priority() const {
  return __fbthrift_field_priority;
}

::std::int32_t& Region::set_priority(::std::int32_t priority_) {
  priority_ref() = priority_;
  return __fbthrift_field_priority;
}

void swap([[maybe_unused]] Region& a, [[maybe_unused]] Region& b) {
  using ::std::swap;
  swap(a.__fbthrift_field_regionId, b.__fbthrift_field_regionId);
  swap(a.__fbthrift_field_lastEntryEndOffset, b.__fbthrift_field_lastEntryEndOffset);
  swap(a.__fbthrift_field_classId, b.__fbthrift_field_classId);
  swap(a.__fbthrift_field_numItems, b.__fbthrift_field_numItems);
  swap(a.__fbthrift_field_pinned, b.__fbthrift_field_pinned);
  swap(a.__fbthrift_field_priority, b.__fbthrift_field_priority);
  swap(a.__isset, b.__isset);
}


} // namespace facebook::cachelib::navy::serialization


namespace facebook::cachelib::navy::serialization {

std::string_view RegionData::__fbthrift_get_field_name(::apache::thrift::FieldOrdinal ord) {
  if (ord == ::apache::thrift::FieldOrdinal{0}) { return {}; }
  return apache::thrift::TStructDataStorage<RegionData>::fields_names[folly::to_underlying(ord) - 1];
}
std::string_view RegionData::__fbthrift_get_class_name() {
  return apache::thrift::TStructDataStorage<RegionData>::name;
}

RegionData::RegionData(const RegionData&) = default;
RegionData& RegionData::operator=(const RegionData&) = default;
RegionData::RegionData() :
    __fbthrift_field_regionSize(static_cast<::std::int32_t>(0)) {
}


RegionData::~RegionData() {}

RegionData::RegionData([[maybe_unused]] RegionData&& other) noexcept :
    __fbthrift_field_regions(std::move(other.__fbthrift_field_regions)),
    __fbthrift_field_regionSize(std::move(other.__fbthrift_field_regionSize)),
    __isset(other.__isset) {
}

RegionData& RegionData::operator=([[maybe_unused]] RegionData&& other) noexcept {
    this->__fbthrift_field_regions = std::move(other.__fbthrift_field_regions);
    this->__fbthrift_field_regionSize = std::move(other.__fbthrift_field_regionSize);
    __isset = other.__isset;
    return *this;
}


RegionData::RegionData(apache::thrift::FragileConstructor, ::std::vector<::facebook::cachelib::navy::serialization::Region> regions__arg, ::std::int32_t regionSize__arg) :
    __fbthrift_field_regions(std::move(regions__arg)),
    __fbthrift_field_regionSize(std::move(regionSize__arg)) { 
  __isset.set(folly::index_constant<0>(), true);
  __isset.set(folly::index_constant<1>(), true);
}

void RegionData::__fbthrift_clear() {
  // clear all fields
  this->__fbthrift_field_regions.clear();
  this->__fbthrift_field_regionSize = ::std::int32_t();
  __isset = {};
}

bool RegionData::__fbthrift_is_empty() const {
  return false;
}

bool RegionData::operator==([[maybe_unused]] const RegionData& rhs) const {
  return ::apache::thrift::op::detail::StructEquality{}(*this, rhs);
}

bool RegionData::operator<([[maybe_unused]] const RegionData& rhs) const {
  return ::apache::thrift::op::detail::StructLessThan{}(*this, rhs);
}


const ::std::vector<::facebook::cachelib::navy::serialization::Region>& RegionData::get_regions() const& {
  return __fbthrift_field_regions;
}

::std::vector<::facebook::cachelib::navy::serialization::Region> RegionData::get_regions() && {
  return static_cast<::std::vector<::facebook::cachelib::navy::serialization::Region>&&>(__fbthrift_field_regions);
}

::std::int32_t RegionData::get_regionSize() const {
  return __fbthrift_field_regionSize;
}

::std::int32_t& RegionData::set_regionSize(::std::int32_t regionSize_) {
  regionSize_ref() = regionSize_;
  return __fbthrift_field_regionSize;
}

void swap([[maybe_unused]] RegionData& a, [[maybe_unused]] RegionData& b) {
  using ::std::swap;
  swap(a.__fbthrift_field_regions, b.__fbthrift_field_regions);
  swap(a.__fbthrift_field_regionSize, b.__fbthrift_field_regionSize);
  swap(a.__isset, b.__isset);
}

static_assert(
    ::apache::thrift::detail::st::gen_check_json<
        RegionData,
        ::apache::thrift::type_class::list<::apache::thrift::type_class::structure>,
        ::std::vector<::facebook::cachelib::navy::serialization::Region>>,
    "inconsistent use of json option");

} // namespace facebook::cachelib::navy::serialization


namespace facebook::cachelib::navy::serialization {

std::string_view FifoPolicyNodeData::__fbthrift_get_field_name(::apache::thrift::FieldOrdinal ord) {
  if (ord == ::apache::thrift::FieldOrdinal{0}) { return {}; }
  return apache::thrift::TStructDataStorage<FifoPolicyNodeData>::fields_names[folly::to_underlying(ord) - 1];
}
std::string_view FifoPolicyNodeData::__fbthrift_get_class_name() {
  return apache::thrift::TStructDataStorage<FifoPolicyNodeData>::name;
}


FifoPolicyNodeData::FifoPolicyNodeData(apache::thrift::FragileConstructor, ::std::int32_t idx__arg, ::std::int64_t trackTime__arg) :
    __fbthrift_field_idx(std::move(idx__arg)),
    __fbthrift_field_trackTime(std::move(trackTime__arg)) { 
  __isset.set(folly::index_constant<0>(), true);
  __isset.set(folly::index_constant<1>(), true);
}

void FifoPolicyNodeData::__fbthrift_clear() {
  // clear all fields
  this->__fbthrift_field_idx = ::std::int32_t();
  this->__fbthrift_field_trackTime = ::std::int64_t();
  __isset = {};
}

bool FifoPolicyNodeData::__fbthrift_is_empty() const {
  return false;
}

bool FifoPolicyNodeData::operator==([[maybe_unused]] const FifoPolicyNodeData& rhs) const {
  return ::apache::thrift::op::detail::StructEquality{}(*this, rhs);
}

bool FifoPolicyNodeData::operator<([[maybe_unused]] const FifoPolicyNodeData& rhs) const {
  return ::apache::thrift::op::detail::StructLessThan{}(*this, rhs);
}


::std::int32_t FifoPolicyNodeData::get_idx() const {
  return __fbthrift_field_idx;
}

::std::int32_t& FifoPolicyNodeData::set_idx(::std::int32_t idx_) {
  idx_ref() = idx_;
  return __fbthrift_field_idx;
}

::std::int64_t FifoPolicyNodeData::get_trackTime() const {
  return __fbthrift_field_trackTime;
}

::std::int64_t& FifoPolicyNodeData::set_trackTime(::std::int64_t trackTime_) {
  trackTime_ref() = trackTime_;
  return __fbthrift_field_trackTime;
}

void swap([[maybe_unused]] FifoPolicyNodeData& a, [[maybe_unused]] FifoPolicyNodeData& b) {
  using ::std::swap;
  swap(a.__fbthrift_field_idx, b.__fbthrift_field_idx);
  swap(a.__fbthrift_field_trackTime, b.__fbthrift_field_trackTime);
  swap(a.__isset, b.__isset);
}


} // namespace facebook::cachelib::navy::serialization


namespace facebook::cachelib::navy::serialization {

std::string_view FifoPolicyData::__fbthrift_get_field_name(::apache::thrift::FieldOrdinal ord) {
  if (ord == ::apache::thrift::FieldOrdinal{0}) { return {}; }
  return apache::thrift::TStructDataStorage<FifoPolicyData>::fields_names[folly::to_underlying(ord) - 1];
}
std::string_view FifoPolicyData::__fbthrift_get_class_name() {
  return apache::thrift::TStructDataStorage<FifoPolicyData>::name;
}

FifoPolicyData::FifoPolicyData(const FifoPolicyData&) = default;
FifoPolicyData& FifoPolicyData::operator=(const FifoPolicyData&) = default;
FifoPolicyData::FifoPolicyData() {
}


FifoPolicyData::~FifoPolicyData() {}

FifoPolicyData::FifoPolicyData([[maybe_unused]] FifoPolicyData&& other) noexcept :
    __fbthrift_field_queue(std::move(other.__fbthrift_field_queue)),
    __isset(other.__isset) {
}

FifoPolicyData& FifoPolicyData::operator=([[maybe_unused]] FifoPolicyData&& other) noexcept {
    this->__fbthrift_field_queue = std::move(other.__fbthrift_field_queue);
    __isset = other.__isset;
    return *this;
}


FifoPolicyData::FifoPolicyData(apache::thrift::FragileConstructor, ::std::vector<::facebook::cachelib::navy::serialization::FifoPolicyNodeData> queue__arg) :
    __fbthrift_field_queue(std::move(queue__arg)) { 
  __isset.set(folly::index_constant<0>(), true);
}

void FifoPolicyData::__fbthrift_clear() {
  // clear all fields
  this->__fbthrift_field_queue.clear();
  __isset = {};
}

bool FifoPolicyData::__fbthrift_is_empty() const {
  return false;
}

bool FifoPolicyData::operator==([[maybe_unused]] const FifoPolicyData& rhs) const {
  return ::apache::thrift::op::detail::StructEquality{}(*this, rhs);
}

bool FifoPolicyData::operator<([[maybe_unused]] const FifoPolicyData& rhs) const {
  return ::apache::thrift::op::detail::StructLessThan{}(*this, rhs);
}


const ::std::vector<::facebook::cachelib::navy::serialization::FifoPolicyNodeData>& FifoPolicyData::get_queue() const& {
  return __fbthrift_field_queue;
}

::std::vector<::facebook::cachelib::navy::serialization::FifoPolicyNodeData> FifoPolicyData::get_queue() && {
  return static_cast<::std::vector<::facebook::cachelib::navy::serialization::FifoPolicyNodeData>&&>(__fbthrift_field_queue);
}

void swap([[maybe_unused]] FifoPolicyData& a, [[maybe_unused]] FifoPolicyData& b) {
  using ::std::swap;
  swap(a.__fbthrift_field_queue, b.__fbthrift_field_queue);
  swap(a.__isset, b.__isset);
}

static_assert(
    ::apache::thrift::detail::st::gen_check_json<
        FifoPolicyData,
        ::apache::thrift::type_class::list<::apache::thrift::type_class::structure>,
        ::std::vector<::facebook::cachelib::navy::serialization::FifoPolicyNodeData>>,
    "inconsistent use of json option");

} // namespace facebook::cachelib::navy::serialization


namespace facebook::cachelib::navy::serialization {

std::string_view AccessStats::__fbthrift_get_field_name(::apache::thrift::FieldOrdinal ord) {
  if (ord == ::apache::thrift::FieldOrdinal{0}) { return {}; }
  return apache::thrift::TStructDataStorage<AccessStats>::fields_names[folly::to_underlying(ord) - 1];
}
std::string_view AccessStats::__fbthrift_get_class_name() {
  return apache::thrift::TStructDataStorage<AccessStats>::name;
}

AccessStats::AccessStats(const AccessStats&) = default;
AccessStats& AccessStats::operator=(const AccessStats&) = default;
AccessStats::AccessStats([[maybe_unused]] AccessStats&& other) noexcept :
    __fbthrift_field_totalHits(std::move(other.__fbthrift_field_totalHits)),
    __fbthrift_field_currHits(std::move(other.__fbthrift_field_currHits)),
    __fbthrift_field_numReinsertions(std::move(other.__fbthrift_field_numReinsertions)),
    __isset(other.__isset) {
}

AccessStats& AccessStats::operator=([[maybe_unused]] AccessStats&& other) noexcept {
    this->__fbthrift_field_totalHits = std::move(other.__fbthrift_field_totalHits);
    this->__fbthrift_field_currHits = std::move(other.__fbthrift_field_currHits);
    this->__fbthrift_field_numReinsertions = std::move(other.__fbthrift_field_numReinsertions);
    __isset = other.__isset;
    return *this;
}


AccessStats::AccessStats(apache::thrift::FragileConstructor, ::std::int8_t totalHits__arg, ::std::int8_t currHits__arg, ::std::int8_t numReinsertions__arg) :
    __fbthrift_field_totalHits(std::move(totalHits__arg)),
    __fbthrift_field_currHits(std::move(currHits__arg)),
    __fbthrift_field_numReinsertions(std::move(numReinsertions__arg)) { 
  __isset.set(folly::index_constant<0>(), true);
  __isset.set(folly::index_constant<1>(), true);
  __isset.set(folly::index_constant<2>(), true);
}

void AccessStats::__fbthrift_clear() {
  // clear all fields
  this->__fbthrift_field_totalHits = ::std::int8_t();
  this->__fbthrift_field_currHits = ::std::int8_t();
  this->__fbthrift_field_numReinsertions = ::std::int8_t();
  __isset = {};
}

bool AccessStats::__fbthrift_is_empty() const {
  return false;
}

bool AccessStats::operator==([[maybe_unused]] const AccessStats& rhs) const {
  return ::apache::thrift::op::detail::StructEquality{}(*this, rhs);
}

bool AccessStats::operator<([[maybe_unused]] const AccessStats& rhs) const {
  return ::apache::thrift::op::detail::StructLessThan{}(*this, rhs);
}


::std::int8_t AccessStats::get_totalHits() const {
  return __fbthrift_field_totalHits;
}

::std::int8_t& AccessStats::set_totalHits(::std::int8_t totalHits_) {
  totalHits_ref() = totalHits_;
  return __fbthrift_field_totalHits;
}

::std::int8_t AccessStats::get_currHits() const {
  return __fbthrift_field_currHits;
}

::std::int8_t& AccessStats::set_currHits(::std::int8_t currHits_) {
  currHits_ref() = currHits_;
  return __fbthrift_field_currHits;
}

::std::int8_t AccessStats::get_numReinsertions() const {
  return __fbthrift_field_numReinsertions;
}

::std::int8_t& AccessStats::set_numReinsertions(::std::int8_t numReinsertions_) {
  numReinsertions_ref() = numReinsertions_;
  return __fbthrift_field_numReinsertions;
}

void swap([[maybe_unused]] AccessStats& a, [[maybe_unused]] AccessStats& b) {
  using ::std::swap;
  swap(a.__fbthrift_field_totalHits, b.__fbthrift_field_totalHits);
  swap(a.__fbthrift_field_currHits, b.__fbthrift_field_currHits);
  swap(a.__fbthrift_field_numReinsertions, b.__fbthrift_field_numReinsertions);
  swap(a.__isset, b.__isset);
}


} // namespace facebook::cachelib::navy::serialization


namespace facebook::cachelib::navy::serialization {

std::string_view AccessStatsPair::__fbthrift_get_field_name(::apache::thrift::FieldOrdinal ord) {
  if (ord == ::apache::thrift::FieldOrdinal{0}) { return {}; }
  return apache::thrift::TStructDataStorage<AccessStatsPair>::fields_names[folly::to_underlying(ord) - 1];
}
std::string_view AccessStatsPair::__fbthrift_get_class_name() {
  return apache::thrift::TStructDataStorage<AccessStatsPair>::name;
}

AccessStatsPair::AccessStatsPair(const AccessStatsPair&) = default;
AccessStatsPair& AccessStatsPair::operator=(const AccessStatsPair&) = default;
AccessStatsPair::AccessStatsPair([[maybe_unused]] AccessStatsPair&& other) noexcept :
    __fbthrift_field_key(std::move(other.__fbthrift_field_key)),
    __fbthrift_field_stats(std::move(other.__fbthrift_field_stats)),
    __isset(other.__isset) {
}

AccessStatsPair& AccessStatsPair::operator=([[maybe_unused]] AccessStatsPair&& other) noexcept {
    this->__fbthrift_field_key = std::move(other.__fbthrift_field_key);
    this->__fbthrift_field_stats = std::move(other.__fbthrift_field_stats);
    __isset = other.__isset;
    return *this;
}


AccessStatsPair::AccessStatsPair(apache::thrift::FragileConstructor, ::std::int64_t key__arg, ::facebook::cachelib::navy::serialization::AccessStats stats__arg) :
    __fbthrift_field_key(std::move(key__arg)),
    __fbthrift_field_stats(std::move(stats__arg)) { 
  __isset.set(folly::index_constant<0>(), true);
  __isset.set(folly::index_constant<1>(), true);
}

void AccessStatsPair::__fbthrift_clear() {
  // clear all fields
  this->__fbthrift_field_key = ::std::int64_t();
  ::apache::thrift::clear(this->__fbthrift_field_stats);
  __isset = {};
}

bool AccessStatsPair::__fbthrift_is_empty() const {
  return false;
}

bool AccessStatsPair::operator==([[maybe_unused]] const AccessStatsPair& rhs) const {
  return ::apache::thrift::op::detail::StructEquality{}(*this, rhs);
}

bool AccessStatsPair::operator<([[maybe_unused]] const AccessStatsPair& rhs) const {
  return ::apache::thrift::op::detail::StructLessThan{}(*this, rhs);
}


::std::int64_t AccessStatsPair::get_key() const {
  return __fbthrift_field_key;
}

::std::int64_t& AccessStatsPair::set_key(::std::int64_t key_) {
  key_ref() = key_;
  return __fbthrift_field_key;
}

const ::facebook::cachelib::navy::serialization::AccessStats& AccessStatsPair::get_stats() const& {
  return __fbthrift_field_stats;
}

::facebook::cachelib::navy::serialization::AccessStats AccessStatsPair::get_stats() && {
  return static_cast<::facebook::cachelib::navy::serialization::AccessStats&&>(__fbthrift_field_stats);
}

void swap([[maybe_unused]] AccessStatsPair& a, [[maybe_unused]] AccessStatsPair& b) {
  using ::std::swap;
  swap(a.__fbthrift_field_key, b.__fbthrift_field_key);
  swap(a.__fbthrift_field_stats, b.__fbthrift_field_stats);
  swap(a.__isset, b.__isset);
}

static_assert(
    ::apache::thrift::detail::st::gen_check_json<
        AccessStatsPair,
        ::apache::thrift::type_class::structure,
        ::facebook::cachelib::navy::serialization::AccessStats>,
    "inconsistent use of json option");

} // namespace facebook::cachelib::navy::serialization


namespace facebook::cachelib::navy::serialization {

std::string_view AccessTracker::__fbthrift_get_field_name(::apache::thrift::FieldOrdinal ord) {
  if (ord == ::apache::thrift::FieldOrdinal{0}) { return {}; }
  return apache::thrift::TStructDataStorage<AccessTracker>::fields_names[folly::to_underlying(ord) - 1];
}
std::string_view AccessTracker::__fbthrift_get_class_name() {
  return apache::thrift::TStructDataStorage<AccessTracker>::name;
}

AccessTracker::AccessTracker(const AccessTracker&) = default;
AccessTracker& AccessTracker::operator=(const AccessTracker&) = default;
AccessTracker::AccessTracker() {
}


AccessTracker::~AccessTracker() {}

AccessTracker::AccessTracker([[maybe_unused]] AccessTracker&& other) noexcept :
    __fbthrift_field_deprecated_data(std::move(other.__fbthrift_field_deprecated_data)),
    __fbthrift_field_data(std::move(other.__fbthrift_field_data)),
    __isset(other.__isset) {
}

AccessTracker& AccessTracker::operator=([[maybe_unused]] AccessTracker&& other) noexcept {
    this->__fbthrift_field_deprecated_data = std::move(other.__fbthrift_field_deprecated_data);
    this->__fbthrift_field_data = std::move(other.__fbthrift_field_data);
    __isset = other.__isset;
    return *this;
}


AccessTracker::AccessTracker(apache::thrift::FragileConstructor, ::std::map<::std::int64_t, ::facebook::cachelib::navy::serialization::AccessStats> deprecated_data__arg, ::std::vector<::facebook::cachelib::navy::serialization::AccessStatsPair> data__arg) :
    __fbthrift_field_deprecated_data(std::move(deprecated_data__arg)),
    __fbthrift_field_data(std::move(data__arg)) { 
  __isset.set(folly::index_constant<0>(), true);
  __isset.set(folly::index_constant<1>(), true);
}

void AccessTracker::__fbthrift_clear() {
  // clear all fields
  this->__fbthrift_field_deprecated_data.clear();
  this->__fbthrift_field_data.clear();
  __isset = {};
}

bool AccessTracker::__fbthrift_is_empty() const {
  return false;
}

bool AccessTracker::operator==([[maybe_unused]] const AccessTracker& rhs) const {
  return ::apache::thrift::op::detail::StructEquality{}(*this, rhs);
}

bool AccessTracker::operator<([[maybe_unused]] const AccessTracker& rhs) const {
  return ::apache::thrift::op::detail::StructLessThan{}(*this, rhs);
}


const ::std::map<::std::int64_t, ::facebook::cachelib::navy::serialization::AccessStats>& AccessTracker::get_deprecated_data() const& {
  return __fbthrift_field_deprecated_data;
}

::std::map<::std::int64_t, ::facebook::cachelib::navy::serialization::AccessStats> AccessTracker::get_deprecated_data() && {
  return static_cast<::std::map<::std::int64_t, ::facebook::cachelib::navy::serialization::AccessStats>&&>(__fbthrift_field_deprecated_data);
}

const ::std::vector<::facebook::cachelib::navy::serialization::AccessStatsPair>& AccessTracker::get_data() const& {
  return __fbthrift_field_data;
}

::std::vector<::facebook::cachelib::navy::serialization::AccessStatsPair> AccessTracker::get_data() && {
  return static_cast<::std::vector<::facebook::cachelib::navy::serialization::AccessStatsPair>&&>(__fbthrift_field_data);
}

void swap([[maybe_unused]] AccessTracker& a, [[maybe_unused]] AccessTracker& b) {
  using ::std::swap;
  swap(a.__fbthrift_field_deprecated_data, b.__fbthrift_field_deprecated_data);
  swap(a.__fbthrift_field_data, b.__fbthrift_field_data);
  swap(a.__isset, b.__isset);
}

static_assert(
    ::apache::thrift::detail::st::gen_check_json<
        AccessTracker,
        ::apache::thrift::type_class::map<::apache::thrift::type_class::integral, ::apache::thrift::type_class::structure>,
        ::std::map<::std::int64_t, ::facebook::cachelib::navy::serialization::AccessStats>>,
    "inconsistent use of json option");
static_assert(
    ::apache::thrift::detail::st::gen_check_json<
        AccessTracker,
        ::apache::thrift::type_class::list<::apache::thrift::type_class::structure>,
        ::std::vector<::facebook::cachelib::navy::serialization::AccessStatsPair>>,
    "inconsistent use of json option");

} // namespace facebook::cachelib::navy::serialization


namespace facebook::cachelib::navy::serialization {

std::string_view BlockCacheConfig::__fbthrift_get_field_name(::apache::thrift::FieldOrdinal ord) {
  if (ord == ::apache::thrift::FieldOrdinal{0}) { return {}; }
  return apache::thrift::TStructDataStorage<BlockCacheConfig>::fields_names[folly::to_underlying(ord) - 1];
}
std::string_view BlockCacheConfig::__fbthrift_get_class_name() {
  return apache::thrift::TStructDataStorage<BlockCacheConfig>::name;
}

BlockCacheConfig::BlockCacheConfig(const BlockCacheConfig&) = default;
BlockCacheConfig& BlockCacheConfig::operator=(const BlockCacheConfig&) = default;
BlockCacheConfig::BlockCacheConfig() :
    __fbthrift_field_version(static_cast<::std::int64_t>(0)),
    __fbthrift_field_cacheBaseOffset(static_cast<::std::int64_t>(0)),
    __fbthrift_field_cacheSize(static_cast<::std::int64_t>(0)),
    __fbthrift_field_allocAlignSize(static_cast<::std::int32_t>(0)),
    __fbthrift_field_checksum(false),
    __fbthrift_field_holeCount(static_cast<::std::int64_t>(0)),
    __fbthrift_field_holeSizeTotal(static_cast<::std::int64_t>(0)),
    __fbthrift_field_reinsertionPolicyEnabled(false),
    __fbthrift_field_usedSizeBytes(static_cast<::std::int64_t>(0)) {
}


BlockCacheConfig::~BlockCacheConfig() {}

BlockCacheConfig::BlockCacheConfig([[maybe_unused]] BlockCacheConfig&& other) noexcept :
    __fbthrift_field_version(std::move(other.__fbthrift_field_version)),
    __fbthrift_field_cacheBaseOffset(std::move(other.__fbthrift_field_cacheBaseOffset)),
    __fbthrift_field_cacheSize(std::move(other.__fbthrift_field_cacheSize)),
    __fbthrift_field_allocAlignSize(std::move(other.__fbthrift_field_allocAlignSize)),
    __fbthrift_field_deprecated_sizeClasses(std::move(other.__fbthrift_field_deprecated_sizeClasses)),
    __fbthrift_field_checksum(std::move(other.__fbthrift_field_checksum)),
    __fbthrift_field_deprecated_sizeDist(std::move(other.__fbthrift_field_deprecated_sizeDist)),
    __fbthrift_field_holeCount(std::move(other.__fbthrift_field_holeCount)),
    __fbthrift_field_holeSizeTotal(std::move(other.__fbthrift_field_holeSizeTotal)),
    __fbthrift_field_reinsertionPolicyEnabled(std::move(other.__fbthrift_field_reinsertionPolicyEnabled)),
    __fbthrift_field_usedSizeBytes(std::move(other.__fbthrift_field_usedSizeBytes)),
    __isset(other.__isset) {
}

BlockCacheConfig& BlockCacheConfig::operator=([[maybe_unused]] BlockCacheConfig&& other) noexcept {
    this->__fbthrift_field_version = std::move(other.__fbthrift_field_version);
    this->__fbthrift_field_cacheBaseOffset = std::move(other.__fbthrift_field_cacheBaseOffset);
    this->__fbthrift_field_cacheSize = std::move(other.__fbthrift_field_cacheSize);
    this->__fbthrift_field_allocAlignSize = std::move(other.__fbthrift_field_allocAlignSize);
    this->__fbthrift_field_deprecated_sizeClasses = std::move(other.__fbthrift_field_deprecated_sizeClasses);
    this->__fbthrift_field_checksum = std::move(other.__fbthrift_field_checksum);
    this->__fbthrift_field_deprecated_sizeDist = std::move(other.__fbthrift_field_deprecated_sizeDist);
    this->__fbthrift_field_holeCount = std::move(other.__fbthrift_field_holeCount);
    this->__fbthrift_field_holeSizeTotal = std::move(other.__fbthrift_field_holeSizeTotal);
    this->__fbthrift_field_reinsertionPolicyEnabled = std::move(other.__fbthrift_field_reinsertionPolicyEnabled);
    this->__fbthrift_field_usedSizeBytes = std::move(other.__fbthrift_field_usedSizeBytes);
    __isset = other.__isset;
    return *this;
}


BlockCacheConfig::BlockCacheConfig(apache::thrift::FragileConstructor, ::std::int64_t version__arg, ::std::int64_t cacheBaseOffset__arg, ::std::int64_t cacheSize__arg, ::std::int32_t allocAlignSize__arg, ::std::set<::std::int32_t> deprecated_sizeClasses__arg, bool checksum__arg, ::std::map<::std::int64_t, ::std::int64_t> deprecated_sizeDist__arg, ::std::int64_t holeCount__arg, ::std::int64_t holeSizeTotal__arg, bool reinsertionPolicyEnabled__arg, ::std::int64_t usedSizeBytes__arg) :
    __fbthrift_field_version(std::move(version__arg)),
    __fbthrift_field_cacheBaseOffset(std::move(cacheBaseOffset__arg)),
    __fbthrift_field_cacheSize(std::move(cacheSize__arg)),
    __fbthrift_field_allocAlignSize(std::move(allocAlignSize__arg)),
    __fbthrift_field_deprecated_sizeClasses(std::move(deprecated_sizeClasses__arg)),
    __fbthrift_field_checksum(std::move(checksum__arg)),
    __fbthrift_field_deprecated_sizeDist(std::move(deprecated_sizeDist__arg)),
    __fbthrift_field_holeCount(std::move(holeCount__arg)),
    __fbthrift_field_holeSizeTotal(std::move(holeSizeTotal__arg)),
    __fbthrift_field_reinsertionPolicyEnabled(std::move(reinsertionPolicyEnabled__arg)),
    __fbthrift_field_usedSizeBytes(std::move(usedSizeBytes__arg)) { 
  __isset.set(folly::index_constant<0>(), true);
  __isset.set(folly::index_constant<1>(), true);
  __isset.set(folly::index_constant<2>(), true);
  __isset.set(folly::index_constant<3>(), true);
  __isset.set(folly::index_constant<4>(), true);
  __isset.set(folly::index_constant<5>(), true);
  __isset.set(folly::index_constant<6>(), true);
  __isset.set(folly::index_constant<7>(), true);
  __isset.set(folly::index_constant<8>(), true);
  __isset.set(folly::index_constant<9>(), true);
  __isset.set(folly::index_constant<10>(), true);
}

void BlockCacheConfig::__fbthrift_clear() {
  // clear all fields
  this->__fbthrift_field_version = ::std::int64_t();
  this->__fbthrift_field_cacheBaseOffset = ::std::int64_t();
  this->__fbthrift_field_cacheSize = ::std::int64_t();
  this->__fbthrift_field_allocAlignSize = ::std::int32_t();
  this->__fbthrift_field_deprecated_sizeClasses.clear();
  this->__fbthrift_field_checksum = bool();
  this->__fbthrift_field_deprecated_sizeDist.clear();
  this->__fbthrift_field_holeCount = ::std::int64_t();
  this->__fbthrift_field_holeSizeTotal = ::std::int64_t();
  this->__fbthrift_field_reinsertionPolicyEnabled = bool();
  this->__fbthrift_field_usedSizeBytes = ::std::int64_t();
  __isset = {};
}

bool BlockCacheConfig::__fbthrift_is_empty() const {
  return false;
}

bool BlockCacheConfig::operator==([[maybe_unused]] const BlockCacheConfig& rhs) const {
  return ::apache::thrift::op::detail::StructEquality{}(*this, rhs);
}

bool BlockCacheConfig::operator<([[maybe_unused]] const BlockCacheConfig& rhs) const {
  return ::apache::thrift::op::detail::StructLessThan{}(*this, rhs);
}


::std::int64_t BlockCacheConfig::get_version() const {
  return __fbthrift_field_version;
}

::std::int64_t& BlockCacheConfig::set_version(::std::int64_t version_) {
  version_ref() = version_;
  return __fbthrift_field_version;
}

::std::int64_t BlockCacheConfig::get_cacheBaseOffset() const {
  return __fbthrift_field_cacheBaseOffset;
}

::std::int64_t& BlockCacheConfig::set_cacheBaseOffset(::std::int64_t cacheBaseOffset_) {
  cacheBaseOffset_ref() = cacheBaseOffset_;
  return __fbthrift_field_cacheBaseOffset;
}

::std::int64_t BlockCacheConfig::get_cacheSize() const {
  return __fbthrift_field_cacheSize;
}

::std::int64_t& BlockCacheConfig::set_cacheSize(::std::int64_t cacheSize_) {
  cacheSize_ref() = cacheSize_;
  return __fbthrift_field_cacheSize;
}

::std::int32_t BlockCacheConfig::get_allocAlignSize() const {
  return __fbthrift_field_allocAlignSize;
}

::std::int32_t& BlockCacheConfig::set_allocAlignSize(::std::int32_t allocAlignSize_) {
  allocAlignSize_ref() = allocAlignSize_;
  return __fbthrift_field_allocAlignSize;
}

const ::std::set<::std::int32_t>& BlockCacheConfig::get_deprecated_sizeClasses() const& {
  return __fbthrift_field_deprecated_sizeClasses;
}

::std::set<::std::int32_t> BlockCacheConfig::get_deprecated_sizeClasses() && {
  return static_cast<::std::set<::std::int32_t>&&>(__fbthrift_field_deprecated_sizeClasses);
}

bool BlockCacheConfig::get_checksum() const {
  return __fbthrift_field_checksum;
}

bool& BlockCacheConfig::set_checksum(bool checksum_) {
  checksum_ref() = checksum_;
  return __fbthrift_field_checksum;
}

const ::std::map<::std::int64_t, ::std::int64_t>& BlockCacheConfig::get_deprecated_sizeDist() const& {
  return __fbthrift_field_deprecated_sizeDist;
}

::std::map<::std::int64_t, ::std::int64_t> BlockCacheConfig::get_deprecated_sizeDist() && {
  return static_cast<::std::map<::std::int64_t, ::std::int64_t>&&>(__fbthrift_field_deprecated_sizeDist);
}

::std::int64_t BlockCacheConfig::get_holeCount() const {
  return __fbthrift_field_holeCount;
}

::std::int64_t& BlockCacheConfig::set_holeCount(::std::int64_t holeCount_) {
  holeCount_ref() = holeCount_;
  return __fbthrift_field_holeCount;
}

::std::int64_t BlockCacheConfig::get_holeSizeTotal() const {
  return __fbthrift_field_holeSizeTotal;
}

::std::int64_t& BlockCacheConfig::set_holeSizeTotal(::std::int64_t holeSizeTotal_) {
  holeSizeTotal_ref() = holeSizeTotal_;
  return __fbthrift_field_holeSizeTotal;
}

bool BlockCacheConfig::get_reinsertionPolicyEnabled() const {
  return __fbthrift_field_reinsertionPolicyEnabled;
}

bool& BlockCacheConfig::set_reinsertionPolicyEnabled(bool reinsertionPolicyEnabled_) {
  reinsertionPolicyEnabled_ref() = reinsertionPolicyEnabled_;
  return __fbthrift_field_reinsertionPolicyEnabled;
}

::std::int64_t BlockCacheConfig::get_usedSizeBytes() const {
  return __fbthrift_field_usedSizeBytes;
}

::std::int64_t& BlockCacheConfig::set_usedSizeBytes(::std::int64_t usedSizeBytes_) {
  usedSizeBytes_ref() = usedSizeBytes_;
  return __fbthrift_field_usedSizeBytes;
}

void swap([[maybe_unused]] BlockCacheConfig& a, [[maybe_unused]] BlockCacheConfig& b) {
  using ::std::swap;
  swap(a.__fbthrift_field_version, b.__fbthrift_field_version);
  swap(a.__fbthrift_field_cacheBaseOffset, b.__fbthrift_field_cacheBaseOffset);
  swap(a.__fbthrift_field_cacheSize, b.__fbthrift_field_cacheSize);
  swap(a.__fbthrift_field_allocAlignSize, b.__fbthrift_field_allocAlignSize);
  swap(a.__fbthrift_field_deprecated_sizeClasses, b.__fbthrift_field_deprecated_sizeClasses);
  swap(a.__fbthrift_field_checksum, b.__fbthrift_field_checksum);
  swap(a.__fbthrift_field_deprecated_sizeDist, b.__fbthrift_field_deprecated_sizeDist);
  swap(a.__fbthrift_field_holeCount, b.__fbthrift_field_holeCount);
  swap(a.__fbthrift_field_holeSizeTotal, b.__fbthrift_field_holeSizeTotal);
  swap(a.__fbthrift_field_reinsertionPolicyEnabled, b.__fbthrift_field_reinsertionPolicyEnabled);
  swap(a.__fbthrift_field_usedSizeBytes, b.__fbthrift_field_usedSizeBytes);
  swap(a.__isset, b.__isset);
}


} // namespace facebook::cachelib::navy::serialization


namespace facebook::cachelib::navy::serialization {

std::string_view ValidBucketCheckerState::__fbthrift_get_field_name(::apache::thrift::FieldOrdinal ord) {
  if (ord == ::apache::thrift::FieldOrdinal{0}) { return {}; }
  return apache::thrift::TStructDataStorage<ValidBucketCheckerState>::fields_names[folly::to_underlying(ord) - 1];
}
std::string_view ValidBucketCheckerState::__fbthrift_get_class_name() {
  return apache::thrift::TStructDataStorage<ValidBucketCheckerState>::name;
}

ValidBucketCheckerState::ValidBucketCheckerState(const ValidBucketCheckerState&) = default;
ValidBucketCheckerState& ValidBucketCheckerState::operator=(const ValidBucketCheckerState&) = default;
ValidBucketCheckerState::ValidBucketCheckerState() :
    __fbthrift_field_numBuckets(static_cast<::std::int32_t>(0)),
    __fbthrift_field_numBucketsPerBit(static_cast<::std::int32_t>(0)),
    __fbthrift_field_numDisabledBuckets(static_cast<::std::int32_t>(0)) {
}


ValidBucketCheckerState::~ValidBucketCheckerState() {}

ValidBucketCheckerState::ValidBucketCheckerState([[maybe_unused]] ValidBucketCheckerState&& other) noexcept :
    __fbthrift_field_numBuckets(std::move(other.__fbthrift_field_numBuckets)),
    __fbthrift_field_numBucketsPerBit(std::move(other.__fbthrift_field_numBucketsPerBit)),
    __fbthrift_field_numDisabledBuckets(std::move(other.__fbthrift_field_numDisabledBuckets)),
    __fbthrift_field_bytes(std::move(other.__fbthrift_field_bytes)),
    __isset(other.__isset) {
}

ValidBucketCheckerState& ValidBucketCheckerState::operator=([[maybe_unused]] ValidBucketCheckerState&& other) noexcept {
    this->__fbthrift_field_numBuckets = std::move(other.__fbthrift_field_numBuckets);
    this->__fbthrift_field_numBucketsPerBit = std::move(other.__fbthrift_field_numBucketsPerBit);
    this->__fbthrift_field_numDisabledBuckets = std::move(other.__fbthrift_field_numDisabledBuckets);
    this->__fbthrift_field_bytes = std::move(other.__fbthrift_field_bytes);
    __isset = other.__isset;
    return *this;
}


ValidBucketCheckerState::ValidBucketCheckerState(apache::thrift::FragileConstructor, ::std::int32_t numBuckets__arg, ::std::int32_t numBucketsPerBit__arg, ::std::int32_t numDisabledBuckets__arg, ::std::vector<::std::int8_t> bytes__arg) :
    __fbthrift_field_numBuckets(std::move(numBuckets__arg)),
    __fbthrift_field_numBucketsPerBit(std::move(numBucketsPerBit__arg)),
    __fbthrift_field_numDisabledBuckets(std::move(numDisabledBuckets__arg)),
    __fbthrift_field_bytes(std::move(bytes__arg)) { 
  __isset.set(folly::index_constant<0>(), true);
  __isset.set(folly::index_constant<1>(), true);
  __isset.set(folly::index_constant<2>(), true);
  __isset.set(folly::index_constant<3>(), true);
}

void ValidBucketCheckerState::__fbthrift_clear() {
  // clear all fields
  this->__fbthrift_field_numBuckets = ::std::int32_t();
  this->__fbthrift_field_numBucketsPerBit = ::std::int32_t();
  this->__fbthrift_field_numDisabledBuckets = ::std::int32_t();
  this->__fbthrift_field_bytes.clear();
  __isset = {};
}

bool ValidBucketCheckerState::__fbthrift_is_empty() const {
  return false;
}

bool ValidBucketCheckerState::operator==([[maybe_unused]] const ValidBucketCheckerState& rhs) const {
  return ::apache::thrift::op::detail::StructEquality{}(*this, rhs);
}

bool ValidBucketCheckerState::operator<([[maybe_unused]] const ValidBucketCheckerState& rhs) const {
  return ::apache::thrift::op::detail::StructLessThan{}(*this, rhs);
}


::std::int32_t ValidBucketCheckerState::get_numBuckets() const {
  return __fbthrift_field_numBuckets;
}

::std::int32_t& ValidBucketCheckerState::set_numBuckets(::std::int32_t numBuckets_) {
  numBuckets_ref() = numBuckets_;
  return __fbthrift_field_numBuckets;
}

::std::int32_t ValidBucketCheckerState::get_numBucketsPerBit() const {
  return __fbthrift_field_numBucketsPerBit;
}

::std::int32_t& ValidBucketCheckerState::set_numBucketsPerBit(::std::int32_t numBucketsPerBit_) {
  numBucketsPerBit_ref() = numBucketsPerBit_;
  return __fbthrift_field_numBucketsPerBit;
}

::std::int32_t ValidBucketCheckerState::get_numDisabledBuckets() const {
  return __fbthrift_field_numDisabledBuckets;
}

::std::int32_t& ValidBucketCheckerState::set_numDisabledBuckets(::std::int32_t numDisabledBuckets_) {
  numDisabledBuckets_ref() = numDisabledBuckets_;
  return __fbthrift_field_numDisabledBuckets;
}

const ::std::vector<::std::int8_t>& ValidBucketCheckerState::get_bytes() const& {
  return __fbthrift_field_bytes;
}

::std::vector<::std::int8_t> ValidBucketCheckerState::get_bytes() && {
  return static_cast<::std::vector<::std::int8_t>&&>(__fbthrift_field_bytes);
}

void swap([[maybe_unused]] ValidBucketCheckerState& a, [[maybe_unused]] ValidBucketCheckerState& b) {
  using ::std::swap;
  swap(a.__fbthrift_field_numBuckets, b.__fbthrift_field_numBuckets);
  swap(a.__fbthrift_field_numBucketsPerBit, b.__fbthrift_field_numBucketsPerBit);
  swap(a.__fbthrift_field_numDisabledBuckets, b.__fbthrift_field_numDisabledBuckets);
  swap(a.__fbthrift_field_bytes, b.__fbthrift_field_bytes);
  swap(a.__isset, b.__isset);
}


} // namespace facebook::cachelib::navy::serialization


namespace facebook::cachelib::navy::serialization {

std::string_view BigHashPersistentData::__fbthrift_get_field_name(::apache::thrift::FieldOrdinal ord) {
  if (ord == ::apache::thrift::FieldOrdinal{0}) { return {}; }
  return apache::thrift::TStructDataStorage<BigHashPersistentData>::fields_names[folly::to_underlying(ord) - 1];
}
std::string_view BigHashPersistentData::__fbthrift_get_class_name() {
  return apache::thrift::TStructDataStorage<BigHashPersistentData>::name;
}

BigHashPersistentData::BigHashPersistentData(const BigHashPersistentData&) = default;
BigHashPersistentData& BigHashPersistentData::operator=(const BigHashPersistentData&) = default;
BigHashPersistentData::BigHashPersistentData() :
    __fbthrift_field_version(static_cast<::std::int32_t>(0)),
    __fbthrift_field_generationTime(static_cast<::std::int64_t>(0)),
    __fbthrift_field_itemCount(static_cast<::std::int64_t>(0)),
    __fbthrift_field_bucketSize(static_cast<::std::int64_t>(0)),
    __fbthrift_field_cacheBaseOffset(static_cast<::std::int64_t>(0)),
    __fbthrift_field_numBuckets(static_cast<::std::int64_t>(0)),
    __fbthrift_field_usedSizeBytes(static_cast<::std::int64_t>(0)) {
}


BigHashPersistentData::~BigHashPersistentData() {}

BigHashPersistentData::BigHashPersistentData([[maybe_unused]] BigHashPersistentData&& other) noexcept :
    __fbthrift_field_version(std::move(other.__fbthrift_field_version)),
    __fbthrift_field_generationTime(std::move(other.__fbthrift_field_generationTime)),
    __fbthrift_field_itemCount(std::move(other.__fbthrift_field_itemCount)),
    __fbthrift_field_bucketSize(std::move(other.__fbthrift_field_bucketSize)),
    __fbthrift_field_cacheBaseOffset(std::move(other.__fbthrift_field_cacheBaseOffset)),
    __fbthrift_field_numBuckets(std::move(other.__fbthrift_field_numBuckets)),
    __fbthrift_field_deprecated_sizeDist(std::move(other.__fbthrift_field_deprecated_sizeDist)),
    __fbthrift_field_usedSizeBytes(std::move(other.__fbthrift_field_usedSizeBytes)),
    __fbthrift_field_validBucketCheckerState(std::move(other.__fbthrift_field_validBucketCheckerState)),
    __isset(other.__isset) {
}

BigHashPersistentData& BigHashPersistentData::operator=([[maybe_unused]] BigHashPersistentData&& other) noexcept {
    this->__fbthrift_field_version = std::move(other.__fbthrift_field_version);
    this->__fbthrift_field_generationTime = std::move(other.__fbthrift_field_generationTime);
    this->__fbthrift_field_itemCount = std::move(other.__fbthrift_field_itemCount);
    this->__fbthrift_field_bucketSize = std::move(other.__fbthrift_field_bucketSize);
    this->__fbthrift_field_cacheBaseOffset = std::move(other.__fbthrift_field_cacheBaseOffset);
    this->__fbthrift_field_numBuckets = std::move(other.__fbthrift_field_numBuckets);
    this->__fbthrift_field_deprecated_sizeDist = std::move(other.__fbthrift_field_deprecated_sizeDist);
    this->__fbthrift_field_usedSizeBytes = std::move(other.__fbthrift_field_usedSizeBytes);
    this->__fbthrift_field_validBucketCheckerState = std::move(other.__fbthrift_field_validBucketCheckerState);
    __isset = other.__isset;
    return *this;
}


BigHashPersistentData::BigHashPersistentData(apache::thrift::FragileConstructor, ::std::int32_t version__arg, ::std::int64_t generationTime__arg, ::std::int64_t itemCount__arg, ::std::int64_t bucketSize__arg, ::std::int64_t cacheBaseOffset__arg, ::std::int64_t numBuckets__arg, ::std::map<::std::int64_t, ::std::int64_t> deprecated_sizeDist__arg, ::std::int64_t usedSizeBytes__arg, ::facebook::cachelib::navy::serialization::ValidBucketCheckerState validBucketCheckerState__arg) :
    __fbthrift_field_version(std::move(version__arg)),
    __fbthrift_field_generationTime(std::move(generationTime__arg)),
    __fbthrift_field_itemCount(std::move(itemCount__arg)),
    __fbthrift_field_bucketSize(std::move(bucketSize__arg)),
    __fbthrift_field_cacheBaseOffset(std::move(cacheBaseOffset__arg)),
    __fbthrift_field_numBuckets(std::move(numBuckets__arg)),
    __fbthrift_field_deprecated_sizeDist(std::move(deprecated_sizeDist__arg)),
    __fbthrift_field_usedSizeBytes(std::move(usedSizeBytes__arg)),
    __fbthrift_field_validBucketCheckerState(std::move(validBucketCheckerState__arg)) { 
  __isset.set(folly::index_constant<0>(), true);
  __isset.set(folly::index_constant<1>(), true);
  __isset.set(folly::index_constant<2>(), true);
  __isset.set(folly::index_constant<3>(), true);
  __isset.set(folly::index_constant<4>(), true);
  __isset.set(folly::index_constant<5>(), true);
  __isset.set(folly::index_constant<6>(), true);
  __isset.set(folly::index_constant<7>(), true);
  __isset.set(folly::index_constant<8>(), true);
}

void BigHashPersistentData::__fbthrift_clear() {
  // clear all fields
  this->__fbthrift_field_version = ::std::int32_t();
  this->__fbthrift_field_generationTime = ::std::int64_t();
  this->__fbthrift_field_itemCount = ::std::int64_t();
  this->__fbthrift_field_bucketSize = ::std::int64_t();
  this->__fbthrift_field_cacheBaseOffset = ::std::int64_t();
  this->__fbthrift_field_numBuckets = ::std::int64_t();
  this->__fbthrift_field_deprecated_sizeDist.clear();
  this->__fbthrift_field_usedSizeBytes = ::std::int64_t();
  ::apache::thrift::clear(this->__fbthrift_field_validBucketCheckerState);
  __isset = {};
}

bool BigHashPersistentData::__fbthrift_is_empty() const {
  return false;
}

bool BigHashPersistentData::operator==([[maybe_unused]] const BigHashPersistentData& rhs) const {
  return ::apache::thrift::op::detail::StructEquality{}(*this, rhs);
}

bool BigHashPersistentData::operator<([[maybe_unused]] const BigHashPersistentData& rhs) const {
  return ::apache::thrift::op::detail::StructLessThan{}(*this, rhs);
}


::std::int32_t BigHashPersistentData::get_version() const {
  return __fbthrift_field_version;
}

::std::int32_t& BigHashPersistentData::set_version(::std::int32_t version_) {
  version_ref() = version_;
  return __fbthrift_field_version;
}

::std::int64_t BigHashPersistentData::get_generationTime() const {
  return __fbthrift_field_generationTime;
}

::std::int64_t& BigHashPersistentData::set_generationTime(::std::int64_t generationTime_) {
  generationTime_ref() = generationTime_;
  return __fbthrift_field_generationTime;
}

::std::int64_t BigHashPersistentData::get_itemCount() const {
  return __fbthrift_field_itemCount;
}

::std::int64_t& BigHashPersistentData::set_itemCount(::std::int64_t itemCount_) {
  itemCount_ref() = itemCount_;
  return __fbthrift_field_itemCount;
}

::std::int64_t BigHashPersistentData::get_bucketSize() const {
  return __fbthrift_field_bucketSize;
}

::std::int64_t& BigHashPersistentData::set_bucketSize(::std::int64_t bucketSize_) {
  bucketSize_ref() = bucketSize_;
  return __fbthrift_field_bucketSize;
}

::std::int64_t BigHashPersistentData::get_cacheBaseOffset() const {
  return __fbthrift_field_cacheBaseOffset;
}

::std::int64_t& BigHashPersistentData::set_cacheBaseOffset(::std::int64_t cacheBaseOffset_) {
  cacheBaseOffset_ref() = cacheBaseOffset_;
  return __fbthrift_field_cacheBaseOffset;
}

::std::int64_t BigHashPersistentData::get_numBuckets() const {
  return __fbthrift_field_numBuckets;
}

::std::int64_t& BigHashPersistentData::set_numBuckets(::std::int64_t numBuckets_) {
  numBuckets_ref() = numBuckets_;
  return __fbthrift_field_numBuckets;
}

const ::std::map<::std::int64_t, ::std::int64_t>& BigHashPersistentData::get_deprecated_sizeDist() const& {
  return __fbthrift_field_deprecated_sizeDist;
}

::std::map<::std::int64_t, ::std::int64_t> BigHashPersistentData::get_deprecated_sizeDist() && {
  return static_cast<::std::map<::std::int64_t, ::std::int64_t>&&>(__fbthrift_field_deprecated_sizeDist);
}

::std::int64_t BigHashPersistentData::get_usedSizeBytes() const {
  return __fbthrift_field_usedSizeBytes;
}

::std::int64_t& BigHashPersistentData::set_usedSizeBytes(::std::int64_t usedSizeBytes_) {
  usedSizeBytes_ref() = usedSizeBytes_;
  return __fbthrift_field_usedSizeBytes;
}

const ::facebook::cachelib::navy::serialization::ValidBucketCheckerState& BigHashPersistentData::get_validBucketCheckerState() const& {
  return __fbthrift_field_validBucketCheckerState;
}

::facebook::cachelib::navy::serialization::ValidBucketCheckerState BigHashPersistentData::get_validBucketCheckerState() && {
  return static_cast<::facebook::cachelib::navy::serialization::ValidBucketCheckerState&&>(__fbthrift_field_validBucketCheckerState);
}

void swap([[maybe_unused]] BigHashPersistentData& a, [[maybe_unused]] BigHashPersistentData& b) {
  using ::std::swap;
  swap(a.__fbthrift_field_version, b.__fbthrift_field_version);
  swap(a.__fbthrift_field_generationTime, b.__fbthrift_field_generationTime);
  swap(a.__fbthrift_field_itemCount, b.__fbthrift_field_itemCount);
  swap(a.__fbthrift_field_bucketSize, b.__fbthrift_field_bucketSize);
  swap(a.__fbthrift_field_cacheBaseOffset, b.__fbthrift_field_cacheBaseOffset);
  swap(a.__fbthrift_field_numBuckets, b.__fbthrift_field_numBuckets);
  swap(a.__fbthrift_field_deprecated_sizeDist, b.__fbthrift_field_deprecated_sizeDist);
  swap(a.__fbthrift_field_usedSizeBytes, b.__fbthrift_field_usedSizeBytes);
  swap(a.__fbthrift_field_validBucketCheckerState, b.__fbthrift_field_validBucketCheckerState);
  swap(a.__isset, b.__isset);
}

static_assert(
    ::apache::thrift::detail::st::gen_check_json<
        BigHashPersistentData,
        ::apache::thrift::type_class::structure,
        ::facebook::cachelib::navy::serialization::ValidBucketCheckerState>,
    "inconsistent use of json option");

} // namespace facebook::cachelib::navy::serialization


namespace facebook::cachelib::navy::serialization {

std::string_view FixedSizeIndexConfig::__fbthrift_get_field_name(::apache::thrift::FieldOrdinal ord) {
  if (ord == ::apache::thrift::FieldOrdinal{0}) { return {}; }
  return apache::thrift::TStructDataStorage<FixedSizeIndexConfig>::fields_names[folly::to_underlying(ord) - 1];
}
std::string_view FixedSizeIndexConfig::__fbthrift_get_class_name() {
  return apache::thrift::TStructDataStorage<FixedSizeIndexConfig>::name;
}

FixedSizeIndexConfig::FixedSizeIndexConfig(const FixedSizeIndexConfig&) = default;
FixedSizeIndexConfig& FixedSizeIndexConfig::operator=(const FixedSizeIndexConfig&) = default;
FixedSizeIndexConfig::FixedSizeIndexConfig([[maybe_unused]] FixedSizeIndexConfig&& other) noexcept :
    __fbthrift_field_version(std::move(other.__fbthrift_field_version)),
    __fbthrift_field_numChunks(std::move(other.__fbthrift_field_numChunks)),
    __fbthrift_field_numBucketsPerChunkPower(std::move(other.__fbthrift_field_numBucketsPerChunkPower)),
    __fbthrift_field_numBucketsPerShard(std::move(other.__fbthrift_field_numBucketsPerShard)),
    __isset(other.__isset) {
}

FixedSizeIndexConfig& FixedSizeIndexConfig::operator=([[maybe_unused]] FixedSizeIndexConfig&& other) noexcept {
    this->__fbthrift_field_version = std::move(other.__fbthrift_field_version);
    this->__fbthrift_field_numChunks = std::move(other.__fbthrift_field_numChunks);
    this->__fbthrift_field_numBucketsPerChunkPower = std::move(other.__fbthrift_field_numBucketsPerChunkPower);
    this->__fbthrift_field_numBucketsPerShard = std::move(other.__fbthrift_field_numBucketsPerShard);
    __isset = other.__isset;
    return *this;
}


FixedSizeIndexConfig::FixedSizeIndexConfig(apache::thrift::FragileConstructor, ::std::int32_t version__arg, ::std::int32_t numChunks__arg, ::std::int8_t numBucketsPerChunkPower__arg, ::std::int64_t numBucketsPerShard__arg) :
    __fbthrift_field_version(std::move(version__arg)),
    __fbthrift_field_numChunks(std::move(numChunks__arg)),
    __fbthrift_field_numBucketsPerChunkPower(std::move(numBucketsPerChunkPower__arg)),
    __fbthrift_field_numBucketsPerShard(std::move(numBucketsPerShard__arg)) { 
  __isset.set(folly::index_constant<0>(), true);
  __isset.set(folly::index_constant<1>(), true);
  __isset.set(folly::index_constant<2>(), true);
  __isset.set(folly::index_constant<3>(), true);
}

void FixedSizeIndexConfig::__fbthrift_clear() {
  // clear all fields
  this->__fbthrift_field_version = ::std::int32_t();
  this->__fbthrift_field_numChunks = ::std::int32_t();
  this->__fbthrift_field_numBucketsPerChunkPower = ::std::int8_t();
  this->__fbthrift_field_numBucketsPerShard = ::std::int64_t();
  __isset = {};
}

bool FixedSizeIndexConfig::__fbthrift_is_empty() const {
  return false;
}

bool FixedSizeIndexConfig::operator==([[maybe_unused]] const FixedSizeIndexConfig& rhs) const {
  return ::apache::thrift::op::detail::StructEquality{}(*this, rhs);
}

bool FixedSizeIndexConfig::operator<([[maybe_unused]] const FixedSizeIndexConfig& rhs) const {
  return ::apache::thrift::op::detail::StructLessThan{}(*this, rhs);
}


::std::int32_t FixedSizeIndexConfig::get_version() const {
  return __fbthrift_field_version;
}

::std::int32_t& FixedSizeIndexConfig::set_version(::std::int32_t version_) {
  version_ref() = version_;
  return __fbthrift_field_version;
}

::std::int32_t FixedSizeIndexConfig::get_numChunks() const {
  return __fbthrift_field_numChunks;
}

::std::int32_t& FixedSizeIndexConfig::set_numChunks(::std::int32_t numChunks_) {
  numChunks_ref() = numChunks_;
  return __fbthrift_field_numChunks;
}

::std::int8_t FixedSizeIndexConfig::get_numBucketsPerChunkPower() const {
  return __fbthrift_field_numBucketsPerChunkPower;
}

::std::int8_t& FixedSizeIndexConfig::set_numBucketsPerChunkPower(::std::int8_t numBucketsPerChunkPower_) {
  numBucketsPerChunkPower_ref() = numBucketsPerChunkPower_;
  return __fbthrift_field_numBucketsPerChunkPower;
}

::std::int64_t FixedSizeIndexConfig::get_numBucketsPerShard() const {
  return __fbthrift_field_numBucketsPerShard;
}

::std::int64_t& FixedSizeIndexConfig::set_numBucketsPerShard(::std::int64_t numBucketsPerShard_) {
  numBucketsPerShard_ref() = numBucketsPerShard_;
  return __fbthrift_field_numBucketsPerShard;
}

void swap([[maybe_unused]] FixedSizeIndexConfig& a, [[maybe_unused]] FixedSizeIndexConfig& b) {
  using ::std::swap;
  swap(a.__fbthrift_field_version, b.__fbthrift_field_version);
  swap(a.__fbthrift_field_numChunks, b.__fbthrift_field_numChunks);
  swap(a.__fbthrift_field_numBucketsPerChunkPower, b.__fbthrift_field_numBucketsPerChunkPower);
  swap(a.__fbthrift_field_numBucketsPerShard, b.__fbthrift_field_numBucketsPerShard);
  swap(a.__isset, b.__isset);
}


} // namespace facebook::cachelib::navy::serialization

namespace facebook::cachelib::navy::serialization { namespace {
[[maybe_unused]] FOLLY_ERASE void validateAdapters() {
}
}} // namespace facebook::cachelib::navy::serialization
namespace apache::thrift::detail::annotation {
}
