/**
 * Autogenerated by Thrift for cachelib/navy/serialization/objects.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated @nocommit
 */
#pragma once

// BEGIN forward_declare
namespace facebook::cachelib::navy::serialization {
class IndexEntry;
class IndexBucket;
class Region;
class RegionData;
class FifoPolicyNodeData;
class FifoPolicyData;
class AccessStats;
class AccessStatsPair;
class AccessTracker;
class BlockCacheConfig;
class ValidBucketCheckerState;
class BigHashPersistentData;
class FixedSizeIndexConfig;
} // namespace facebook::cachelib::navy::serialization
// END forward_declare
