/**
 * Autogenerated by Thrift for cachelib/navy/serialization/objects.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated @nocommit
 */
#pragma once

#include <thrift/lib/cpp2/gen/module_constants_h.h>

#include "cachelib/navy/serialization/gen-cpp2/objects_types.h"

namespace facebook::cachelib::navy::serialization {
/** Glean {"file": "cachelib/navy/serialization/objects.thrift"} */
namespace objects_constants {

  FOLLY_EXPORT ::std::string_view _fbthrift_schema_e76116d4fff65aaa();
  FOLLY_EXPORT ::folly::Range<const ::std::string_view*> _fbthrift_schema_e76116d4fff65aaa_includes();
  FOLLY_EXPORT ::folly::Range<const ::std::string_view*> _fbthrift_schema_e76116d4fff65aaa_uris();

} // namespace objects_constants
} // namespace facebook::cachelib::navy::serialization
