/**
 * Autogenerated by Thrift for cachelib/allocator/datastruct/serialize/objects.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated @nocommit
 */

#include "cachelib/allocator/datastruct/serialize/gen-cpp2/objects_constants.h"

#include <thrift/lib/cpp2/gen/module_constants_cpp.h>


namespace facebook::cachelib::serialization {
namespace objects_constants {


::std::string_view _fbthrift_schema_87d3d4b5ca64ce2b() {
  return "";
}
::folly::Range<const ::std::string_view*> _fbthrift_schema_87d3d4b5ca64ce2b_includes() {
  return {};
}
::folly::Range<const ::std::string_view*> _fbthrift_schema_87d3d4b5ca64ce2b_uris() {
  return {};
}

} // namespace objects_constants
} // namespace facebook::cachelib::serialization
