/**
 * Autogenerated by Thrift for cachelib/allocator/datastruct/serialize/objects.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated @nocommit
 */

#pragma once

#include <thrift/lib/cpp2/gen/module_types_h.h>

namespace apache::thrift {
namespace ident {
struct size;
struct compressedHead;
struct compressedTail;
struct compressedHead;
struct compressedTail;
struct size;
struct lists;
} // namespace ident
namespace detail {
#ifndef APACHE_THRIFT_ACCESSOR_size
#define APACHE_THRIFT_ACCESSOR_size
APACHE_THRIFT_DEFINE_ACCESSOR(size);
#endif
#ifndef APACHE_THRIFT_ACCESSOR_compressedHead
#define APACHE_THRIFT_ACCESSOR_compressedHead
APACHE_THRIFT_DEFINE_ACCESSOR(compressedHead);
#endif
#ifndef APACHE_THRIFT_ACCESSOR_compressedTail
#define APACHE_THRIFT_ACCESSOR_compressedTail
APACHE_THRIFT_DEFINE_ACCESSOR(compressedTail);
#endif
#ifndef APACHE_THRIFT_ACCESSOR_compressedHead
#define APACHE_THRIFT_ACCESSOR_compressedHead
APACHE_THRIFT_DEFINE_ACCESSOR(compressedHead);
#endif
#ifndef APACHE_THRIFT_ACCESSOR_compressedTail
#define APACHE_THRIFT_ACCESSOR_compressedTail
APACHE_THRIFT_DEFINE_ACCESSOR(compressedTail);
#endif
#ifndef APACHE_THRIFT_ACCESSOR_size
#define APACHE_THRIFT_ACCESSOR_size
APACHE_THRIFT_DEFINE_ACCESSOR(size);
#endif
#ifndef APACHE_THRIFT_ACCESSOR_lists
#define APACHE_THRIFT_ACCESSOR_lists
APACHE_THRIFT_DEFINE_ACCESSOR(lists);
#endif
} // namespace detail
} // namespace apache::thrift

// BEGIN declare_enums
// END declare_enums
// BEGIN forward_declare
namespace facebook::cachelib::serialization {
class SListObject;
class DListObject;
class MultiDListObject;
} // namespace facebook::cachelib::serialization
// END forward_declare
namespace apache::thrift::detail::annotation {
} // namespace apache::thrift::detail::annotation

namespace apache::thrift::detail::qualifier {
} // namespace apache::thrift::detail::qualifier

// BEGIN hash_and_equal_to
// END hash_and_equal_to
namespace facebook::cachelib::serialization {
using ::apache::thrift::detail::operator!=;
using ::apache::thrift::detail::operator>;
using ::apache::thrift::detail::operator<=;
using ::apache::thrift::detail::operator>=;


/** Glean {"file": "cachelib/allocator/datastruct/serialize/objects.thrift", "name": "SListObject", "kind": "struct" } */
class SListObject final  {
 private:
  friend struct ::apache::thrift::detail::st::struct_private_access;
  template<class> friend struct ::apache::thrift::detail::invoke_reffer;

  //  used by a static_assert in the corresponding source
  static constexpr bool __fbthrift_cpp2_gen_json = false;
  static constexpr bool __fbthrift_cpp2_is_runtime_annotation = false;
  static std::string_view __fbthrift_get_field_name(::apache::thrift::FieldOrdinal ord);
  static std::string_view __fbthrift_get_class_name();
  template <class ...>
  FOLLY_ERASE static constexpr std::string_view __fbthrift_get_module_name() noexcept {
    return "objects";
  }
  static constexpr std::size_t __fbthrift_num_fields = 3;

  static constexpr const int16_t __fbthrift_reflection_field_ids[] = {0,2,3,4};

  using __fbthrift_reflection_idents = folly::tag_t<
    ::apache::thrift::ident::size,
    ::apache::thrift::ident::compressedHead,
    ::apache::thrift::ident::compressedTail
  >;

  using __fbthrift_reflection_type_tags = folly::tag_t<
    ::apache::thrift::type::i64_t,
    ::apache::thrift::type::i64_t,
    ::apache::thrift::type::i64_t
  >;
  void __fbthrift_clear();
  bool __fbthrift_is_empty() const;

 public:
  using __fbthrift_cpp2_type = SListObject;
  static constexpr bool __fbthrift_cpp2_is_union =
    false;


 public:

  SListObject() :
      __fbthrift_field_size(),
      __fbthrift_field_compressedHead(),
      __fbthrift_field_compressedTail(static_cast<::std::int64_t>(-1)) {
  }
  // FragileConstructor for use in initialization lists only.
  [[deprecated("This constructor is deprecated")]]
  SListObject(apache::thrift::FragileConstructor, ::std::int64_t size__arg, ::std::int64_t compressedHead__arg, ::std::int64_t compressedTail__arg);

  SListObject(SListObject&&) = default;
  SListObject(const SListObject&) = default;


  SListObject& operator=(SListObject&&) = default;
  SListObject& operator=(const SListObject&) = default;
 private:
  ::std::int64_t __fbthrift_field_size;
 private:
  ::std::int64_t __fbthrift_field_compressedHead;
 private:
  ::std::int64_t __fbthrift_field_compressedTail;
 private:
  apache::thrift::detail::isset_bitset<1, apache::thrift::detail::IssetBitsetOption::Unpacked> __isset;

 public:

  bool operator==(const SListObject&) const;
  bool operator<(const SListObject&) const;

  /** Glean { "field": "size" } */
  template <typename..., typename fbthrift_T = ::std::int64_t>
  FOLLY_ERASE ::apache::thrift::required_field_ref<const fbthrift_T&> size_ref() const& {
    return ::apache::thrift::required_field_ref<const fbthrift_T&>{this->__fbthrift_field_size};
  }

  /** Glean { "field": "size" } */
  template <typename..., typename fbthrift_T = ::std::int64_t>
  FOLLY_ERASE ::apache::thrift::required_field_ref<fbthrift_T&> size_ref() & {
    return ::apache::thrift::required_field_ref<fbthrift_T&>{this->__fbthrift_field_size};
  }

  /** Glean { "field": "size" } */
  template <typename..., typename fbthrift_T = ::std::int64_t>
  FOLLY_ERASE ::apache::thrift::required_field_ref<fbthrift_T&&> size_ref() && {
    return ::apache::thrift::required_field_ref<fbthrift_T&&>{static_cast<fbthrift_T&&>(this->__fbthrift_field_size)};
  }

  /** Glean { "field": "size" } */
  template <typename..., typename fbthrift_T = ::std::int64_t>
  FOLLY_ERASE ::apache::thrift::required_field_ref<const fbthrift_T&> size() const& {
    return ::apache::thrift::required_field_ref<const fbthrift_T&>{this->__fbthrift_field_size};
  }

  /** Glean { "field": "size" } */
  template <typename..., typename fbthrift_T = ::std::int64_t>
  FOLLY_ERASE ::apache::thrift::required_field_ref<fbthrift_T&> size() & {
    return ::apache::thrift::required_field_ref<fbthrift_T&>{this->__fbthrift_field_size};
  }

  /** Glean { "field": "size" } */
  template <typename..., typename fbthrift_T = ::std::int64_t>
  FOLLY_ERASE ::apache::thrift::required_field_ref<fbthrift_T&&> size() && {
    return ::apache::thrift::required_field_ref<fbthrift_T&&>{static_cast<fbthrift_T&&>(this->__fbthrift_field_size)};
  }

  /** Glean { "field": "compressedHead" } */
  template <typename..., typename fbthrift_T = ::std::int64_t>
  FOLLY_ERASE ::apache::thrift::required_field_ref<const fbthrift_T&> compressedHead_ref() const& {
    return ::apache::thrift::required_field_ref<const fbthrift_T&>{this->__fbthrift_field_compressedHead};
  }

  /** Glean { "field": "compressedHead" } */
  template <typename..., typename fbthrift_T = ::std::int64_t>
  FOLLY_ERASE ::apache::thrift::required_field_ref<fbthrift_T&> compressedHead_ref() & {
    return ::apache::thrift::required_field_ref<fbthrift_T&>{this->__fbthrift_field_compressedHead};
  }

  /** Glean { "field": "compressedHead" } */
  template <typename..., typename fbthrift_T = ::std::int64_t>
  FOLLY_ERASE ::apache::thrift::required_field_ref<fbthrift_T&&> compressedHead_ref() && {
    return ::apache::thrift::required_field_ref<fbthrift_T&&>{static_cast<fbthrift_T&&>(this->__fbthrift_field_compressedHead)};
  }

  /** Glean { "field": "compressedHead" } */
  template <typename..., typename fbthrift_T = ::std::int64_t>
  FOLLY_ERASE ::apache::thrift::required_field_ref<const fbthrift_T&> compressedHead() const& {
    return ::apache::thrift::required_field_ref<const fbthrift_T&>{this->__fbthrift_field_compressedHead};
  }

  /** Glean { "field": "compressedHead" } */
  template <typename..., typename fbthrift_T = ::std::int64_t>
  FOLLY_ERASE ::apache::thrift::required_field_ref<fbthrift_T&> compressedHead() & {
    return ::apache::thrift::required_field_ref<fbthrift_T&>{this->__fbthrift_field_compressedHead};
  }

  /** Glean { "field": "compressedHead" } */
  template <typename..., typename fbthrift_T = ::std::int64_t>
  FOLLY_ERASE ::apache::thrift::required_field_ref<fbthrift_T&&> compressedHead() && {
    return ::apache::thrift::required_field_ref<fbthrift_T&&>{static_cast<fbthrift_T&&>(this->__fbthrift_field_compressedHead)};
  }

  /** Glean { "field": "compressedTail" } */
  template <typename..., typename fbthrift_T = ::std::int64_t>
  FOLLY_ERASE ::apache::thrift::field_ref<const fbthrift_T&> compressedTail_ref() const& {
    return {this->__fbthrift_field_compressedTail, __isset.at(0), __isset.bit(0)};
  }

  /** Glean { "field": "compressedTail" } */
  template <typename..., typename fbthrift_T = ::std::int64_t>
  FOLLY_ERASE ::apache::thrift::field_ref<fbthrift_T&> compressedTail_ref() & {
    return {this->__fbthrift_field_compressedTail, __isset.at(0), __isset.bit(0)};
  }

  /** Glean { "field": "compressedTail" } */
  template <typename..., typename fbthrift_T = ::std::int64_t>
  FOLLY_ERASE ::apache::thrift::field_ref<fbthrift_T&&> compressedTail_ref() && {
    return {static_cast<fbthrift_T&&>(this->__fbthrift_field_compressedTail), __isset.at(0), __isset.bit(0)};
  }

  /** Glean { "field": "compressedTail" } */
  template <typename..., typename fbthrift_T = ::std::int64_t>
  FOLLY_ERASE ::apache::thrift::field_ref<const fbthrift_T&> compressedTail() const& {
    return {this->__fbthrift_field_compressedTail, __isset.at(0), __isset.bit(0)};
  }

  /** Glean { "field": "compressedTail" } */
  template <typename..., typename fbthrift_T = ::std::int64_t>
  FOLLY_ERASE ::apache::thrift::field_ref<fbthrift_T&> compressedTail() & {
    return {this->__fbthrift_field_compressedTail, __isset.at(0), __isset.bit(0)};
  }

  /** Glean { "field": "compressedTail" } */
  template <typename..., typename fbthrift_T = ::std::int64_t>
  FOLLY_ERASE ::apache::thrift::field_ref<fbthrift_T&&> compressedTail() && {
    return {static_cast<fbthrift_T&&>(this->__fbthrift_field_compressedTail), __isset.at(0), __isset.bit(0)};
  }

  /** Glean { "field": "size" } */
  [[deprecated("Use `FOO.size().value()` instead of `FOO.get_size()`")]]
  ::std::int64_t get_size() const;

  /** Glean { "field": "size" } */
  [[deprecated("Use `FOO.size() = BAR` instead of `FOO.set_size(BAR)`")]]
  ::std::int64_t& set_size(::std::int64_t size_);

  /** Glean { "field": "compressedHead" } */
  [[deprecated("Use `FOO.compressedHead().value()` instead of `FOO.get_compressedHead()`")]]
  ::std::int64_t get_compressedHead() const;

  /** Glean { "field": "compressedHead" } */
  [[deprecated("Use `FOO.compressedHead() = BAR` instead of `FOO.set_compressedHead(BAR)`")]]
  ::std::int64_t& set_compressedHead(::std::int64_t compressedHead_);

  /** Glean { "field": "compressedTail" } */
  [[deprecated("Use `FOO.compressedTail().value()` instead of `FOO.get_compressedTail()`")]]
  ::std::int64_t get_compressedTail() const;

  /** Glean { "field": "compressedTail" } */
  [[deprecated("Use `FOO.compressedTail() = BAR` instead of `FOO.set_compressedTail(BAR)`")]]
  ::std::int64_t& set_compressedTail(::std::int64_t compressedTail_);

  template <class Protocol_>
  unsigned long read(Protocol_* iprot);
  template <class Protocol_>
  uint32_t serializedSize(Protocol_ const* prot_) const;
  template <class Protocol_>
  uint32_t serializedSizeZC(Protocol_ const* prot_) const;
  template <class Protocol_>
  uint32_t write(Protocol_* prot_) const;

 private:
  template <class Protocol_>
  void readNoXfer(Protocol_* iprot);

  friend class ::apache::thrift::Cpp2Ops<SListObject>;
  friend void swap(SListObject& a, SListObject& b);
};

template <class Protocol_>
unsigned long SListObject::read(Protocol_* iprot) {
  auto _xferStart = iprot->getCursorPosition();
  readNoXfer(iprot);
  return iprot->getCursorPosition() - _xferStart;
}


/** Glean {"file": "cachelib/allocator/datastruct/serialize/objects.thrift", "name": "DListObject", "kind": "struct" } */
class DListObject final  {
 private:
  friend struct ::apache::thrift::detail::st::struct_private_access;
  template<class> friend struct ::apache::thrift::detail::invoke_reffer;

  //  used by a static_assert in the corresponding source
  static constexpr bool __fbthrift_cpp2_gen_json = false;
  static constexpr bool __fbthrift_cpp2_is_runtime_annotation = false;
  static std::string_view __fbthrift_get_field_name(::apache::thrift::FieldOrdinal ord);
  static std::string_view __fbthrift_get_class_name();
  template <class ...>
  FOLLY_ERASE static constexpr std::string_view __fbthrift_get_module_name() noexcept {
    return "objects";
  }
  static constexpr std::size_t __fbthrift_num_fields = 3;

  static constexpr const int16_t __fbthrift_reflection_field_ids[] = {0,1,2,3};

  using __fbthrift_reflection_idents = folly::tag_t<
    ::apache::thrift::ident::compressedHead,
    ::apache::thrift::ident::compressedTail,
    ::apache::thrift::ident::size
  >;

  using __fbthrift_reflection_type_tags = folly::tag_t<
    ::apache::thrift::type::i64_t,
    ::apache::thrift::type::i64_t,
    ::apache::thrift::type::i64_t
  >;
  void __fbthrift_clear();
  bool __fbthrift_is_empty() const;

 public:
  using __fbthrift_cpp2_type = DListObject;
  static constexpr bool __fbthrift_cpp2_is_union =
    false;


 public:

  DListObject() :
      __fbthrift_field_compressedHead(),
      __fbthrift_field_compressedTail(),
      __fbthrift_field_size() {
  }
  // FragileConstructor for use in initialization lists only.
  [[deprecated("This constructor is deprecated")]]
  DListObject(apache::thrift::FragileConstructor, ::std::int64_t compressedHead__arg, ::std::int64_t compressedTail__arg, ::std::int64_t size__arg);

  DListObject(DListObject&&) = default;
  DListObject(const DListObject&) = default;


  DListObject& operator=(DListObject&&) = default;
  DListObject& operator=(const DListObject&) = default;
 private:
  ::std::int64_t __fbthrift_field_compressedHead;
 private:
  ::std::int64_t __fbthrift_field_compressedTail;
 private:
  ::std::int64_t __fbthrift_field_size;

 public:

  bool operator==(const DListObject&) const;
  bool operator<(const DListObject&) const;

  /** Glean { "field": "compressedHead" } */
  template <typename..., typename fbthrift_T = ::std::int64_t>
  FOLLY_ERASE ::apache::thrift::required_field_ref<const fbthrift_T&> compressedHead_ref() const& {
    return ::apache::thrift::required_field_ref<const fbthrift_T&>{this->__fbthrift_field_compressedHead};
  }

  /** Glean { "field": "compressedHead" } */
  template <typename..., typename fbthrift_T = ::std::int64_t>
  FOLLY_ERASE ::apache::thrift::required_field_ref<fbthrift_T&> compressedHead_ref() & {
    return ::apache::thrift::required_field_ref<fbthrift_T&>{this->__fbthrift_field_compressedHead};
  }

  /** Glean { "field": "compressedHead" } */
  template <typename..., typename fbthrift_T = ::std::int64_t>
  FOLLY_ERASE ::apache::thrift::required_field_ref<fbthrift_T&&> compressedHead_ref() && {
    return ::apache::thrift::required_field_ref<fbthrift_T&&>{static_cast<fbthrift_T&&>(this->__fbthrift_field_compressedHead)};
  }

  /** Glean { "field": "compressedHead" } */
  template <typename..., typename fbthrift_T = ::std::int64_t>
  FOLLY_ERASE ::apache::thrift::required_field_ref<const fbthrift_T&> compressedHead() const& {
    return ::apache::thrift::required_field_ref<const fbthrift_T&>{this->__fbthrift_field_compressedHead};
  }

  /** Glean { "field": "compressedHead" } */
  template <typename..., typename fbthrift_T = ::std::int64_t>
  FOLLY_ERASE ::apache::thrift::required_field_ref<fbthrift_T&> compressedHead() & {
    return ::apache::thrift::required_field_ref<fbthrift_T&>{this->__fbthrift_field_compressedHead};
  }

  /** Glean { "field": "compressedHead" } */
  template <typename..., typename fbthrift_T = ::std::int64_t>
  FOLLY_ERASE ::apache::thrift::required_field_ref<fbthrift_T&&> compressedHead() && {
    return ::apache::thrift::required_field_ref<fbthrift_T&&>{static_cast<fbthrift_T&&>(this->__fbthrift_field_compressedHead)};
  }

  /** Glean { "field": "compressedTail" } */
  template <typename..., typename fbthrift_T = ::std::int64_t>
  FOLLY_ERASE ::apache::thrift::required_field_ref<const fbthrift_T&> compressedTail_ref() const& {
    return ::apache::thrift::required_field_ref<const fbthrift_T&>{this->__fbthrift_field_compressedTail};
  }

  /** Glean { "field": "compressedTail" } */
  template <typename..., typename fbthrift_T = ::std::int64_t>
  FOLLY_ERASE ::apache::thrift::required_field_ref<fbthrift_T&> compressedTail_ref() & {
    return ::apache::thrift::required_field_ref<fbthrift_T&>{this->__fbthrift_field_compressedTail};
  }

  /** Glean { "field": "compressedTail" } */
  template <typename..., typename fbthrift_T = ::std::int64_t>
  FOLLY_ERASE ::apache::thrift::required_field_ref<fbthrift_T&&> compressedTail_ref() && {
    return ::apache::thrift::required_field_ref<fbthrift_T&&>{static_cast<fbthrift_T&&>(this->__fbthrift_field_compressedTail)};
  }

  /** Glean { "field": "compressedTail" } */
  template <typename..., typename fbthrift_T = ::std::int64_t>
  FOLLY_ERASE ::apache::thrift::required_field_ref<const fbthrift_T&> compressedTail() const& {
    return ::apache::thrift::required_field_ref<const fbthrift_T&>{this->__fbthrift_field_compressedTail};
  }

  /** Glean { "field": "compressedTail" } */
  template <typename..., typename fbthrift_T = ::std::int64_t>
  FOLLY_ERASE ::apache::thrift::required_field_ref<fbthrift_T&> compressedTail() & {
    return ::apache::thrift::required_field_ref<fbthrift_T&>{this->__fbthrift_field_compressedTail};
  }

  /** Glean { "field": "compressedTail" } */
  template <typename..., typename fbthrift_T = ::std::int64_t>
  FOLLY_ERASE ::apache::thrift::required_field_ref<fbthrift_T&&> compressedTail() && {
    return ::apache::thrift::required_field_ref<fbthrift_T&&>{static_cast<fbthrift_T&&>(this->__fbthrift_field_compressedTail)};
  }

  /** Glean { "field": "size" } */
  template <typename..., typename fbthrift_T = ::std::int64_t>
  FOLLY_ERASE ::apache::thrift::required_field_ref<const fbthrift_T&> size_ref() const& {
    return ::apache::thrift::required_field_ref<const fbthrift_T&>{this->__fbthrift_field_size};
  }

  /** Glean { "field": "size" } */
  template <typename..., typename fbthrift_T = ::std::int64_t>
  FOLLY_ERASE ::apache::thrift::required_field_ref<fbthrift_T&> size_ref() & {
    return ::apache::thrift::required_field_ref<fbthrift_T&>{this->__fbthrift_field_size};
  }

  /** Glean { "field": "size" } */
  template <typename..., typename fbthrift_T = ::std::int64_t>
  FOLLY_ERASE ::apache::thrift::required_field_ref<fbthrift_T&&> size_ref() && {
    return ::apache::thrift::required_field_ref<fbthrift_T&&>{static_cast<fbthrift_T&&>(this->__fbthrift_field_size)};
  }

  /** Glean { "field": "size" } */
  template <typename..., typename fbthrift_T = ::std::int64_t>
  FOLLY_ERASE ::apache::thrift::required_field_ref<const fbthrift_T&> size() const& {
    return ::apache::thrift::required_field_ref<const fbthrift_T&>{this->__fbthrift_field_size};
  }

  /** Glean { "field": "size" } */
  template <typename..., typename fbthrift_T = ::std::int64_t>
  FOLLY_ERASE ::apache::thrift::required_field_ref<fbthrift_T&> size() & {
    return ::apache::thrift::required_field_ref<fbthrift_T&>{this->__fbthrift_field_size};
  }

  /** Glean { "field": "size" } */
  template <typename..., typename fbthrift_T = ::std::int64_t>
  FOLLY_ERASE ::apache::thrift::required_field_ref<fbthrift_T&&> size() && {
    return ::apache::thrift::required_field_ref<fbthrift_T&&>{static_cast<fbthrift_T&&>(this->__fbthrift_field_size)};
  }

  /** Glean { "field": "compressedHead" } */
  [[deprecated("Use `FOO.compressedHead().value()` instead of `FOO.get_compressedHead()`")]]
  ::std::int64_t get_compressedHead() const;

  /** Glean { "field": "compressedHead" } */
  [[deprecated("Use `FOO.compressedHead() = BAR` instead of `FOO.set_compressedHead(BAR)`")]]
  ::std::int64_t& set_compressedHead(::std::int64_t compressedHead_);

  /** Glean { "field": "compressedTail" } */
  [[deprecated("Use `FOO.compressedTail().value()` instead of `FOO.get_compressedTail()`")]]
  ::std::int64_t get_compressedTail() const;

  /** Glean { "field": "compressedTail" } */
  [[deprecated("Use `FOO.compressedTail() = BAR` instead of `FOO.set_compressedTail(BAR)`")]]
  ::std::int64_t& set_compressedTail(::std::int64_t compressedTail_);

  /** Glean { "field": "size" } */
  [[deprecated("Use `FOO.size().value()` instead of `FOO.get_size()`")]]
  ::std::int64_t get_size() const;

  /** Glean { "field": "size" } */
  [[deprecated("Use `FOO.size() = BAR` instead of `FOO.set_size(BAR)`")]]
  ::std::int64_t& set_size(::std::int64_t size_);

  template <class Protocol_>
  unsigned long read(Protocol_* iprot);
  template <class Protocol_>
  uint32_t serializedSize(Protocol_ const* prot_) const;
  template <class Protocol_>
  uint32_t serializedSizeZC(Protocol_ const* prot_) const;
  template <class Protocol_>
  uint32_t write(Protocol_* prot_) const;

 private:
  template <class Protocol_>
  void readNoXfer(Protocol_* iprot);

  friend class ::apache::thrift::Cpp2Ops<DListObject>;
  friend void swap(DListObject& a, DListObject& b);
};

template <class Protocol_>
unsigned long DListObject::read(Protocol_* iprot) {
  auto _xferStart = iprot->getCursorPosition();
  readNoXfer(iprot);
  return iprot->getCursorPosition() - _xferStart;
}


/** Glean {"file": "cachelib/allocator/datastruct/serialize/objects.thrift", "name": "MultiDListObject", "kind": "struct" } */
class MultiDListObject final  {
 private:
  friend struct ::apache::thrift::detail::st::struct_private_access;
  template<class> friend struct ::apache::thrift::detail::invoke_reffer;

  //  used by a static_assert in the corresponding source
  static constexpr bool __fbthrift_cpp2_gen_json = false;
  static constexpr bool __fbthrift_cpp2_is_runtime_annotation = false;
  static std::string_view __fbthrift_get_field_name(::apache::thrift::FieldOrdinal ord);
  static std::string_view __fbthrift_get_class_name();
  template <class ...>
  FOLLY_ERASE static constexpr std::string_view __fbthrift_get_module_name() noexcept {
    return "objects";
  }
  static constexpr std::size_t __fbthrift_num_fields = 1;

  static constexpr const int16_t __fbthrift_reflection_field_ids[] = {0,1};

  using __fbthrift_reflection_idents = folly::tag_t<
    ::apache::thrift::ident::lists
  >;

  using __fbthrift_reflection_type_tags = folly::tag_t<
    ::apache::thrift::type::list<::apache::thrift::type::struct_t<::facebook::cachelib::serialization::DListObject>>
  >;
  void __fbthrift_clear();
  bool __fbthrift_is_empty() const;

 public:
  using __fbthrift_cpp2_type = MultiDListObject;
  static constexpr bool __fbthrift_cpp2_is_union =
    false;


 public:

  MultiDListObject();

  // FragileConstructor for use in initialization lists only.
  [[deprecated("This constructor is deprecated")]]
  MultiDListObject(apache::thrift::FragileConstructor, ::std::vector<::facebook::cachelib::serialization::DListObject> lists__arg);

  MultiDListObject(MultiDListObject&&) noexcept;
  MultiDListObject(const MultiDListObject& src);


  MultiDListObject& operator=(MultiDListObject&&) noexcept;
  MultiDListObject& operator=(const MultiDListObject&);

  ~MultiDListObject();

 private:
  ::std::vector<::facebook::cachelib::serialization::DListObject> __fbthrift_field_lists;

 public:

  bool operator==(const MultiDListObject&) const;
  bool operator<(const MultiDListObject&) const;

  /** Glean { "field": "lists" } */
  template <typename..., typename fbthrift_T = ::std::vector<::facebook::cachelib::serialization::DListObject>>
  FOLLY_ERASE ::apache::thrift::required_field_ref<const fbthrift_T&> lists_ref() const& {
    return ::apache::thrift::required_field_ref<const fbthrift_T&>{this->__fbthrift_field_lists};
  }

  /** Glean { "field": "lists" } */
  template <typename..., typename fbthrift_T = ::std::vector<::facebook::cachelib::serialization::DListObject>>
  FOLLY_ERASE ::apache::thrift::required_field_ref<fbthrift_T&> lists_ref() & {
    return ::apache::thrift::required_field_ref<fbthrift_T&>{this->__fbthrift_field_lists};
  }

  /** Glean { "field": "lists" } */
  template <typename..., typename fbthrift_T = ::std::vector<::facebook::cachelib::serialization::DListObject>>
  FOLLY_ERASE ::apache::thrift::required_field_ref<fbthrift_T&&> lists_ref() && {
    return ::apache::thrift::required_field_ref<fbthrift_T&&>{static_cast<fbthrift_T&&>(this->__fbthrift_field_lists)};
  }

  /** Glean { "field": "lists" } */
  template <typename..., typename fbthrift_T = ::std::vector<::facebook::cachelib::serialization::DListObject>>
  FOLLY_ERASE ::apache::thrift::required_field_ref<const fbthrift_T&> lists() const& {
    return ::apache::thrift::required_field_ref<const fbthrift_T&>{this->__fbthrift_field_lists};
  }

  /** Glean { "field": "lists" } */
  template <typename..., typename fbthrift_T = ::std::vector<::facebook::cachelib::serialization::DListObject>>
  FOLLY_ERASE ::apache::thrift::required_field_ref<fbthrift_T&> lists() & {
    return ::apache::thrift::required_field_ref<fbthrift_T&>{this->__fbthrift_field_lists};
  }

  /** Glean { "field": "lists" } */
  template <typename..., typename fbthrift_T = ::std::vector<::facebook::cachelib::serialization::DListObject>>
  FOLLY_ERASE ::apache::thrift::required_field_ref<fbthrift_T&&> lists() && {
    return ::apache::thrift::required_field_ref<fbthrift_T&&>{static_cast<fbthrift_T&&>(this->__fbthrift_field_lists)};
  }

  /** Glean { "field": "lists" } */
  [[deprecated("Use `FOO.lists().value()` instead of `FOO.get_lists()`")]]
  const ::std::vector<::facebook::cachelib::serialization::DListObject>& get_lists() const&;

  /** Glean { "field": "lists" } */
  [[deprecated("Use `FOO.lists().value()` instead of `FOO.get_lists()`")]]
  ::std::vector<::facebook::cachelib::serialization::DListObject> get_lists() &&;

  /** Glean { "field": "lists" } */
  template <typename T_MultiDListObject_lists_struct_setter = ::std::vector<::facebook::cachelib::serialization::DListObject>>
  [[deprecated("Use `FOO.lists() = BAR` instead of `FOO.set_lists(BAR)`")]]
  ::std::vector<::facebook::cachelib::serialization::DListObject>& set_lists(T_MultiDListObject_lists_struct_setter&& lists_) {
    lists_ref() = std::forward<T_MultiDListObject_lists_struct_setter>(lists_);
    return __fbthrift_field_lists;
  }

  template <class Protocol_>
  unsigned long read(Protocol_* iprot);
  template <class Protocol_>
  uint32_t serializedSize(Protocol_ const* prot_) const;
  template <class Protocol_>
  uint32_t serializedSizeZC(Protocol_ const* prot_) const;
  template <class Protocol_>
  uint32_t write(Protocol_* prot_) const;

 private:
  template <class Protocol_>
  void readNoXfer(Protocol_* iprot);

  friend class ::apache::thrift::Cpp2Ops<MultiDListObject>;
  friend void swap(MultiDListObject& a, MultiDListObject& b);
};

template <class Protocol_>
unsigned long MultiDListObject::read(Protocol_* iprot) {
  auto _xferStart = iprot->getCursorPosition();
  readNoXfer(iprot);
  return iprot->getCursorPosition() - _xferStart;
}


} // namespace facebook::cachelib::serialization

namespace apache::thrift::detail {
template <> struct TSchemaAssociation<::facebook::cachelib::serialization::SListObject, false> {
  static ::folly::Range<const ::std::string_view*> bundle();
  static constexpr int64_t programId = -8659343781253558741;
  static constexpr ::std::string_view definitionKey = {"\xd6\xce\x0c\x3d\x65\xa8\x32\xa6\xce\xdd\x49\x14\xde\x4e\xe7\xef", 16};
};
template <> struct TSchemaAssociation<::facebook::cachelib::serialization::DListObject, false> {
  static ::folly::Range<const ::std::string_view*> bundle();
  static constexpr int64_t programId = -8659343781253558741;
  static constexpr ::std::string_view definitionKey = {"\x2c\xba\xa6\x4f\xa8\x5a\x13\xed\x61\x70\x49\x07\x1a\x4c\x41\x75", 16};
};
template <> struct TSchemaAssociation<::facebook::cachelib::serialization::MultiDListObject, false> {
  static ::folly::Range<const ::std::string_view*> bundle();
  static constexpr int64_t programId = -8659343781253558741;
  static constexpr ::std::string_view definitionKey = {"\xe3\x1d\x49\x84\x86\x78\x40\x5f\x94\xf3\x6f\x46\x83\xe8\x61\xc0", 16};
};
} // namespace apache::thrift::detail
