/**
 * Autogenerated by Thrift for cachelib/allocator/datastruct/serialize/objects.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated @nocommit
 */
#pragma once


/**
 * This header file includes the tcc files of the corresponding header file
 * and the header files of its dependent types. Include this header file
 * only when you need to use custom protocols (e.g. DebugProtocol,
 * VirtualProtocol) to read/write thrift structs.
 */

#include "cachelib/allocator/datastruct/serialize/gen-cpp2/objects_types.tcc"



namespace apache {
namespace thrift {
namespace detail {

template <>
struct TccStructTraits<::facebook::cachelib::serialization::SListObject> {
  static void translateFieldName(
      std::string_view _fname,
      int16_t& fid,
      apache::thrift::protocol::TType& _ftype);
};
template <>
struct TccStructTraits<::facebook::cachelib::serialization::DListObject> {
  static void translateFieldName(
      std::string_view _fname,
      int16_t& fid,
      apache::thrift::protocol::TType& _ftype);
};
template <>
struct TccStructTraits<::facebook::cachelib::serialization::MultiDListObject> {
  static void translateFieldName(
      std::string_view _fname,
      int16_t& fid,
      apache::thrift::protocol::TType& _ftype);
};

} // namespace detail
} // namespace thrift
} // namespace apache

namespace facebook::cachelib::serialization {

template <class Protocol_>
void SListObject::readNoXfer(Protocol_* iprot) {
  apache::thrift::detail::ProtocolReaderStructReadState<Protocol_> _readState;

  _readState.readStructBegin(iprot);

  using apache::thrift::TProtocolException;


  if (UNLIKELY(!_readState.advanceToNextField(
          iprot,
          0,
          2,
          apache::thrift::protocol::TType::T_I64))) {
    goto _advance_failure;
  }
_readField_size:
  {
    ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int64_t>::readWithContext(*iprot, this->__fbthrift_field_size, _readState);
  }

  if (UNLIKELY(!_readState.advanceToNextField(
          iprot,
          2,
          3,
          apache::thrift::protocol::TType::T_I64))) {
    goto _advance_failure;
  }
_readField_compressedHead:
  {
    ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int64_t>::readWithContext(*iprot, this->__fbthrift_field_compressedHead, _readState);
  }

  if (UNLIKELY(!_readState.advanceToNextField(
          iprot,
          3,
          4,
          apache::thrift::protocol::TType::T_I64))) {
    goto _advance_failure;
  }
_readField_compressedTail:
  {
    ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int64_t>::readWithContext(*iprot, this->__fbthrift_field_compressedTail, _readState);
  }
 this->__isset.set(0, true);

  if (UNLIKELY(!_readState.advanceToNextField(
          iprot,
          4,
          0,
          apache::thrift::protocol::T_STOP))) {
    goto _advance_failure;
  }

_end:
  _readState.readStructEnd(iprot);

  return;

  goto _advance_failure; // Avoid compiler warnings about unused labels.
  _advance_failure:
  _readState.afterAdvanceFailure(iprot);
_loop:
  if (_readState.atStop()) {
    goto _end;
  }
  if (iprot->kUsesFieldNames()) {
    _readState.template fillFieldTraitsFromName<apache::thrift::detail::TccStructTraits<SListObject>>();
  }

  switch (_readState.fieldId) {
    case 2:
    {
      if (LIKELY(_readState.isCompatibleWithType(iprot, apache::thrift::protocol::TType::T_I64))) {
        goto _readField_size;
      } else {
        goto _skip;
      }
    }
    case 3:
    {
      if (LIKELY(_readState.isCompatibleWithType(iprot, apache::thrift::protocol::TType::T_I64))) {
        goto _readField_compressedHead;
      } else {
        goto _skip;
      }
    }
    case 4:
    {
      if (LIKELY(_readState.isCompatibleWithType(iprot, apache::thrift::protocol::TType::T_I64))) {
        goto _readField_compressedTail;
      } else {
        goto _skip;
      }
    }
    default:
    {
_skip:
      _readState.skip(iprot);
      _readState.readFieldEnd(iprot);
      _readState.readFieldBeginNoInline(iprot);
      goto _loop;
    }
  }
}

template <class Protocol_>
uint32_t SListObject::serializedSize(Protocol_ const* prot_) const {
  uint32_t xfer = 0;
  xfer += prot_->serializedStructSize("SListObject");
  {
    xfer += prot_->serializedFieldSize("size", apache::thrift::protocol::TType::T_I64, 2);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int64_t>::serializedSize<false>(*prot_, this->__fbthrift_field_size);
  }
  {
    xfer += prot_->serializedFieldSize("compressedHead", apache::thrift::protocol::TType::T_I64, 3);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int64_t>::serializedSize<false>(*prot_, this->__fbthrift_field_compressedHead);
  }
  {
    xfer += prot_->serializedFieldSize("compressedTail", apache::thrift::protocol::TType::T_I64, 4);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int64_t>::serializedSize<false>(*prot_, this->__fbthrift_field_compressedTail);
  }
  xfer += prot_->serializedSizeStop();
  return xfer;
}

template <class Protocol_>
uint32_t SListObject::serializedSizeZC(Protocol_ const* prot_) const {
  uint32_t xfer = 0;
  xfer += prot_->serializedStructSize("SListObject");
  {
    xfer += prot_->serializedFieldSize("size", apache::thrift::protocol::TType::T_I64, 2);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int64_t>::serializedSize<false>(*prot_, this->__fbthrift_field_size);
  }
  {
    xfer += prot_->serializedFieldSize("compressedHead", apache::thrift::protocol::TType::T_I64, 3);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int64_t>::serializedSize<false>(*prot_, this->__fbthrift_field_compressedHead);
  }
  {
    xfer += prot_->serializedFieldSize("compressedTail", apache::thrift::protocol::TType::T_I64, 4);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int64_t>::serializedSize<false>(*prot_, this->__fbthrift_field_compressedTail);
  }
  xfer += prot_->serializedSizeStop();
  return xfer;
}

template <class Protocol_>
uint32_t SListObject::write(Protocol_* prot_) const {
  // If the protocol requests field-id-ascending order and it differs from
  // the codegen serialization order, delegate to the generic StructEncode
  // which respects FieldOrder::IdAscending.
  if constexpr (requires { prot_->fieldOrder(); }) {
    if (prot_->fieldOrder() == ::apache::thrift::FieldOrder::IdAscending) {
      return ::apache::thrift::op::detail::StructEncode<SListObject>{}(*prot_, *this);
    }
  }
  uint32_t xfer = 0;
  xfer += prot_->writeStructBegin("SListObject");
  bool previousFieldHasValue = true;
  {
    constexpr int16_t kPrevFieldId = 0;
    xfer += ::apache::thrift::detail::writeFieldBegin<apache::thrift::protocol::TType::T_I64, 2, kPrevFieldId>(*prot_, "size", previousFieldHasValue);
    previousFieldHasValue = true;
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int64_t>::write(*prot_, this->__fbthrift_field_size);
    xfer += prot_->writeFieldEnd();
  }
  {
    constexpr int16_t kPrevFieldId = 2;
    xfer += ::apache::thrift::detail::writeFieldBegin<apache::thrift::protocol::TType::T_I64, 3, kPrevFieldId>(*prot_, "compressedHead", previousFieldHasValue);
    previousFieldHasValue = true;
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int64_t>::write(*prot_, this->__fbthrift_field_compressedHead);
    xfer += prot_->writeFieldEnd();
  }
  {
    constexpr int16_t kPrevFieldId = 3;
    xfer += ::apache::thrift::detail::writeFieldBegin<apache::thrift::protocol::TType::T_I64, 4, kPrevFieldId>(*prot_, "compressedTail", previousFieldHasValue);
    previousFieldHasValue = true;
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int64_t>::write(*prot_, this->__fbthrift_field_compressedTail);
    xfer += prot_->writeFieldEnd();
  }
  xfer += prot_->writeFieldStop();
  xfer += prot_->writeStructEnd();
  return xfer;
}

extern template void SListObject::readNoXfer<>(apache::thrift::BinaryProtocolReader*);
extern template uint32_t SListObject::write<>(apache::thrift::BinaryProtocolWriter*) const;
extern template uint32_t SListObject::serializedSize<>(apache::thrift::BinaryProtocolWriter const*) const;
extern template uint32_t SListObject::serializedSizeZC<>(apache::thrift::BinaryProtocolWriter const*) const;
extern template void SListObject::readNoXfer<>(apache::thrift::CompactProtocolReader*);
extern template uint32_t SListObject::write<>(apache::thrift::CompactProtocolWriter*) const;
extern template uint32_t SListObject::serializedSize<>(apache::thrift::CompactProtocolWriter const*) const;
extern template uint32_t SListObject::serializedSizeZC<>(apache::thrift::CompactProtocolWriter const*) const;


template <class Protocol_>
void DListObject::readNoXfer(Protocol_* iprot) {
  apache::thrift::detail::ProtocolReaderStructReadState<Protocol_> _readState;

  _readState.readStructBegin(iprot);

  using apache::thrift::TProtocolException;


  if (UNLIKELY(!_readState.advanceToNextField(
          iprot,
          0,
          1,
          apache::thrift::protocol::TType::T_I64))) {
    goto _advance_failure;
  }
_readField_compressedHead:
  {
    ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int64_t>::readWithContext(*iprot, this->__fbthrift_field_compressedHead, _readState);
  }

  if (UNLIKELY(!_readState.advanceToNextField(
          iprot,
          1,
          2,
          apache::thrift::protocol::TType::T_I64))) {
    goto _advance_failure;
  }
_readField_compressedTail:
  {
    ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int64_t>::readWithContext(*iprot, this->__fbthrift_field_compressedTail, _readState);
  }

  if (UNLIKELY(!_readState.advanceToNextField(
          iprot,
          2,
          3,
          apache::thrift::protocol::TType::T_I64))) {
    goto _advance_failure;
  }
_readField_size:
  {
    ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int64_t>::readWithContext(*iprot, this->__fbthrift_field_size, _readState);
  }

  if (UNLIKELY(!_readState.advanceToNextField(
          iprot,
          3,
          0,
          apache::thrift::protocol::T_STOP))) {
    goto _advance_failure;
  }

_end:
  _readState.readStructEnd(iprot);

  return;

  goto _advance_failure; // Avoid compiler warnings about unused labels.
  _advance_failure:
  _readState.afterAdvanceFailure(iprot);
_loop:
  if (_readState.atStop()) {
    goto _end;
  }
  if (iprot->kUsesFieldNames()) {
    _readState.template fillFieldTraitsFromName<apache::thrift::detail::TccStructTraits<DListObject>>();
  }

  switch (_readState.fieldId) {
    case 1:
    {
      if (LIKELY(_readState.isCompatibleWithType(iprot, apache::thrift::protocol::TType::T_I64))) {
        goto _readField_compressedHead;
      } else {
        goto _skip;
      }
    }
    case 2:
    {
      if (LIKELY(_readState.isCompatibleWithType(iprot, apache::thrift::protocol::TType::T_I64))) {
        goto _readField_compressedTail;
      } else {
        goto _skip;
      }
    }
    case 3:
    {
      if (LIKELY(_readState.isCompatibleWithType(iprot, apache::thrift::protocol::TType::T_I64))) {
        goto _readField_size;
      } else {
        goto _skip;
      }
    }
    default:
    {
_skip:
      _readState.skip(iprot);
      _readState.readFieldEnd(iprot);
      _readState.readFieldBeginNoInline(iprot);
      goto _loop;
    }
  }
}

template <class Protocol_>
uint32_t DListObject::serializedSize(Protocol_ const* prot_) const {
  uint32_t xfer = 0;
  xfer += prot_->serializedStructSize("DListObject");
  {
    xfer += prot_->serializedFieldSize("compressedHead", apache::thrift::protocol::TType::T_I64, 1);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int64_t>::serializedSize<false>(*prot_, this->__fbthrift_field_compressedHead);
  }
  {
    xfer += prot_->serializedFieldSize("compressedTail", apache::thrift::protocol::TType::T_I64, 2);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int64_t>::serializedSize<false>(*prot_, this->__fbthrift_field_compressedTail);
  }
  {
    xfer += prot_->serializedFieldSize("size", apache::thrift::protocol::TType::T_I64, 3);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int64_t>::serializedSize<false>(*prot_, this->__fbthrift_field_size);
  }
  xfer += prot_->serializedSizeStop();
  return xfer;
}

template <class Protocol_>
uint32_t DListObject::serializedSizeZC(Protocol_ const* prot_) const {
  uint32_t xfer = 0;
  xfer += prot_->serializedStructSize("DListObject");
  {
    xfer += prot_->serializedFieldSize("compressedHead", apache::thrift::protocol::TType::T_I64, 1);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int64_t>::serializedSize<false>(*prot_, this->__fbthrift_field_compressedHead);
  }
  {
    xfer += prot_->serializedFieldSize("compressedTail", apache::thrift::protocol::TType::T_I64, 2);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int64_t>::serializedSize<false>(*prot_, this->__fbthrift_field_compressedTail);
  }
  {
    xfer += prot_->serializedFieldSize("size", apache::thrift::protocol::TType::T_I64, 3);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int64_t>::serializedSize<false>(*prot_, this->__fbthrift_field_size);
  }
  xfer += prot_->serializedSizeStop();
  return xfer;
}

template <class Protocol_>
uint32_t DListObject::write(Protocol_* prot_) const {
  // If the protocol requests field-id-ascending order and it differs from
  // the codegen serialization order, delegate to the generic StructEncode
  // which respects FieldOrder::IdAscending.
  if constexpr (requires { prot_->fieldOrder(); }) {
    if (prot_->fieldOrder() == ::apache::thrift::FieldOrder::IdAscending) {
      return ::apache::thrift::op::detail::StructEncode<DListObject>{}(*prot_, *this);
    }
  }
  uint32_t xfer = 0;
  xfer += prot_->writeStructBegin("DListObject");
  bool previousFieldHasValue = true;
  {
    constexpr int16_t kPrevFieldId = 0;
    xfer += ::apache::thrift::detail::writeFieldBegin<apache::thrift::protocol::TType::T_I64, 1, kPrevFieldId>(*prot_, "compressedHead", previousFieldHasValue);
    previousFieldHasValue = true;
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int64_t>::write(*prot_, this->__fbthrift_field_compressedHead);
    xfer += prot_->writeFieldEnd();
  }
  {
    constexpr int16_t kPrevFieldId = 1;
    xfer += ::apache::thrift::detail::writeFieldBegin<apache::thrift::protocol::TType::T_I64, 2, kPrevFieldId>(*prot_, "compressedTail", previousFieldHasValue);
    previousFieldHasValue = true;
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int64_t>::write(*prot_, this->__fbthrift_field_compressedTail);
    xfer += prot_->writeFieldEnd();
  }
  {
    constexpr int16_t kPrevFieldId = 2;
    xfer += ::apache::thrift::detail::writeFieldBegin<apache::thrift::protocol::TType::T_I64, 3, kPrevFieldId>(*prot_, "size", previousFieldHasValue);
    previousFieldHasValue = true;
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int64_t>::write(*prot_, this->__fbthrift_field_size);
    xfer += prot_->writeFieldEnd();
  }
  xfer += prot_->writeFieldStop();
  xfer += prot_->writeStructEnd();
  return xfer;
}

extern template void DListObject::readNoXfer<>(apache::thrift::BinaryProtocolReader*);
extern template uint32_t DListObject::write<>(apache::thrift::BinaryProtocolWriter*) const;
extern template uint32_t DListObject::serializedSize<>(apache::thrift::BinaryProtocolWriter const*) const;
extern template uint32_t DListObject::serializedSizeZC<>(apache::thrift::BinaryProtocolWriter const*) const;
extern template void DListObject::readNoXfer<>(apache::thrift::CompactProtocolReader*);
extern template uint32_t DListObject::write<>(apache::thrift::CompactProtocolWriter*) const;
extern template uint32_t DListObject::serializedSize<>(apache::thrift::CompactProtocolWriter const*) const;
extern template uint32_t DListObject::serializedSizeZC<>(apache::thrift::CompactProtocolWriter const*) const;


template <class Protocol_>
void MultiDListObject::readNoXfer(Protocol_* iprot) {
  apache::thrift::detail::ProtocolReaderStructReadState<Protocol_> _readState;

  _readState.readStructBegin(iprot);

  using apache::thrift::TProtocolException;


  if (UNLIKELY(!_readState.advanceToNextField(
          iprot,
          0,
          1,
          apache::thrift::protocol::TType::T_LIST))) {
    goto _advance_failure;
  }
_readField_lists:
  {
    _readState.beforeSubobject(iprot);
    this->__fbthrift_field_lists = ::std::vector<::facebook::cachelib::serialization::DListObject>();
    ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::list<::apache::thrift::type_class::structure>, ::std::vector<::facebook::cachelib::serialization::DListObject>>::readWithContext(*iprot, this->__fbthrift_field_lists, _readState);
    _readState.afterSubobject(iprot);
  }

  if (UNLIKELY(!_readState.advanceToNextField(
          iprot,
          1,
          0,
          apache::thrift::protocol::T_STOP))) {
    goto _advance_failure;
  }

_end:
  _readState.readStructEnd(iprot);

  return;

  goto _advance_failure; // Avoid compiler warnings about unused labels.
  _advance_failure:
  _readState.afterAdvanceFailure(iprot);
_loop:
  if (_readState.atStop()) {
    goto _end;
  }
  if (iprot->kUsesFieldNames()) {
    _readState.template fillFieldTraitsFromName<apache::thrift::detail::TccStructTraits<MultiDListObject>>();
  }

  switch (_readState.fieldId) {
    case 1:
    {
      if (LIKELY(_readState.isCompatibleWithType(iprot, apache::thrift::protocol::TType::T_LIST))) {
        goto _readField_lists;
      } else {
        goto _skip;
      }
    }
    default:
    {
_skip:
      _readState.skip(iprot);
      _readState.readFieldEnd(iprot);
      _readState.readFieldBeginNoInline(iprot);
      goto _loop;
    }
  }
}

template <class Protocol_>
uint32_t MultiDListObject::serializedSize(Protocol_ const* prot_) const {
  uint32_t xfer = 0;
  xfer += prot_->serializedStructSize("MultiDListObject");
  {
    xfer += prot_->serializedFieldSize("lists", apache::thrift::protocol::TType::T_LIST, 1);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::list<::apache::thrift::type_class::structure>, ::std::vector<::facebook::cachelib::serialization::DListObject>>::serializedSize<false>(*prot_, this->__fbthrift_field_lists);
  }
  xfer += prot_->serializedSizeStop();
  return xfer;
}

template <class Protocol_>
uint32_t MultiDListObject::serializedSizeZC(Protocol_ const* prot_) const {
  uint32_t xfer = 0;
  xfer += prot_->serializedStructSize("MultiDListObject");
  {
    xfer += prot_->serializedFieldSize("lists", apache::thrift::protocol::TType::T_LIST, 1);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::list<::apache::thrift::type_class::structure>, ::std::vector<::facebook::cachelib::serialization::DListObject>>::serializedSize<true>(*prot_, this->__fbthrift_field_lists);
  }
  xfer += prot_->serializedSizeStop();
  return xfer;
}

template <class Protocol_>
uint32_t MultiDListObject::write(Protocol_* prot_) const {
  // If the protocol requests field-id-ascending order and it differs from
  // the codegen serialization order, delegate to the generic StructEncode
  // which respects FieldOrder::IdAscending.
  if constexpr (requires { prot_->fieldOrder(); }) {
    if (prot_->fieldOrder() == ::apache::thrift::FieldOrder::IdAscending) {
      return ::apache::thrift::op::detail::StructEncode<MultiDListObject>{}(*prot_, *this);
    }
  }
  uint32_t xfer = 0;
  xfer += prot_->writeStructBegin("MultiDListObject");
  bool previousFieldHasValue = true;
  {
    constexpr int16_t kPrevFieldId = 0;
    xfer += ::apache::thrift::detail::writeFieldBegin<apache::thrift::protocol::TType::T_LIST, 1, kPrevFieldId>(*prot_, "lists", previousFieldHasValue);
    previousFieldHasValue = true;
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::list<::apache::thrift::type_class::structure>, ::std::vector<::facebook::cachelib::serialization::DListObject>>::write(*prot_, this->__fbthrift_field_lists);
    xfer += prot_->writeFieldEnd();
  }
  xfer += prot_->writeFieldStop();
  xfer += prot_->writeStructEnd();
  return xfer;
}

extern template void MultiDListObject::readNoXfer<>(apache::thrift::BinaryProtocolReader*);
extern template uint32_t MultiDListObject::write<>(apache::thrift::BinaryProtocolWriter*) const;
extern template uint32_t MultiDListObject::serializedSize<>(apache::thrift::BinaryProtocolWriter const*) const;
extern template uint32_t MultiDListObject::serializedSizeZC<>(apache::thrift::BinaryProtocolWriter const*) const;
extern template void MultiDListObject::readNoXfer<>(apache::thrift::CompactProtocolReader*);
extern template uint32_t MultiDListObject::write<>(apache::thrift::CompactProtocolWriter*) const;
extern template uint32_t MultiDListObject::serializedSize<>(apache::thrift::CompactProtocolWriter const*) const;
extern template uint32_t MultiDListObject::serializedSizeZC<>(apache::thrift::CompactProtocolWriter const*) const;


} // namespace facebook::cachelib::serialization
