/**
 * Autogenerated by Thrift for cachelib/allocator/datastruct/serialize/objects.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated @nocommit
 */
#pragma once

#include <thrift/lib/cpp2/frozen/Frozen.h>
#include "cachelib/allocator/datastruct/serialize/gen-cpp2/objects_types.h"
namespace apache::thrift::frozen {


FROZEN_TYPE(::facebook::cachelib::serialization::SListObject,
  FROZEN_FIELD_REQ(size, 2, ::std::int64_t)
  FROZEN_FIELD_REQ(compressedHead, 3, ::std::int64_t)
  FROZEN_FIELD(compressedTail, 4, ::std::int64_t)
  FROZEN_VIEW(
    FROZEN_VIEW_FIELD_REQ(size, ::std::int64_t)
    FROZEN_VIEW_FIELD_REQ(compressedHead, ::std::int64_t)
    FROZEN_VIEW_FIELD(compressedTail, ::std::int64_t))
  FROZEN_SAVE_INLINE(
    FROZEN_SAVE_FIELD(size)
    FROZEN_SAVE_FIELD(compressedHead)
    FROZEN_SAVE_FIELD(compressedTail))
  FROZEN_LOAD_INLINE(
    FROZEN_LOAD_FIELD(size, 2)
    FROZEN_LOAD_FIELD(compressedHead, 3)
    FROZEN_LOAD_FIELD(compressedTail, 4)));

FROZEN_TYPE(::facebook::cachelib::serialization::DListObject,
  FROZEN_FIELD_REQ(compressedHead, 1, ::std::int64_t)
  FROZEN_FIELD_REQ(compressedTail, 2, ::std::int64_t)
  FROZEN_FIELD_REQ(size, 3, ::std::int64_t)
  FROZEN_VIEW(
    FROZEN_VIEW_FIELD_REQ(compressedHead, ::std::int64_t)
    FROZEN_VIEW_FIELD_REQ(compressedTail, ::std::int64_t)
    FROZEN_VIEW_FIELD_REQ(size, ::std::int64_t))
  FROZEN_SAVE_INLINE(
    FROZEN_SAVE_FIELD(compressedHead)
    FROZEN_SAVE_FIELD(compressedTail)
    FROZEN_SAVE_FIELD(size))
  FROZEN_LOAD_INLINE(
    FROZEN_LOAD_FIELD(compressedHead, 1)
    FROZEN_LOAD_FIELD(compressedTail, 2)
    FROZEN_LOAD_FIELD(size, 3)));

FROZEN_TYPE(::facebook::cachelib::serialization::MultiDListObject,
  FROZEN_FIELD_REQ(lists, 1, ::std::vector<::facebook::cachelib::serialization::DListObject>)
  FROZEN_VIEW(
    FROZEN_VIEW_FIELD_REQ(lists, ::std::vector<::facebook::cachelib::serialization::DListObject>))
  FROZEN_SAVE_INLINE(
    FROZEN_SAVE_FIELD(lists))
  FROZEN_LOAD_INLINE(
    FROZEN_LOAD_FIELD(lists, 1)));

} // apache::thrift::frozen
