/**
 * Autogenerated by Thrift for cachelib/allocator/datastruct/serialize/objects.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated @nocommit
 */
#include "cachelib/allocator/datastruct/serialize/gen-cpp2/objects_types_custom_protocol.h"

namespace facebook::cachelib::serialization {

template void SListObject::readNoXfer<>(apache::thrift::BinaryProtocolReader*);
template uint32_t SListObject::write<>(apache::thrift::BinaryProtocolWriter*) const;
template uint32_t SListObject::serializedSize<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t SListObject::serializedSizeZC<>(apache::thrift::BinaryProtocolWriter const*) const;

template void DListObject::readNoXfer<>(apache::thrift::BinaryProtocolReader*);
template uint32_t DListObject::write<>(apache::thrift::BinaryProtocolWriter*) const;
template uint32_t DListObject::serializedSize<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t DListObject::serializedSizeZC<>(apache::thrift::BinaryProtocolWriter const*) const;

template void MultiDListObject::readNoXfer<>(apache::thrift::BinaryProtocolReader*);
template uint32_t MultiDListObject::write<>(apache::thrift::BinaryProtocolWriter*) const;
template uint32_t MultiDListObject::serializedSize<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t MultiDListObject::serializedSizeZC<>(apache::thrift::BinaryProtocolWriter const*) const;

} // namespace facebook::cachelib::serialization
