/**
 * Autogenerated by Thrift for test_objects.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated @nocommit
 */
#include "test_objects_types.tcc"
#include "test_objects_constants.h"
#include "test_objects_data.h"

#include <thrift/lib/cpp2/gen/module_types_cpp.h>

[[maybe_unused]] static constexpr std::string_view kModuleName = "test_objects";



namespace facebook::cachelib::test_serialization {

std::string_view SListObjectNoCompressedTail::__fbthrift_get_field_name(::apache::thrift::FieldOrdinal ord) {
  if (ord == ::apache::thrift::FieldOrdinal{0}) { return {}; }
  return apache::thrift::TStructDataStorage<SListObjectNoCompressedTail>::fields_names[folly::to_underlying(ord) - 1];
}
std::string_view SListObjectNoCompressedTail::__fbthrift_get_class_name() {
  return apache::thrift::TStructDataStorage<SListObjectNoCompressedTail>::name;
}


SListObjectNoCompressedTail::SListObjectNoCompressedTail(apache::thrift::FragileConstructor, ::std::int64_t size__arg, ::std::int64_t compressedHead__arg) :
    __fbthrift_field_size(std::move(size__arg)),
    __fbthrift_field_compressedHead(std::move(compressedHead__arg)) { 
}

void SListObjectNoCompressedTail::__fbthrift_clear() {
  // clear all fields
  this->__fbthrift_field_size = ::std::int64_t();
  this->__fbthrift_field_compressedHead = ::std::int64_t();
}

bool SListObjectNoCompressedTail::__fbthrift_is_empty() const {
  return false;
}

bool SListObjectNoCompressedTail::operator==([[maybe_unused]] const SListObjectNoCompressedTail& rhs) const {
  return ::apache::thrift::op::detail::StructEquality{}(*this, rhs);
}

bool SListObjectNoCompressedTail::operator<([[maybe_unused]] const SListObjectNoCompressedTail& rhs) const {
  return ::apache::thrift::op::detail::StructLessThan{}(*this, rhs);
}


::std::int64_t SListObjectNoCompressedTail::get_size() const {
  return __fbthrift_field_size;
}

::std::int64_t& SListObjectNoCompressedTail::set_size(::std::int64_t size_) {
  size_ref() = size_;
  return __fbthrift_field_size;
}

::std::int64_t SListObjectNoCompressedTail::get_compressedHead() const {
  return __fbthrift_field_compressedHead;
}

::std::int64_t& SListObjectNoCompressedTail::set_compressedHead(::std::int64_t compressedHead_) {
  compressedHead_ref() = compressedHead_;
  return __fbthrift_field_compressedHead;
}

void swap([[maybe_unused]] SListObjectNoCompressedTail& a, [[maybe_unused]] SListObjectNoCompressedTail& b) {
  using ::std::swap;
  swap(a.__fbthrift_field_size, b.__fbthrift_field_size);
  swap(a.__fbthrift_field_compressedHead, b.__fbthrift_field_compressedHead);
}


} // namespace facebook::cachelib::test_serialization

namespace facebook::cachelib::test_serialization { namespace {
[[maybe_unused]] FOLLY_ERASE void validateAdapters() {
}
}} // namespace facebook::cachelib::test_serialization
namespace apache::thrift::detail::annotation {
}
