/**
 * Autogenerated by Thrift for test_objects.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated @nocommit
 */

#pragma once

#include <thrift/lib/cpp2/gen/module_types_h.h>

namespace apache::thrift {
namespace ident {
struct size;
struct compressedHead;
} // namespace ident
namespace detail {
#ifndef APACHE_THRIFT_ACCESSOR_size
#define APACHE_THRIFT_ACCESSOR_size
APACHE_THRIFT_DEFINE_ACCESSOR(size);
#endif
#ifndef APACHE_THRIFT_ACCESSOR_compressedHead
#define APACHE_THRIFT_ACCESSOR_compressedHead
APACHE_THRIFT_DEFINE_ACCESSOR(compressedHead);
#endif
} // namespace detail
} // namespace apache::thrift

// BEGIN declare_enums
// END declare_enums
// BEGIN forward_declare
namespace facebook::cachelib::test_serialization {
class SListObjectNoCompressedTail;
} // namespace facebook::cachelib::test_serialization
// END forward_declare
namespace apache::thrift::detail::annotation {
} // namespace apache::thrift::detail::annotation

namespace apache::thrift::detail::qualifier {
} // namespace apache::thrift::detail::qualifier

// BEGIN hash_and_equal_to
// END hash_and_equal_to
namespace facebook::cachelib::test_serialization {
using ::apache::thrift::detail::operator!=;
using ::apache::thrift::detail::operator>;
using ::apache::thrift::detail::operator<=;
using ::apache::thrift::detail::operator>=;


/** Glean {"file": "test_objects.thrift", "name": "SListObjectNoCompressedTail", "kind": "struct" } */
class SListObjectNoCompressedTail final  {
 private:
  friend struct ::apache::thrift::detail::st::struct_private_access;
  template<class> friend struct ::apache::thrift::detail::invoke_reffer;

  //  used by a static_assert in the corresponding source
  static constexpr bool __fbthrift_cpp2_gen_json = false;
  static constexpr bool __fbthrift_cpp2_is_runtime_annotation = false;
  static std::string_view __fbthrift_get_field_name(::apache::thrift::FieldOrdinal ord);
  static std::string_view __fbthrift_get_class_name();
  template <class ...>
  FOLLY_ERASE static constexpr std::string_view __fbthrift_get_module_name() noexcept {
    return "test_objects";
  }
  static constexpr std::size_t __fbthrift_num_fields = 2;

  static constexpr const int16_t __fbthrift_reflection_field_ids[] = {0,2,3};

  using __fbthrift_reflection_idents = folly::tag_t<
    ::apache::thrift::ident::size,
    ::apache::thrift::ident::compressedHead
  >;

  using __fbthrift_reflection_type_tags = folly::tag_t<
    ::apache::thrift::type::i64_t,
    ::apache::thrift::type::i64_t
  >;
  void __fbthrift_clear();
  bool __fbthrift_is_empty() const;

 public:
  using __fbthrift_cpp2_type = SListObjectNoCompressedTail;
  static constexpr bool __fbthrift_cpp2_is_union =
    false;


 public:

  SListObjectNoCompressedTail() :
      __fbthrift_field_size(),
      __fbthrift_field_compressedHead() {
  }
  // FragileConstructor for use in initialization lists only.
  [[deprecated("This constructor is deprecated")]]
  SListObjectNoCompressedTail(apache::thrift::FragileConstructor, ::std::int64_t size__arg, ::std::int64_t compressedHead__arg);

  SListObjectNoCompressedTail(SListObjectNoCompressedTail&&) = default;
  SListObjectNoCompressedTail(const SListObjectNoCompressedTail&) = default;


  SListObjectNoCompressedTail& operator=(SListObjectNoCompressedTail&&) = default;
  SListObjectNoCompressedTail& operator=(const SListObjectNoCompressedTail&) = default;
 private:
  ::std::int64_t __fbthrift_field_size;
 private:
  ::std::int64_t __fbthrift_field_compressedHead;

 public:

  bool operator==(const SListObjectNoCompressedTail&) const;
  bool operator<(const SListObjectNoCompressedTail&) const;

  /** Glean { "field": "size" } */
  template <typename..., typename fbthrift_T = ::std::int64_t>
  FOLLY_ERASE ::apache::thrift::required_field_ref<const fbthrift_T&> size_ref() const& {
    return ::apache::thrift::required_field_ref<const fbthrift_T&>{this->__fbthrift_field_size};
  }

  /** Glean { "field": "size" } */
  template <typename..., typename fbthrift_T = ::std::int64_t>
  FOLLY_ERASE ::apache::thrift::required_field_ref<fbthrift_T&> size_ref() & {
    return ::apache::thrift::required_field_ref<fbthrift_T&>{this->__fbthrift_field_size};
  }

  /** Glean { "field": "size" } */
  template <typename..., typename fbthrift_T = ::std::int64_t>
  FOLLY_ERASE ::apache::thrift::required_field_ref<fbthrift_T&&> size_ref() && {
    return ::apache::thrift::required_field_ref<fbthrift_T&&>{static_cast<fbthrift_T&&>(this->__fbthrift_field_size)};
  }

  /** Glean { "field": "size" } */
  template <typename..., typename fbthrift_T = ::std::int64_t>
  FOLLY_ERASE ::apache::thrift::required_field_ref<const fbthrift_T&> size() const& {
    return ::apache::thrift::required_field_ref<const fbthrift_T&>{this->__fbthrift_field_size};
  }

  /** Glean { "field": "size" } */
  template <typename..., typename fbthrift_T = ::std::int64_t>
  FOLLY_ERASE ::apache::thrift::required_field_ref<fbthrift_T&> size() & {
    return ::apache::thrift::required_field_ref<fbthrift_T&>{this->__fbthrift_field_size};
  }

  /** Glean { "field": "size" } */
  template <typename..., typename fbthrift_T = ::std::int64_t>
  FOLLY_ERASE ::apache::thrift::required_field_ref<fbthrift_T&&> size() && {
    return ::apache::thrift::required_field_ref<fbthrift_T&&>{static_cast<fbthrift_T&&>(this->__fbthrift_field_size)};
  }

  /** Glean { "field": "compressedHead" } */
  template <typename..., typename fbthrift_T = ::std::int64_t>
  FOLLY_ERASE ::apache::thrift::required_field_ref<const fbthrift_T&> compressedHead_ref() const& {
    return ::apache::thrift::required_field_ref<const fbthrift_T&>{this->__fbthrift_field_compressedHead};
  }

  /** Glean { "field": "compressedHead" } */
  template <typename..., typename fbthrift_T = ::std::int64_t>
  FOLLY_ERASE ::apache::thrift::required_field_ref<fbthrift_T&> compressedHead_ref() & {
    return ::apache::thrift::required_field_ref<fbthrift_T&>{this->__fbthrift_field_compressedHead};
  }

  /** Glean { "field": "compressedHead" } */
  template <typename..., typename fbthrift_T = ::std::int64_t>
  FOLLY_ERASE ::apache::thrift::required_field_ref<fbthrift_T&&> compressedHead_ref() && {
    return ::apache::thrift::required_field_ref<fbthrift_T&&>{static_cast<fbthrift_T&&>(this->__fbthrift_field_compressedHead)};
  }

  /** Glean { "field": "compressedHead" } */
  template <typename..., typename fbthrift_T = ::std::int64_t>
  FOLLY_ERASE ::apache::thrift::required_field_ref<const fbthrift_T&> compressedHead() const& {
    return ::apache::thrift::required_field_ref<const fbthrift_T&>{this->__fbthrift_field_compressedHead};
  }

  /** Glean { "field": "compressedHead" } */
  template <typename..., typename fbthrift_T = ::std::int64_t>
  FOLLY_ERASE ::apache::thrift::required_field_ref<fbthrift_T&> compressedHead() & {
    return ::apache::thrift::required_field_ref<fbthrift_T&>{this->__fbthrift_field_compressedHead};
  }

  /** Glean { "field": "compressedHead" } */
  template <typename..., typename fbthrift_T = ::std::int64_t>
  FOLLY_ERASE ::apache::thrift::required_field_ref<fbthrift_T&&> compressedHead() && {
    return ::apache::thrift::required_field_ref<fbthrift_T&&>{static_cast<fbthrift_T&&>(this->__fbthrift_field_compressedHead)};
  }

  /** Glean { "field": "size" } */
  [[deprecated("Use `FOO.size().value()` instead of `FOO.get_size()`")]]
  ::std::int64_t get_size() const;

  /** Glean { "field": "size" } */
  [[deprecated("Use `FOO.size() = BAR` instead of `FOO.set_size(BAR)`")]]
  ::std::int64_t& set_size(::std::int64_t size_);

  /** Glean { "field": "compressedHead" } */
  [[deprecated("Use `FOO.compressedHead().value()` instead of `FOO.get_compressedHead()`")]]
  ::std::int64_t get_compressedHead() const;

  /** Glean { "field": "compressedHead" } */
  [[deprecated("Use `FOO.compressedHead() = BAR` instead of `FOO.set_compressedHead(BAR)`")]]
  ::std::int64_t& set_compressedHead(::std::int64_t compressedHead_);

  template <class Protocol_>
  unsigned long read(Protocol_* iprot);
  template <class Protocol_>
  uint32_t serializedSize(Protocol_ const* prot_) const;
  template <class Protocol_>
  uint32_t serializedSizeZC(Protocol_ const* prot_) const;
  template <class Protocol_>
  uint32_t write(Protocol_* prot_) const;

 private:
  template <class Protocol_>
  void readNoXfer(Protocol_* iprot);

  friend class ::apache::thrift::Cpp2Ops<SListObjectNoCompressedTail>;
  friend void swap(SListObjectNoCompressedTail& a, SListObjectNoCompressedTail& b);
};

template <class Protocol_>
unsigned long SListObjectNoCompressedTail::read(Protocol_* iprot) {
  auto _xferStart = iprot->getCursorPosition();
  readNoXfer(iprot);
  return iprot->getCursorPosition() - _xferStart;
}


} // namespace facebook::cachelib::test_serialization

namespace apache::thrift::detail {
template <> struct TSchemaAssociation<::facebook::cachelib::test_serialization::SListObjectNoCompressedTail, false> {
  static ::folly::Range<const ::std::string_view*> bundle();
  static constexpr int64_t programId = -2309398325310486508;
  static constexpr ::std::string_view definitionKey = {"\x07\xe6\x1e\xcc\xb9\x64\x5c\x80\xb1\x1e\x20\xf8\x9f\xcd\x90\xc3", 16};
};
} // namespace apache::thrift::detail
