/**
 * Autogenerated by Thrift for test_objects.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated @nocommit
 */
#pragma once

#include <thrift/lib/cpp2/visitation/visit_by_thrift_field_metadata.h>
#include "test_objects_metadata.h"

namespace apache {
namespace thrift {
namespace detail {

template <>
struct VisitByFieldId<::facebook::cachelib::test_serialization::SListObjectNoCompressedTail> {
  template <typename F, typename T>
  void operator()([[maybe_unused]] F&& f, int32_t fieldId, [[maybe_unused]] T&& t) const {
    switch (fieldId) {
    case 2:
      return f(0, static_cast<T&&>(t).size_ref());
    case 3:
      return f(1, static_cast<T&&>(t).compressedHead_ref());
    default:
      throwInvalidThriftId(fieldId, "::facebook::cachelib::test_serialization::SListObjectNoCompressedTail");
    }
  }
};
} // namespace detail
} // namespace thrift
} // namespace apache
