/**
 * Autogenerated by Thrift for test_objects.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated @nocommit
 */
#pragma once

#include <thrift/lib/cpp2/frozen/Frozen.h>
#include "test_objects_types.h"
namespace apache::thrift::frozen {


FROZEN_TYPE(::facebook::cachelib::test_serialization::SListObjectNoCompressedTail,
  FROZEN_FIELD_REQ(size, 2, ::std::int64_t)
  FROZEN_FIELD_REQ(compressedHead, 3, ::std::int64_t)
  FROZEN_VIEW(
    FROZEN_VIEW_FIELD_REQ(size, ::std::int64_t)
    FROZEN_VIEW_FIELD_REQ(compressedHead, ::std::int64_t))
  FROZEN_SAVE_INLINE(
    FROZEN_SAVE_FIELD(size)
    FROZEN_SAVE_FIELD(compressedHead))
  FROZEN_LOAD_INLINE(
    FROZEN_LOAD_FIELD(size, 2)
    FROZEN_LOAD_FIELD(compressedHead, 3)));

} // apache::thrift::frozen
