/**
 * Autogenerated by Thrift for test_objects.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated @nocommit
 */
#pragma once
#include "test_objects_for_each_field.h"
#include "test_objects_visit_union.h"
#include "test_objects_visit_by_thrift_field_metadata.h"
