/**
 * Autogenerated by Thrift for cachelib/allocator/serialize/objects.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated @nocommit
 */
#pragma once
#include "cachelib/allocator/datastruct/serialize/gen-cpp2/objects_visitation.h"
#include "cachelib/allocator/serialize/gen-cpp2/objects_for_each_field.h"
#include "cachelib/allocator/serialize/gen-cpp2/objects_visit_union.h"
#include "cachelib/allocator/serialize/gen-cpp2/objects_visit_by_thrift_field_metadata.h"
