/**
 * Autogenerated by Thrift for cachelib/allocator/serialize/objects.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated @nocommit
 */

#include "cachelib/allocator/serialize/gen-cpp2/objects_data.h"
#include "cachelib/allocator/serialize/gen-cpp2/objects_constants.h"

#include <thrift/lib/cpp2/gen/module_data_cpp.h>

namespace apache::thrift {

THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::string_view TStructDataStorage<::facebook::cachelib::serialization::CacheAllocatorMetadata>::name = "CacheAllocatorMetadata";
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<std::string_view, 11> TStructDataStorage<::facebook::cachelib::serialization::CacheAllocatorMetadata>::fields_names = { {
  "allocatorVersion"sv,
  "cacheCreationTime"sv,
  "accessType"sv,
  "mmType"sv,
  "fragmentationSize"sv,
  "compactCachePools"sv,
  "numPermanentItems"sv,
  "numChainedParentItems"sv,
  "numChainedChildItems"sv,
  "ramFormatVersion"sv,
  "numAbortedSlabReleases"sv,
}};
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<int16_t, 11> TStructDataStorage<::facebook::cachelib::serialization::CacheAllocatorMetadata>::fields_ids = { {
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
}};
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<protocol::TType, 11> TStructDataStorage<::facebook::cachelib::serialization::CacheAllocatorMetadata>::fields_types = { {
  apache::thrift::protocol::TType::T_I64,
  apache::thrift::protocol::TType::T_I64,
  apache::thrift::protocol::TType::T_I64,
  apache::thrift::protocol::TType::T_I64,
  apache::thrift::protocol::TType::T_MAP,
  apache::thrift::protocol::TType::T_LIST,
  apache::thrift::protocol::TType::T_I64,
  apache::thrift::protocol::TType::T_I64,
  apache::thrift::protocol::TType::T_I64,
  apache::thrift::protocol::TType::T_I64,
  apache::thrift::protocol::TType::T_I64,
}};
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<int, 11> TStructDataStorage<::facebook::cachelib::serialization::CacheAllocatorMetadata>::isset_indexes = { {
  -1,
  0,
  -1,
  -1,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
}};

THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::string_view TStructDataStorage<::facebook::cachelib::serialization::NvmCacheMetadata>::name = "NvmCacheMetadata";
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<std::string_view, 5> TStructDataStorage<::facebook::cachelib::serialization::NvmCacheMetadata>::fields_names = { {
  "nvmFormatVersion"sv,
  "creationTime"sv,
  "safeShutDown"sv,
  "encryptionEnabled"sv,
  "truncateAllocSize"sv,
}};
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<int16_t, 5> TStructDataStorage<::facebook::cachelib::serialization::NvmCacheMetadata>::fields_ids = { {
  1,
  2,
  3,
  4,
  5,
}};
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<protocol::TType, 5> TStructDataStorage<::facebook::cachelib::serialization::NvmCacheMetadata>::fields_types = { {
  apache::thrift::protocol::TType::T_I64,
  apache::thrift::protocol::TType::T_I64,
  apache::thrift::protocol::TType::T_BOOL,
  apache::thrift::protocol::TType::T_BOOL,
  apache::thrift::protocol::TType::T_BOOL,
}};
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<int, 5> TStructDataStorage<::facebook::cachelib::serialization::NvmCacheMetadata>::isset_indexes = { {
  0,
  1,
  2,
  3,
  4,
}};

THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::string_view TStructDataStorage<::facebook::cachelib::serialization::CompactCacheMetadataObject>::name = "CompactCacheMetadataObject";
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<std::string_view, 2> TStructDataStorage<::facebook::cachelib::serialization::CompactCacheMetadataObject>::fields_names = { {
  "keySize"sv,
  "valueSize"sv,
}};
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<int16_t, 2> TStructDataStorage<::facebook::cachelib::serialization::CompactCacheMetadataObject>::fields_ids = { {
  1,
  2,
}};
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<protocol::TType, 2> TStructDataStorage<::facebook::cachelib::serialization::CompactCacheMetadataObject>::fields_types = { {
  apache::thrift::protocol::TType::T_I64,
  apache::thrift::protocol::TType::T_I64,
}};
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<int, 2> TStructDataStorage<::facebook::cachelib::serialization::CompactCacheMetadataObject>::isset_indexes = { {
  -1,
  -1,
}};

THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::string_view TStructDataStorage<::facebook::cachelib::serialization::CompactCacheAllocatorObject>::name = "CompactCacheAllocatorObject";
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<std::string_view, 2> TStructDataStorage<::facebook::cachelib::serialization::CompactCacheAllocatorObject>::fields_names = { {
  "chunks"sv,
  "ccMetadata"sv,
}};
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<int16_t, 2> TStructDataStorage<::facebook::cachelib::serialization::CompactCacheAllocatorObject>::fields_ids = { {
  1,
  2,
}};
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<protocol::TType, 2> TStructDataStorage<::facebook::cachelib::serialization::CompactCacheAllocatorObject>::fields_types = { {
  apache::thrift::protocol::TType::T_LIST,
  apache::thrift::protocol::TType::T_STRUCT,
}};
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<int, 2> TStructDataStorage<::facebook::cachelib::serialization::CompactCacheAllocatorObject>::isset_indexes = { {
  -1,
  -1,
}};

THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::string_view TStructDataStorage<::facebook::cachelib::serialization::CompactCacheAllocatorManagerObject>::name = "CompactCacheAllocatorManagerObject";
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<std::string_view, 1> TStructDataStorage<::facebook::cachelib::serialization::CompactCacheAllocatorManagerObject>::fields_names = { {
  "allocators"sv,
}};
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<int16_t, 1> TStructDataStorage<::facebook::cachelib::serialization::CompactCacheAllocatorManagerObject>::fields_ids = { {
  1,
}};
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<protocol::TType, 1> TStructDataStorage<::facebook::cachelib::serialization::CompactCacheAllocatorManagerObject>::fields_types = { {
  apache::thrift::protocol::TType::T_MAP,
}};
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<int, 1> TStructDataStorage<::facebook::cachelib::serialization::CompactCacheAllocatorManagerObject>::isset_indexes = { {
  -1,
}};

THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::string_view TStructDataStorage<::facebook::cachelib::serialization::MMLruConfig>::name = "MMLruConfig";
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<std::string_view, 6> TStructDataStorage<::facebook::cachelib::serialization::MMLruConfig>::fields_names = { {
  "lruRefreshTime"sv,
  "updateOnWrite"sv,
  "lruInsertionPointSpec"sv,
  "updateOnRead"sv,
  "tryLockUpdate"sv,
  "lruRefreshRatio"sv,
}};
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<int16_t, 6> TStructDataStorage<::facebook::cachelib::serialization::MMLruConfig>::fields_ids = { {
  1,
  2,
  3,
  4,
  5,
  6,
}};
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<protocol::TType, 6> TStructDataStorage<::facebook::cachelib::serialization::MMLruConfig>::fields_types = { {
  apache::thrift::protocol::TType::T_I32,
  apache::thrift::protocol::TType::T_BOOL,
  apache::thrift::protocol::TType::T_I32,
  apache::thrift::protocol::TType::T_BOOL,
  apache::thrift::protocol::TType::T_BOOL,
  apache::thrift::protocol::TType::T_DOUBLE,
}};
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<int, 6> TStructDataStorage<::facebook::cachelib::serialization::MMLruConfig>::isset_indexes = { {
  -1,
  -1,
  -1,
  0,
  1,
  2,
}};

THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::string_view TStructDataStorage<::facebook::cachelib::serialization::MMLruObject>::name = "MMLruObject";
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<std::string_view, 6> TStructDataStorage<::facebook::cachelib::serialization::MMLruObject>::fields_names = { {
  "config"sv,
  "evictions"sv,
  "insertionPoint"sv,
  "tailSize"sv,
  "lru"sv,
  "compressedInsertionPoint"sv,
}};
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<int16_t, 6> TStructDataStorage<::facebook::cachelib::serialization::MMLruObject>::fields_ids = { {
  1,
  5,
  6,
  7,
  8,
  9,
}};
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<protocol::TType, 6> TStructDataStorage<::facebook::cachelib::serialization::MMLruObject>::fields_types = { {
  apache::thrift::protocol::TType::T_STRUCT,
  apache::thrift::protocol::TType::T_I64,
  apache::thrift::protocol::TType::T_I64,
  apache::thrift::protocol::TType::T_I64,
  apache::thrift::protocol::TType::T_STRUCT,
  apache::thrift::protocol::TType::T_I64,
}};
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<int, 6> TStructDataStorage<::facebook::cachelib::serialization::MMLruObject>::isset_indexes = { {
  -1,
  0,
  -1,
  -1,
  -1,
  -1,
}};

THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::string_view TStructDataStorage<::facebook::cachelib::serialization::MMLruCollection>::name = "MMLruCollection";
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<std::string_view, 1> TStructDataStorage<::facebook::cachelib::serialization::MMLruCollection>::fields_names = { {
  "pools"sv,
}};
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<int16_t, 1> TStructDataStorage<::facebook::cachelib::serialization::MMLruCollection>::fields_ids = { {
  1,
}};
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<protocol::TType, 1> TStructDataStorage<::facebook::cachelib::serialization::MMLruCollection>::fields_types = { {
  apache::thrift::protocol::TType::T_MAP,
}};
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<int, 1> TStructDataStorage<::facebook::cachelib::serialization::MMLruCollection>::isset_indexes = { {
  -1,
}};

THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::string_view TStructDataStorage<::facebook::cachelib::serialization::MM2QConfig>::name = "MM2QConfig";
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<std::string_view, 8> TStructDataStorage<::facebook::cachelib::serialization::MM2QConfig>::fields_names = { {
  "lruRefreshTime"sv,
  "updateOnWrite"sv,
  "hotSizePercent"sv,
  "coldSizePercent"sv,
  "updateOnRead"sv,
  "tryLockUpdate"sv,
  "rebalanceOnRecordAccess"sv,
  "lruRefreshRatio"sv,
}};
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<int16_t, 8> TStructDataStorage<::facebook::cachelib::serialization::MM2QConfig>::fields_ids = { {
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
}};
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<protocol::TType, 8> TStructDataStorage<::facebook::cachelib::serialization::MM2QConfig>::fields_types = { {
  apache::thrift::protocol::TType::T_I32,
  apache::thrift::protocol::TType::T_BOOL,
  apache::thrift::protocol::TType::T_I32,
  apache::thrift::protocol::TType::T_I32,
  apache::thrift::protocol::TType::T_BOOL,
  apache::thrift::protocol::TType::T_BOOL,
  apache::thrift::protocol::TType::T_BOOL,
  apache::thrift::protocol::TType::T_DOUBLE,
}};
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<int, 8> TStructDataStorage<::facebook::cachelib::serialization::MM2QConfig>::isset_indexes = { {
  -1,
  -1,
  -1,
  -1,
  0,
  1,
  2,
  3,
}};

THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::string_view TStructDataStorage<::facebook::cachelib::serialization::MM2QObject>::name = "MM2QObject";
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<std::string_view, 4> TStructDataStorage<::facebook::cachelib::serialization::MM2QObject>::fields_names = { {
  "config"sv,
  "tailTrackingEnabled"sv,
  "evictions"sv,
  "lrus"sv,
}};
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<int16_t, 4> TStructDataStorage<::facebook::cachelib::serialization::MM2QObject>::fields_ids = { {
  1,
  13,
  11,
  12,
}};
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<protocol::TType, 4> TStructDataStorage<::facebook::cachelib::serialization::MM2QObject>::fields_types = { {
  apache::thrift::protocol::TType::T_STRUCT,
  apache::thrift::protocol::TType::T_BOOL,
  apache::thrift::protocol::TType::T_I64,
  apache::thrift::protocol::TType::T_STRUCT,
}};
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<int, 4> TStructDataStorage<::facebook::cachelib::serialization::MM2QObject>::isset_indexes = { {
  -1,
  0,
  1,
  -1,
}};

THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::string_view TStructDataStorage<::facebook::cachelib::serialization::MM2QCollection>::name = "MM2QCollection";
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<std::string_view, 1> TStructDataStorage<::facebook::cachelib::serialization::MM2QCollection>::fields_names = { {
  "pools"sv,
}};
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<int16_t, 1> TStructDataStorage<::facebook::cachelib::serialization::MM2QCollection>::fields_ids = { {
  1,
}};
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<protocol::TType, 1> TStructDataStorage<::facebook::cachelib::serialization::MM2QCollection>::fields_types = { {
  apache::thrift::protocol::TType::T_MAP,
}};
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<int, 1> TStructDataStorage<::facebook::cachelib::serialization::MM2QCollection>::isset_indexes = { {
  -1,
}};

THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::string_view TStructDataStorage<::facebook::cachelib::serialization::MMTinyLFUConfig>::name = "MMTinyLFUConfig";
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<std::string_view, 11> TStructDataStorage<::facebook::cachelib::serialization::MMTinyLFUConfig>::fields_names = { {
  "lruRefreshTime"sv,
  "updateOnWrite"sv,
  "windowToCacheSizeRatio"sv,
  "tinySizePercent"sv,
  "updateOnRead"sv,
  "tryLockUpdate"sv,
  "lruRefreshRatio"sv,
  "mmReconfigureIntervalSecs"sv,
  "newcomerWinsOnTie"sv,
  "protectionFreq_"sv,
  "protectionSegmentSizePct"sv,
}};
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<int16_t, 11> TStructDataStorage<::facebook::cachelib::serialization::MMTinyLFUConfig>::fields_ids = { {
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
}};
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<protocol::TType, 11> TStructDataStorage<::facebook::cachelib::serialization::MMTinyLFUConfig>::fields_types = { {
  apache::thrift::protocol::TType::T_I32,
  apache::thrift::protocol::TType::T_BOOL,
  apache::thrift::protocol::TType::T_I32,
  apache::thrift::protocol::TType::T_I32,
  apache::thrift::protocol::TType::T_BOOL,
  apache::thrift::protocol::TType::T_BOOL,
  apache::thrift::protocol::TType::T_DOUBLE,
  apache::thrift::protocol::TType::T_I32,
  apache::thrift::protocol::TType::T_BOOL,
  apache::thrift::protocol::TType::T_I32,
  apache::thrift::protocol::TType::T_I32,
}};
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<int, 11> TStructDataStorage<::facebook::cachelib::serialization::MMTinyLFUConfig>::isset_indexes = { {
  -1,
  -1,
  -1,
  -1,
  0,
  1,
  2,
  3,
  4,
  5,
  6,
}};

THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::string_view TStructDataStorage<::facebook::cachelib::serialization::MMTinyLFUObject>::name = "MMTinyLFUObject";
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<std::string_view, 3> TStructDataStorage<::facebook::cachelib::serialization::MMTinyLFUObject>::fields_names = { {
  "config"sv,
  "evictions"sv,
  "lrus"sv,
}};
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<int16_t, 3> TStructDataStorage<::facebook::cachelib::serialization::MMTinyLFUObject>::fields_ids = { {
  1,
  2,
  3,
}};
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<protocol::TType, 3> TStructDataStorage<::facebook::cachelib::serialization::MMTinyLFUObject>::fields_types = { {
  apache::thrift::protocol::TType::T_STRUCT,
  apache::thrift::protocol::TType::T_I64,
  apache::thrift::protocol::TType::T_STRUCT,
}};
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<int, 3> TStructDataStorage<::facebook::cachelib::serialization::MMTinyLFUObject>::isset_indexes = { {
  -1,
  0,
  -1,
}};

THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::string_view TStructDataStorage<::facebook::cachelib::serialization::MMTinyLFUCollection>::name = "MMTinyLFUCollection";
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<std::string_view, 1> TStructDataStorage<::facebook::cachelib::serialization::MMTinyLFUCollection>::fields_names = { {
  "pools"sv,
}};
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<int16_t, 1> TStructDataStorage<::facebook::cachelib::serialization::MMTinyLFUCollection>::fields_ids = { {
  1,
}};
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<protocol::TType, 1> TStructDataStorage<::facebook::cachelib::serialization::MMTinyLFUCollection>::fields_types = { {
  apache::thrift::protocol::TType::T_MAP,
}};
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<int, 1> TStructDataStorage<::facebook::cachelib::serialization::MMTinyLFUCollection>::isset_indexes = { {
  -1,
}};

THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::string_view TStructDataStorage<::facebook::cachelib::serialization::ChainedHashTableObject>::name = "ChainedHashTableObject";
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<std::string_view, 4> TStructDataStorage<::facebook::cachelib::serialization::ChainedHashTableObject>::fields_names = { {
  "bucketsPower"sv,
  "locksPower"sv,
  "numKeys"sv,
  "hasherMagicId"sv,
}};
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<int16_t, 4> TStructDataStorage<::facebook::cachelib::serialization::ChainedHashTableObject>::fields_ids = { {
  1,
  2,
  3,
  4,
}};
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<protocol::TType, 4> TStructDataStorage<::facebook::cachelib::serialization::ChainedHashTableObject>::fields_types = { {
  apache::thrift::protocol::TType::T_I32,
  apache::thrift::protocol::TType::T_I32,
  apache::thrift::protocol::TType::T_I64,
  apache::thrift::protocol::TType::T_I32,
}};
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<int, 4> TStructDataStorage<::facebook::cachelib::serialization::ChainedHashTableObject>::isset_indexes = { {
  -1,
  -1,
  0,
  1,
}};

THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::string_view TStructDataStorage<::facebook::cachelib::serialization::MMTTLBucketObject>::name = "MMTTLBucketObject";
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<std::string_view, 3> TStructDataStorage<::facebook::cachelib::serialization::MMTTLBucketObject>::fields_names = { {
  "expirationTime"sv,
  "creationTime"sv,
  "dList"sv,
}};
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<int16_t, 3> TStructDataStorage<::facebook::cachelib::serialization::MMTTLBucketObject>::fields_ids = { {
  4,
  5,
  6,
}};
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<protocol::TType, 3> TStructDataStorage<::facebook::cachelib::serialization::MMTTLBucketObject>::fields_types = { {
  apache::thrift::protocol::TType::T_I64,
  apache::thrift::protocol::TType::T_I64,
  apache::thrift::protocol::TType::T_STRUCT,
}};
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<int, 3> TStructDataStorage<::facebook::cachelib::serialization::MMTTLBucketObject>::isset_indexes = { {
  0,
  1,
  -1,
}};

THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::string_view TStructDataStorage<::facebook::cachelib::serialization::TTLBucketCollection>::name = "TTLBucketCollection";
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<std::string_view, 4> TStructDataStorage<::facebook::cachelib::serialization::TTLBucketCollection>::fields_names = { {
  "buckets"sv,
  "minEpoch"sv,
  "maxTTL"sv,
  "interval"sv,
}};
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<int16_t, 4> TStructDataStorage<::facebook::cachelib::serialization::TTLBucketCollection>::fields_ids = { {
  1,
  2,
  3,
  4,
}};
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<protocol::TType, 4> TStructDataStorage<::facebook::cachelib::serialization::TTLBucketCollection>::fields_types = { {
  apache::thrift::protocol::TType::T_MAP,
  apache::thrift::protocol::TType::T_I64,
  apache::thrift::protocol::TType::T_I64,
  apache::thrift::protocol::TType::T_I64,
}};
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<int, 4> TStructDataStorage<::facebook::cachelib::serialization::TTLBucketCollection>::isset_indexes = { {
  -1,
  0,
  1,
  2,
}};

namespace detail {

::folly::Range<const ::std::string_view*> TSchemaAssociation<::facebook::cachelib::serialization::CacheAllocatorMetadata, false>::bundle() {
    return ::facebook::cachelib::serialization::objects_constants::_fbthrift_schema_c016a6d09f3a05b3_includes();
}

::folly::Range<const ::std::string_view*> TSchemaAssociation<::facebook::cachelib::serialization::NvmCacheMetadata, false>::bundle() {
    return ::facebook::cachelib::serialization::objects_constants::_fbthrift_schema_c016a6d09f3a05b3_includes();
}

::folly::Range<const ::std::string_view*> TSchemaAssociation<::facebook::cachelib::serialization::CompactCacheMetadataObject, false>::bundle() {
    return ::facebook::cachelib::serialization::objects_constants::_fbthrift_schema_c016a6d09f3a05b3_includes();
}

::folly::Range<const ::std::string_view*> TSchemaAssociation<::facebook::cachelib::serialization::CompactCacheAllocatorObject, false>::bundle() {
    return ::facebook::cachelib::serialization::objects_constants::_fbthrift_schema_c016a6d09f3a05b3_includes();
}

::folly::Range<const ::std::string_view*> TSchemaAssociation<::facebook::cachelib::serialization::CompactCacheAllocatorManagerObject, false>::bundle() {
    return ::facebook::cachelib::serialization::objects_constants::_fbthrift_schema_c016a6d09f3a05b3_includes();
}

::folly::Range<const ::std::string_view*> TSchemaAssociation<::facebook::cachelib::serialization::MMLruConfig, false>::bundle() {
    return ::facebook::cachelib::serialization::objects_constants::_fbthrift_schema_c016a6d09f3a05b3_includes();
}

::folly::Range<const ::std::string_view*> TSchemaAssociation<::facebook::cachelib::serialization::MMLruObject, false>::bundle() {
    return ::facebook::cachelib::serialization::objects_constants::_fbthrift_schema_c016a6d09f3a05b3_includes();
}

::folly::Range<const ::std::string_view*> TSchemaAssociation<::facebook::cachelib::serialization::MMLruCollection, false>::bundle() {
    return ::facebook::cachelib::serialization::objects_constants::_fbthrift_schema_c016a6d09f3a05b3_includes();
}

::folly::Range<const ::std::string_view*> TSchemaAssociation<::facebook::cachelib::serialization::MM2QConfig, false>::bundle() {
    return ::facebook::cachelib::serialization::objects_constants::_fbthrift_schema_c016a6d09f3a05b3_includes();
}

::folly::Range<const ::std::string_view*> TSchemaAssociation<::facebook::cachelib::serialization::MM2QObject, false>::bundle() {
    return ::facebook::cachelib::serialization::objects_constants::_fbthrift_schema_c016a6d09f3a05b3_includes();
}

::folly::Range<const ::std::string_view*> TSchemaAssociation<::facebook::cachelib::serialization::MM2QCollection, false>::bundle() {
    return ::facebook::cachelib::serialization::objects_constants::_fbthrift_schema_c016a6d09f3a05b3_includes();
}

::folly::Range<const ::std::string_view*> TSchemaAssociation<::facebook::cachelib::serialization::MMTinyLFUConfig, false>::bundle() {
    return ::facebook::cachelib::serialization::objects_constants::_fbthrift_schema_c016a6d09f3a05b3_includes();
}

::folly::Range<const ::std::string_view*> TSchemaAssociation<::facebook::cachelib::serialization::MMTinyLFUObject, false>::bundle() {
    return ::facebook::cachelib::serialization::objects_constants::_fbthrift_schema_c016a6d09f3a05b3_includes();
}

::folly::Range<const ::std::string_view*> TSchemaAssociation<::facebook::cachelib::serialization::MMTinyLFUCollection, false>::bundle() {
    return ::facebook::cachelib::serialization::objects_constants::_fbthrift_schema_c016a6d09f3a05b3_includes();
}

::folly::Range<const ::std::string_view*> TSchemaAssociation<::facebook::cachelib::serialization::ChainedHashTableObject, false>::bundle() {
    return ::facebook::cachelib::serialization::objects_constants::_fbthrift_schema_c016a6d09f3a05b3_includes();
}

::folly::Range<const ::std::string_view*> TSchemaAssociation<::facebook::cachelib::serialization::MMTTLBucketObject, false>::bundle() {
    return ::facebook::cachelib::serialization::objects_constants::_fbthrift_schema_c016a6d09f3a05b3_includes();
}

::folly::Range<const ::std::string_view*> TSchemaAssociation<::facebook::cachelib::serialization::TTLBucketCollection, false>::bundle() {
    return ::facebook::cachelib::serialization::objects_constants::_fbthrift_schema_c016a6d09f3a05b3_includes();
}

} // namespace detail
} // namespace apache::thrift
