/**
 * Autogenerated by Thrift for cachelib/allocator/serialize/objects.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated @nocommit
 */
#pragma once

// BEGIN forward_declare
namespace facebook::cachelib::serialization {
class CacheAllocatorMetadata;
class NvmCacheMetadata;
class CompactCacheMetadataObject;
class CompactCacheAllocatorObject;
class CompactCacheAllocatorManagerObject;
class MMLruConfig;
class MMLruObject;
class MMLruCollection;
class MM2QConfig;
class MM2QObject;
class MM2QCollection;
class MMTinyLFUConfig;
class MMTinyLFUObject;
class MMTinyLFUCollection;
class ChainedHashTableObject;
class MMTTLBucketObject;
class TTLBucketCollection;
} // namespace facebook::cachelib::serialization
// END forward_declare
