/**
 * Autogenerated by Thrift for cachelib/allocator/serialize/objects.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated @nocommit
 */
#include "cachelib/allocator/serialize/gen-cpp2/objects_types_custom_protocol.h"

namespace facebook::cachelib::serialization {

template void CacheAllocatorMetadata::readNoXfer<>(apache::thrift::BinaryProtocolReader*);
template uint32_t CacheAllocatorMetadata::write<>(apache::thrift::BinaryProtocolWriter*) const;
template uint32_t CacheAllocatorMetadata::serializedSize<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t CacheAllocatorMetadata::serializedSizeZC<>(apache::thrift::BinaryProtocolWriter const*) const;

template void NvmCacheMetadata::readNoXfer<>(apache::thrift::BinaryProtocolReader*);
template uint32_t NvmCacheMetadata::write<>(apache::thrift::BinaryProtocolWriter*) const;
template uint32_t NvmCacheMetadata::serializedSize<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t NvmCacheMetadata::serializedSizeZC<>(apache::thrift::BinaryProtocolWriter const*) const;

template void CompactCacheMetadataObject::readNoXfer<>(apache::thrift::BinaryProtocolReader*);
template uint32_t CompactCacheMetadataObject::write<>(apache::thrift::BinaryProtocolWriter*) const;
template uint32_t CompactCacheMetadataObject::serializedSize<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t CompactCacheMetadataObject::serializedSizeZC<>(apache::thrift::BinaryProtocolWriter const*) const;

template void CompactCacheAllocatorObject::readNoXfer<>(apache::thrift::BinaryProtocolReader*);
template uint32_t CompactCacheAllocatorObject::write<>(apache::thrift::BinaryProtocolWriter*) const;
template uint32_t CompactCacheAllocatorObject::serializedSize<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t CompactCacheAllocatorObject::serializedSizeZC<>(apache::thrift::BinaryProtocolWriter const*) const;

template void CompactCacheAllocatorManagerObject::readNoXfer<>(apache::thrift::BinaryProtocolReader*);
template uint32_t CompactCacheAllocatorManagerObject::write<>(apache::thrift::BinaryProtocolWriter*) const;
template uint32_t CompactCacheAllocatorManagerObject::serializedSize<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t CompactCacheAllocatorManagerObject::serializedSizeZC<>(apache::thrift::BinaryProtocolWriter const*) const;

template void MMLruConfig::readNoXfer<>(apache::thrift::BinaryProtocolReader*);
template uint32_t MMLruConfig::write<>(apache::thrift::BinaryProtocolWriter*) const;
template uint32_t MMLruConfig::serializedSize<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t MMLruConfig::serializedSizeZC<>(apache::thrift::BinaryProtocolWriter const*) const;

template void MMLruObject::readNoXfer<>(apache::thrift::BinaryProtocolReader*);
template uint32_t MMLruObject::write<>(apache::thrift::BinaryProtocolWriter*) const;
template uint32_t MMLruObject::serializedSize<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t MMLruObject::serializedSizeZC<>(apache::thrift::BinaryProtocolWriter const*) const;

template void MMLruCollection::readNoXfer<>(apache::thrift::BinaryProtocolReader*);
template uint32_t MMLruCollection::write<>(apache::thrift::BinaryProtocolWriter*) const;
template uint32_t MMLruCollection::serializedSize<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t MMLruCollection::serializedSizeZC<>(apache::thrift::BinaryProtocolWriter const*) const;

template void MM2QConfig::readNoXfer<>(apache::thrift::BinaryProtocolReader*);
template uint32_t MM2QConfig::write<>(apache::thrift::BinaryProtocolWriter*) const;
template uint32_t MM2QConfig::serializedSize<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t MM2QConfig::serializedSizeZC<>(apache::thrift::BinaryProtocolWriter const*) const;

template void MM2QObject::readNoXfer<>(apache::thrift::BinaryProtocolReader*);
template uint32_t MM2QObject::write<>(apache::thrift::BinaryProtocolWriter*) const;
template uint32_t MM2QObject::serializedSize<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t MM2QObject::serializedSizeZC<>(apache::thrift::BinaryProtocolWriter const*) const;

template void MM2QCollection::readNoXfer<>(apache::thrift::BinaryProtocolReader*);
template uint32_t MM2QCollection::write<>(apache::thrift::BinaryProtocolWriter*) const;
template uint32_t MM2QCollection::serializedSize<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t MM2QCollection::serializedSizeZC<>(apache::thrift::BinaryProtocolWriter const*) const;

template void MMTinyLFUConfig::readNoXfer<>(apache::thrift::BinaryProtocolReader*);
template uint32_t MMTinyLFUConfig::write<>(apache::thrift::BinaryProtocolWriter*) const;
template uint32_t MMTinyLFUConfig::serializedSize<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t MMTinyLFUConfig::serializedSizeZC<>(apache::thrift::BinaryProtocolWriter const*) const;

template void MMTinyLFUObject::readNoXfer<>(apache::thrift::BinaryProtocolReader*);
template uint32_t MMTinyLFUObject::write<>(apache::thrift::BinaryProtocolWriter*) const;
template uint32_t MMTinyLFUObject::serializedSize<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t MMTinyLFUObject::serializedSizeZC<>(apache::thrift::BinaryProtocolWriter const*) const;

template void MMTinyLFUCollection::readNoXfer<>(apache::thrift::BinaryProtocolReader*);
template uint32_t MMTinyLFUCollection::write<>(apache::thrift::BinaryProtocolWriter*) const;
template uint32_t MMTinyLFUCollection::serializedSize<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t MMTinyLFUCollection::serializedSizeZC<>(apache::thrift::BinaryProtocolWriter const*) const;

template void ChainedHashTableObject::readNoXfer<>(apache::thrift::BinaryProtocolReader*);
template uint32_t ChainedHashTableObject::write<>(apache::thrift::BinaryProtocolWriter*) const;
template uint32_t ChainedHashTableObject::serializedSize<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t ChainedHashTableObject::serializedSizeZC<>(apache::thrift::BinaryProtocolWriter const*) const;

template void MMTTLBucketObject::readNoXfer<>(apache::thrift::BinaryProtocolReader*);
template uint32_t MMTTLBucketObject::write<>(apache::thrift::BinaryProtocolWriter*) const;
template uint32_t MMTTLBucketObject::serializedSize<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t MMTTLBucketObject::serializedSizeZC<>(apache::thrift::BinaryProtocolWriter const*) const;

template void TTLBucketCollection::readNoXfer<>(apache::thrift::BinaryProtocolReader*);
template uint32_t TTLBucketCollection::write<>(apache::thrift::BinaryProtocolWriter*) const;
template uint32_t TTLBucketCollection::serializedSize<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t TTLBucketCollection::serializedSizeZC<>(apache::thrift::BinaryProtocolWriter const*) const;

} // namespace facebook::cachelib::serialization
