/**
 * Autogenerated by Thrift for cachelib/allocator/serialize/objects.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated @nocommit
 */
#pragma once

#include <thrift/lib/cpp2/gen/module_constants_h.h>

#include "cachelib/allocator/serialize/gen-cpp2/objects_types.h"

namespace facebook::cachelib::serialization {
/** Glean {"file": "cachelib/allocator/serialize/objects.thrift"} */
namespace objects_constants {

  FOLLY_EXPORT ::std::string_view _fbthrift_schema_c016a6d09f3a05b3();
  FOLLY_EXPORT ::folly::Range<const ::std::string_view*> _fbthrift_schema_c016a6d09f3a05b3_includes();
  FOLLY_EXPORT ::folly::Range<const ::std::string_view*> _fbthrift_schema_c016a6d09f3a05b3_uris();

} // namespace objects_constants
} // namespace facebook::cachelib::serialization
