/**
 * Autogenerated by Thrift for test_objects.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated @nocommit
 */
#include "test_objects_types_custom_protocol.h"
#include "test_objects_data.h"

#include <thrift/lib/cpp2/gen/module_types_cpp.h>


namespace apache {
namespace thrift {
namespace detail {

void TccStructTraits<::facebook::cachelib::test_serialization::SListObjectNoCompressedTail>::translateFieldName(
    std::string_view _fname,
    int16_t& fid,
    apache::thrift::protocol::TType& _ftype) noexcept {
  using data = apache::thrift::TStructDataStorage<::facebook::cachelib::test_serialization::SListObjectNoCompressedTail>;
  static const st::translate_field_name_table table{
      data::fields_size,
      data::fields_names.data(),
      data::fields_ids.data(),
      data::fields_types.data()};
  st::translate_field_name(_fname, fid, _ftype, table);
}

} // namespace detail
} // namespace thrift
} // namespace apache

namespace facebook::cachelib::test_serialization {




} // namespace facebook::cachelib::test_serialization
