/**
 * Autogenerated by Thrift for test_objects.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated @nocommit
 */
#pragma once

// BEGIN forward_declare
namespace facebook::cachelib::test_serialization {
class SListObjectNoCompressedTail;
} // namespace facebook::cachelib::test_serialization
// END forward_declare
