/**
 * Autogenerated by Thrift for test_objects.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated @nocommit
 */
#pragma once

#include "test_objects_metadata.h"
#include <thrift/lib/cpp2/visitation/for_each.h>

namespace apache {
namespace thrift {
namespace detail {

template <>
struct ForEachField<::facebook::cachelib::test_serialization::SListObjectNoCompressedTail> {
  template <typename F, typename... T>
  void operator()([[maybe_unused]] F&& f, [[maybe_unused]] T&&... t) const {
    f(0, static_cast<T&&>(t).size_ref()...);
    f(1, static_cast<T&&>(t).compressedHead_ref()...);
  }
};
} // namespace detail
} // namespace thrift
} // namespace apache
