/**
 * Autogenerated by Thrift for test_objects.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated @nocommit
 */
#include "test_objects_types_custom_protocol.h"

namespace facebook::cachelib::test_serialization {

template void SListObjectNoCompressedTail::readNoXfer<>(apache::thrift::BinaryProtocolReader*);
template uint32_t SListObjectNoCompressedTail::write<>(apache::thrift::BinaryProtocolWriter*) const;
template uint32_t SListObjectNoCompressedTail::serializedSize<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t SListObjectNoCompressedTail::serializedSizeZC<>(apache::thrift::BinaryProtocolWriter const*) const;

} // namespace facebook::cachelib::test_serialization
