/**
 * Autogenerated by Thrift for test_objects.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated @nocommit
 */
#include "test_objects_layouts.h"

namespace apache { namespace thrift { namespace frozen {

FROZEN_CTOR(::facebook::cachelib::test_serialization::SListObjectNoCompressedTail,
  FROZEN_CTOR_FIELD_REQ(size, 2)
  FROZEN_CTOR_FIELD_REQ(compressedHead, 3))
FROZEN_MAXIMIZE(::facebook::cachelib::test_serialization::SListObjectNoCompressedTail,
  FROZEN_MAXIMIZE_FIELD(size);
  FROZEN_MAXIMIZE_FIELD(compressedHead);
)
FROZEN_LAYOUT(::facebook::cachelib::test_serialization::SListObjectNoCompressedTail,
  FROZEN_LAYOUT_FIELD_REQ(size)
  FROZEN_LAYOUT_FIELD_REQ(compressedHead))
FROZEN_FREEZE(::facebook::cachelib::test_serialization::SListObjectNoCompressedTail,
  FROZEN_FREEZE_FIELD_REQ(size)
  FROZEN_FREEZE_FIELD_REQ(compressedHead))
FROZEN_THAW(::facebook::cachelib::test_serialization::SListObjectNoCompressedTail,
  FROZEN_THAW_FIELD_REQ(size)
  FROZEN_THAW_FIELD_REQ(compressedHead))
FROZEN_DEBUG(::facebook::cachelib::test_serialization::SListObjectNoCompressedTail,
  FROZEN_DEBUG_FIELD(size)
  FROZEN_DEBUG_FIELD(compressedHead))
FROZEN_CLEAR(::facebook::cachelib::test_serialization::SListObjectNoCompressedTail,
  FROZEN_CLEAR_FIELD(size)
  FROZEN_CLEAR_FIELD(compressedHead))


}}} // apache::thrift::frozen
