/**
 * Autogenerated by Thrift for test_objects.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated @nocommit
 */

#include "test_objects_constants.h"

#include <thrift/lib/cpp2/gen/module_constants_cpp.h>


namespace facebook::cachelib::test_serialization {
namespace test_objects_constants {


::std::string_view _fbthrift_schema_dff35e7576fc8814() {
  return "";
}
::folly::Range<const ::std::string_view*> _fbthrift_schema_dff35e7576fc8814_includes() {
  return {};
}
::folly::Range<const ::std::string_view*> _fbthrift_schema_dff35e7576fc8814_uris() {
  return {};
}

} // namespace test_objects_constants
} // namespace facebook::cachelib::test_serialization
