/**
 * Autogenerated by Thrift for test_objects.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated @nocommit
 */

#include "test_objects_data.h"
#include "test_objects_constants.h"

#include <thrift/lib/cpp2/gen/module_data_cpp.h>

namespace apache::thrift {

THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::string_view TStructDataStorage<::facebook::cachelib::test_serialization::SListObjectNoCompressedTail>::name = "SListObjectNoCompressedTail";
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<std::string_view, 2> TStructDataStorage<::facebook::cachelib::test_serialization::SListObjectNoCompressedTail>::fields_names = { {
  "size"sv,
  "compressedHead"sv,
}};
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<int16_t, 2> TStructDataStorage<::facebook::cachelib::test_serialization::SListObjectNoCompressedTail>::fields_ids = { {
  2,
  3,
}};
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<protocol::TType, 2> TStructDataStorage<::facebook::cachelib::test_serialization::SListObjectNoCompressedTail>::fields_types = { {
  apache::thrift::protocol::TType::T_I64,
  apache::thrift::protocol::TType::T_I64,
}};
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<int, 2> TStructDataStorage<::facebook::cachelib::test_serialization::SListObjectNoCompressedTail>::isset_indexes = { {
  -1,
  -1,
}};

namespace detail {

::folly::Range<const ::std::string_view*> TSchemaAssociation<::facebook::cachelib::test_serialization::SListObjectNoCompressedTail, false>::bundle() {
    return ::facebook::cachelib::test_serialization::test_objects_constants::_fbthrift_schema_dff35e7576fc8814_includes();
}

} // namespace detail
} // namespace apache::thrift
