/**
 * Autogenerated by Thrift for cachelib/allocator/memory/serialize/objects.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated @nocommit
 */
#include "cachelib/allocator/memory/serialize/gen-cpp2/objects_types.tcc"
#include "cachelib/allocator/memory/serialize/gen-cpp2/objects_constants.h"
#include "cachelib/allocator/memory/serialize/gen-cpp2/objects_data.h"

#include <thrift/lib/cpp2/gen/module_types_cpp.h>

[[maybe_unused]] static constexpr std::string_view kModuleName = "objects";



namespace facebook::cachelib::serialization {

std::string_view SlabAllocatorObject::__fbthrift_get_field_name(::apache::thrift::FieldOrdinal ord) {
  if (ord == ::apache::thrift::FieldOrdinal{0}) { return {}; }
  return apache::thrift::TStructDataStorage<SlabAllocatorObject>::fields_names[folly::to_underlying(ord) - 1];
}
std::string_view SlabAllocatorObject::__fbthrift_get_class_name() {
  return apache::thrift::TStructDataStorage<SlabAllocatorObject>::name;
}

SlabAllocatorObject::SlabAllocatorObject(const SlabAllocatorObject&) = default;
SlabAllocatorObject& SlabAllocatorObject::operator=(const SlabAllocatorObject&) = default;
SlabAllocatorObject::SlabAllocatorObject() :
    __fbthrift_field_memorySize(),
    __fbthrift_field_canAllocate(),
    __fbthrift_field_slabSize(),
    __fbthrift_field_minAllocSize(),
    __fbthrift_field_nextSlabIdx() {
}


SlabAllocatorObject::~SlabAllocatorObject() {}

SlabAllocatorObject::SlabAllocatorObject([[maybe_unused]] SlabAllocatorObject&& other) noexcept :
    __fbthrift_field_memorySize(std::move(other.__fbthrift_field_memorySize)),
    __fbthrift_field_canAllocate(std::move(other.__fbthrift_field_canAllocate)),
    __fbthrift_field_memoryPoolSize(std::move(other.__fbthrift_field_memoryPoolSize)),
    __fbthrift_field_slabSize(std::move(other.__fbthrift_field_slabSize)),
    __fbthrift_field_minAllocSize(std::move(other.__fbthrift_field_minAllocSize)),
    __fbthrift_field_nextSlabIdx(std::move(other.__fbthrift_field_nextSlabIdx)),
    __fbthrift_field_freeSlabIdxs(std::move(other.__fbthrift_field_freeSlabIdxs)),
    __fbthrift_field_advisedSlabIdxs(std::move(other.__fbthrift_field_advisedSlabIdxs)),
    __isset(other.__isset) {
}

SlabAllocatorObject& SlabAllocatorObject::operator=([[maybe_unused]] SlabAllocatorObject&& other) noexcept {
    this->__fbthrift_field_memorySize = std::move(other.__fbthrift_field_memorySize);
    this->__fbthrift_field_canAllocate = std::move(other.__fbthrift_field_canAllocate);
    this->__fbthrift_field_memoryPoolSize = std::move(other.__fbthrift_field_memoryPoolSize);
    this->__fbthrift_field_slabSize = std::move(other.__fbthrift_field_slabSize);
    this->__fbthrift_field_minAllocSize = std::move(other.__fbthrift_field_minAllocSize);
    this->__fbthrift_field_nextSlabIdx = std::move(other.__fbthrift_field_nextSlabIdx);
    this->__fbthrift_field_freeSlabIdxs = std::move(other.__fbthrift_field_freeSlabIdxs);
    this->__fbthrift_field_advisedSlabIdxs = std::move(other.__fbthrift_field_advisedSlabIdxs);
    __isset = other.__isset;
    return *this;
}


SlabAllocatorObject::SlabAllocatorObject(apache::thrift::FragileConstructor, ::std::int64_t memorySize__arg, bool canAllocate__arg, ::std::map<::std::int8_t, ::std::int64_t> memoryPoolSize__arg, ::std::int64_t slabSize__arg, ::std::int64_t minAllocSize__arg, ::std::int32_t nextSlabIdx__arg, ::std::vector<::std::int32_t> freeSlabIdxs__arg, ::std::vector<::std::int32_t> advisedSlabIdxs__arg) :
    __fbthrift_field_memorySize(std::move(memorySize__arg)),
    __fbthrift_field_canAllocate(std::move(canAllocate__arg)),
    __fbthrift_field_memoryPoolSize(std::move(memoryPoolSize__arg)),
    __fbthrift_field_slabSize(std::move(slabSize__arg)),
    __fbthrift_field_minAllocSize(std::move(minAllocSize__arg)),
    __fbthrift_field_nextSlabIdx(std::move(nextSlabIdx__arg)),
    __fbthrift_field_freeSlabIdxs(std::move(freeSlabIdxs__arg)),
    __fbthrift_field_advisedSlabIdxs(std::move(advisedSlabIdxs__arg)) { 
  __isset.set(folly::index_constant<0>(), true);
}

void SlabAllocatorObject::__fbthrift_clear() {
  // clear all fields
  this->__fbthrift_field_memorySize = ::std::int64_t();
  this->__fbthrift_field_canAllocate = bool();
  this->__fbthrift_field_memoryPoolSize.clear();
  this->__fbthrift_field_slabSize = ::std::int64_t();
  this->__fbthrift_field_minAllocSize = ::std::int64_t();
  this->__fbthrift_field_nextSlabIdx = ::std::int32_t();
  this->__fbthrift_field_freeSlabIdxs.clear();
  this->__fbthrift_field_advisedSlabIdxs.clear();
  __isset = {};
}

bool SlabAllocatorObject::__fbthrift_is_empty() const {
  return false;
}

bool SlabAllocatorObject::operator==([[maybe_unused]] const SlabAllocatorObject& rhs) const {
  return ::apache::thrift::op::detail::StructEquality{}(*this, rhs);
}

bool SlabAllocatorObject::operator<([[maybe_unused]] const SlabAllocatorObject& rhs) const {
  return ::apache::thrift::op::detail::StructLessThan{}(*this, rhs);
}


::std::int64_t SlabAllocatorObject::get_memorySize() const {
  return __fbthrift_field_memorySize;
}

::std::int64_t& SlabAllocatorObject::set_memorySize(::std::int64_t memorySize_) {
  memorySize_ref() = memorySize_;
  return __fbthrift_field_memorySize;
}

bool SlabAllocatorObject::get_canAllocate() const {
  return __fbthrift_field_canAllocate;
}

bool& SlabAllocatorObject::set_canAllocate(bool canAllocate_) {
  canAllocate_ref() = canAllocate_;
  return __fbthrift_field_canAllocate;
}

const ::std::map<::std::int8_t, ::std::int64_t>& SlabAllocatorObject::get_memoryPoolSize() const& {
  return __fbthrift_field_memoryPoolSize;
}

::std::map<::std::int8_t, ::std::int64_t> SlabAllocatorObject::get_memoryPoolSize() && {
  return static_cast<::std::map<::std::int8_t, ::std::int64_t>&&>(__fbthrift_field_memoryPoolSize);
}

::std::int64_t SlabAllocatorObject::get_slabSize() const {
  return __fbthrift_field_slabSize;
}

::std::int64_t& SlabAllocatorObject::set_slabSize(::std::int64_t slabSize_) {
  slabSize_ref() = slabSize_;
  return __fbthrift_field_slabSize;
}

::std::int64_t SlabAllocatorObject::get_minAllocSize() const {
  return __fbthrift_field_minAllocSize;
}

::std::int64_t& SlabAllocatorObject::set_minAllocSize(::std::int64_t minAllocSize_) {
  minAllocSize_ref() = minAllocSize_;
  return __fbthrift_field_minAllocSize;
}

::std::int32_t SlabAllocatorObject::get_nextSlabIdx() const {
  return __fbthrift_field_nextSlabIdx;
}

::std::int32_t& SlabAllocatorObject::set_nextSlabIdx(::std::int32_t nextSlabIdx_) {
  nextSlabIdx_ref() = nextSlabIdx_;
  return __fbthrift_field_nextSlabIdx;
}

const ::std::vector<::std::int32_t>& SlabAllocatorObject::get_freeSlabIdxs() const& {
  return __fbthrift_field_freeSlabIdxs;
}

::std::vector<::std::int32_t> SlabAllocatorObject::get_freeSlabIdxs() && {
  return static_cast<::std::vector<::std::int32_t>&&>(__fbthrift_field_freeSlabIdxs);
}

const ::std::vector<::std::int32_t>& SlabAllocatorObject::get_advisedSlabIdxs() const& {
  return __fbthrift_field_advisedSlabIdxs;
}

::std::vector<::std::int32_t> SlabAllocatorObject::get_advisedSlabIdxs() && {
  return static_cast<::std::vector<::std::int32_t>&&>(__fbthrift_field_advisedSlabIdxs);
}

void swap([[maybe_unused]] SlabAllocatorObject& a, [[maybe_unused]] SlabAllocatorObject& b) {
  using ::std::swap;
  swap(a.__fbthrift_field_memorySize, b.__fbthrift_field_memorySize);
  swap(a.__fbthrift_field_canAllocate, b.__fbthrift_field_canAllocate);
  swap(a.__fbthrift_field_memoryPoolSize, b.__fbthrift_field_memoryPoolSize);
  swap(a.__fbthrift_field_slabSize, b.__fbthrift_field_slabSize);
  swap(a.__fbthrift_field_minAllocSize, b.__fbthrift_field_minAllocSize);
  swap(a.__fbthrift_field_nextSlabIdx, b.__fbthrift_field_nextSlabIdx);
  swap(a.__fbthrift_field_freeSlabIdxs, b.__fbthrift_field_freeSlabIdxs);
  swap(a.__fbthrift_field_advisedSlabIdxs, b.__fbthrift_field_advisedSlabIdxs);
  swap(a.__isset, b.__isset);
}


} // namespace facebook::cachelib::serialization


namespace facebook::cachelib::serialization {

std::string_view AllocationClassObject::__fbthrift_get_field_name(::apache::thrift::FieldOrdinal ord) {
  if (ord == ::apache::thrift::FieldOrdinal{0}) { return {}; }
  return apache::thrift::TStructDataStorage<AllocationClassObject>::fields_names[folly::to_underlying(ord) - 1];
}
std::string_view AllocationClassObject::__fbthrift_get_class_name() {
  return apache::thrift::TStructDataStorage<AllocationClassObject>::name;
}

AllocationClassObject::AllocationClassObject(const AllocationClassObject&) = default;
AllocationClassObject& AllocationClassObject::operator=(const AllocationClassObject&) = default;
AllocationClassObject::AllocationClassObject() :
    __fbthrift_field_classId(),
    __fbthrift_field_allocationSize(),
    __fbthrift_field_currOffset(),
    __fbthrift_field_canAllocate(),
    __fbthrift_field_currSlabIdx() {
}


AllocationClassObject::~AllocationClassObject() {}

AllocationClassObject::AllocationClassObject([[maybe_unused]] AllocationClassObject&& other) noexcept :
    __fbthrift_field_classId(std::move(other.__fbthrift_field_classId)),
    __fbthrift_field_allocationSize(std::move(other.__fbthrift_field_allocationSize)),
    __fbthrift_field_currOffset(std::move(other.__fbthrift_field_currOffset)),
    __fbthrift_field_canAllocate(std::move(other.__fbthrift_field_canAllocate)),
    __fbthrift_field_freedAllocationsObject(std::move(other.__fbthrift_field_freedAllocationsObject)),
    __fbthrift_field_currSlabIdx(std::move(other.__fbthrift_field_currSlabIdx)),
    __fbthrift_field_allocatedSlabIdxs(std::move(other.__fbthrift_field_allocatedSlabIdxs)),
    __fbthrift_field_freeSlabIdxs(std::move(other.__fbthrift_field_freeSlabIdxs)),
    __isset(other.__isset) {
}

AllocationClassObject& AllocationClassObject::operator=([[maybe_unused]] AllocationClassObject&& other) noexcept {
    this->__fbthrift_field_classId = std::move(other.__fbthrift_field_classId);
    this->__fbthrift_field_allocationSize = std::move(other.__fbthrift_field_allocationSize);
    this->__fbthrift_field_currOffset = std::move(other.__fbthrift_field_currOffset);
    this->__fbthrift_field_canAllocate = std::move(other.__fbthrift_field_canAllocate);
    this->__fbthrift_field_freedAllocationsObject = std::move(other.__fbthrift_field_freedAllocationsObject);
    this->__fbthrift_field_currSlabIdx = std::move(other.__fbthrift_field_currSlabIdx);
    this->__fbthrift_field_allocatedSlabIdxs = std::move(other.__fbthrift_field_allocatedSlabIdxs);
    this->__fbthrift_field_freeSlabIdxs = std::move(other.__fbthrift_field_freeSlabIdxs);
    __isset = other.__isset;
    return *this;
}


AllocationClassObject::AllocationClassObject(apache::thrift::FragileConstructor, ::std::int8_t classId__arg, ::std::int64_t allocationSize__arg, ::std::int64_t currOffset__arg, bool canAllocate__arg, ::facebook::cachelib::serialization::SListObject freedAllocationsObject__arg, ::std::int32_t currSlabIdx__arg, ::std::vector<::std::int32_t> allocatedSlabIdxs__arg, ::std::vector<::std::int32_t> freeSlabIdxs__arg) :
    __fbthrift_field_classId(std::move(classId__arg)),
    __fbthrift_field_allocationSize(std::move(allocationSize__arg)),
    __fbthrift_field_currOffset(std::move(currOffset__arg)),
    __fbthrift_field_canAllocate(std::move(canAllocate__arg)),
    __fbthrift_field_freedAllocationsObject(std::move(freedAllocationsObject__arg)),
    __fbthrift_field_currSlabIdx(std::move(currSlabIdx__arg)),
    __fbthrift_field_allocatedSlabIdxs(std::move(allocatedSlabIdxs__arg)),
    __fbthrift_field_freeSlabIdxs(std::move(freeSlabIdxs__arg)) { 
  __isset.set(folly::index_constant<0>(), true);
}

void AllocationClassObject::__fbthrift_clear() {
  // clear all fields
  this->__fbthrift_field_classId = ::std::int8_t();
  this->__fbthrift_field_allocationSize = ::std::int64_t();
  this->__fbthrift_field_currOffset = ::std::int64_t();
  this->__fbthrift_field_canAllocate = bool();
  ::apache::thrift::clear(this->__fbthrift_field_freedAllocationsObject);
  this->__fbthrift_field_currSlabIdx = ::std::int32_t();
  this->__fbthrift_field_allocatedSlabIdxs.clear();
  this->__fbthrift_field_freeSlabIdxs.clear();
  __isset = {};
}

bool AllocationClassObject::__fbthrift_is_empty() const {
  return false;
}

bool AllocationClassObject::operator==([[maybe_unused]] const AllocationClassObject& rhs) const {
  return ::apache::thrift::op::detail::StructEquality{}(*this, rhs);
}

bool AllocationClassObject::operator<([[maybe_unused]] const AllocationClassObject& rhs) const {
  return ::apache::thrift::op::detail::StructLessThan{}(*this, rhs);
}


::std::int8_t AllocationClassObject::get_classId() const {
  return __fbthrift_field_classId;
}

::std::int8_t& AllocationClassObject::set_classId(::std::int8_t classId_) {
  classId_ref() = classId_;
  return __fbthrift_field_classId;
}

::std::int64_t AllocationClassObject::get_allocationSize() const {
  return __fbthrift_field_allocationSize;
}

::std::int64_t& AllocationClassObject::set_allocationSize(::std::int64_t allocationSize_) {
  allocationSize_ref() = allocationSize_;
  return __fbthrift_field_allocationSize;
}

::std::int64_t AllocationClassObject::get_currOffset() const {
  return __fbthrift_field_currOffset;
}

::std::int64_t& AllocationClassObject::set_currOffset(::std::int64_t currOffset_) {
  currOffset_ref() = currOffset_;
  return __fbthrift_field_currOffset;
}

bool AllocationClassObject::get_canAllocate() const {
  return __fbthrift_field_canAllocate;
}

bool& AllocationClassObject::set_canAllocate(bool canAllocate_) {
  canAllocate_ref() = canAllocate_;
  return __fbthrift_field_canAllocate;
}

const ::facebook::cachelib::serialization::SListObject& AllocationClassObject::get_freedAllocationsObject() const& {
  return __fbthrift_field_freedAllocationsObject;
}

::facebook::cachelib::serialization::SListObject AllocationClassObject::get_freedAllocationsObject() && {
  return static_cast<::facebook::cachelib::serialization::SListObject&&>(__fbthrift_field_freedAllocationsObject);
}

::std::int32_t AllocationClassObject::get_currSlabIdx() const {
  return __fbthrift_field_currSlabIdx;
}

::std::int32_t& AllocationClassObject::set_currSlabIdx(::std::int32_t currSlabIdx_) {
  currSlabIdx_ref() = currSlabIdx_;
  return __fbthrift_field_currSlabIdx;
}

const ::std::vector<::std::int32_t>& AllocationClassObject::get_allocatedSlabIdxs() const& {
  return __fbthrift_field_allocatedSlabIdxs;
}

::std::vector<::std::int32_t> AllocationClassObject::get_allocatedSlabIdxs() && {
  return static_cast<::std::vector<::std::int32_t>&&>(__fbthrift_field_allocatedSlabIdxs);
}

const ::std::vector<::std::int32_t>& AllocationClassObject::get_freeSlabIdxs() const& {
  return __fbthrift_field_freeSlabIdxs;
}

::std::vector<::std::int32_t> AllocationClassObject::get_freeSlabIdxs() && {
  return static_cast<::std::vector<::std::int32_t>&&>(__fbthrift_field_freeSlabIdxs);
}

void swap([[maybe_unused]] AllocationClassObject& a, [[maybe_unused]] AllocationClassObject& b) {
  using ::std::swap;
  swap(a.__fbthrift_field_classId, b.__fbthrift_field_classId);
  swap(a.__fbthrift_field_allocationSize, b.__fbthrift_field_allocationSize);
  swap(a.__fbthrift_field_currOffset, b.__fbthrift_field_currOffset);
  swap(a.__fbthrift_field_canAllocate, b.__fbthrift_field_canAllocate);
  swap(a.__fbthrift_field_freedAllocationsObject, b.__fbthrift_field_freedAllocationsObject);
  swap(a.__fbthrift_field_currSlabIdx, b.__fbthrift_field_currSlabIdx);
  swap(a.__fbthrift_field_allocatedSlabIdxs, b.__fbthrift_field_allocatedSlabIdxs);
  swap(a.__fbthrift_field_freeSlabIdxs, b.__fbthrift_field_freeSlabIdxs);
  swap(a.__isset, b.__isset);
}

static_assert(
    ::apache::thrift::detail::st::gen_check_json<
        AllocationClassObject,
        ::apache::thrift::type_class::structure,
        ::facebook::cachelib::serialization::SListObject>,
    "inconsistent use of json option");

} // namespace facebook::cachelib::serialization


namespace facebook::cachelib::serialization {

std::string_view MemoryPoolObject::__fbthrift_get_field_name(::apache::thrift::FieldOrdinal ord) {
  if (ord == ::apache::thrift::FieldOrdinal{0}) { return {}; }
  return apache::thrift::TStructDataStorage<MemoryPoolObject>::fields_names[folly::to_underlying(ord) - 1];
}
std::string_view MemoryPoolObject::__fbthrift_get_class_name() {
  return apache::thrift::TStructDataStorage<MemoryPoolObject>::name;
}

MemoryPoolObject::MemoryPoolObject(const MemoryPoolObject&) = default;
MemoryPoolObject& MemoryPoolObject::operator=(const MemoryPoolObject&) = default;
MemoryPoolObject::MemoryPoolObject() :
    __fbthrift_field_id(),
    __fbthrift_field_maxSize(),
    __fbthrift_field_currSlabAllocSize(),
    __fbthrift_field_currAllocSize(),
    __fbthrift_field_numSlabResize(static_cast<::std::int64_t>(0)),
    __fbthrift_field_numSlabRebalance(static_cast<::std::int64_t>(0)),
    __fbthrift_field_numSlabsAdvised(static_cast<::std::int64_t>(0)) {
}


MemoryPoolObject::~MemoryPoolObject() {}

MemoryPoolObject::MemoryPoolObject([[maybe_unused]] MemoryPoolObject&& other) noexcept :
    __fbthrift_field_id(std::move(other.__fbthrift_field_id)),
    __fbthrift_field_maxSize(std::move(other.__fbthrift_field_maxSize)),
    __fbthrift_field_currSlabAllocSize(std::move(other.__fbthrift_field_currSlabAllocSize)),
    __fbthrift_field_currAllocSize(std::move(other.__fbthrift_field_currAllocSize)),
    __fbthrift_field_acSizes(std::move(other.__fbthrift_field_acSizes)),
    __fbthrift_field_ac(std::move(other.__fbthrift_field_ac)),
    __fbthrift_field_numSlabResize(std::move(other.__fbthrift_field_numSlabResize)),
    __fbthrift_field_numSlabRebalance(std::move(other.__fbthrift_field_numSlabRebalance)),
    __fbthrift_field_freeSlabIdxs(std::move(other.__fbthrift_field_freeSlabIdxs)),
    __fbthrift_field_numSlabsAdvised(std::move(other.__fbthrift_field_numSlabsAdvised)),
    __isset(other.__isset) {
}

MemoryPoolObject& MemoryPoolObject::operator=([[maybe_unused]] MemoryPoolObject&& other) noexcept {
    this->__fbthrift_field_id = std::move(other.__fbthrift_field_id);
    this->__fbthrift_field_maxSize = std::move(other.__fbthrift_field_maxSize);
    this->__fbthrift_field_currSlabAllocSize = std::move(other.__fbthrift_field_currSlabAllocSize);
    this->__fbthrift_field_currAllocSize = std::move(other.__fbthrift_field_currAllocSize);
    this->__fbthrift_field_acSizes = std::move(other.__fbthrift_field_acSizes);
    this->__fbthrift_field_ac = std::move(other.__fbthrift_field_ac);
    this->__fbthrift_field_numSlabResize = std::move(other.__fbthrift_field_numSlabResize);
    this->__fbthrift_field_numSlabRebalance = std::move(other.__fbthrift_field_numSlabRebalance);
    this->__fbthrift_field_freeSlabIdxs = std::move(other.__fbthrift_field_freeSlabIdxs);
    this->__fbthrift_field_numSlabsAdvised = std::move(other.__fbthrift_field_numSlabsAdvised);
    __isset = other.__isset;
    return *this;
}


MemoryPoolObject::MemoryPoolObject(apache::thrift::FragileConstructor, ::std::int8_t id__arg, ::std::int64_t maxSize__arg, ::std::int64_t currSlabAllocSize__arg, ::std::int64_t currAllocSize__arg, ::std::vector<::std::int64_t> acSizes__arg, ::std::vector<::facebook::cachelib::serialization::AllocationClassObject> ac__arg, ::std::int64_t numSlabResize__arg, ::std::int64_t numSlabRebalance__arg, ::std::vector<::std::int32_t> freeSlabIdxs__arg, ::std::int64_t numSlabsAdvised__arg) :
    __fbthrift_field_id(std::move(id__arg)),
    __fbthrift_field_maxSize(std::move(maxSize__arg)),
    __fbthrift_field_currSlabAllocSize(std::move(currSlabAllocSize__arg)),
    __fbthrift_field_currAllocSize(std::move(currAllocSize__arg)),
    __fbthrift_field_acSizes(std::move(acSizes__arg)),
    __fbthrift_field_ac(std::move(ac__arg)),
    __fbthrift_field_numSlabResize(std::move(numSlabResize__arg)),
    __fbthrift_field_numSlabRebalance(std::move(numSlabRebalance__arg)),
    __fbthrift_field_freeSlabIdxs(std::move(freeSlabIdxs__arg)),
    __fbthrift_field_numSlabsAdvised(std::move(numSlabsAdvised__arg)) { 
  __isset.set(folly::index_constant<0>(), true);
  __isset.set(folly::index_constant<1>(), true);
  __isset.set(folly::index_constant<2>(), true);
}

void MemoryPoolObject::__fbthrift_clear() {
  // clear all fields
  this->__fbthrift_field_id = ::std::int8_t();
  this->__fbthrift_field_maxSize = ::std::int64_t();
  this->__fbthrift_field_currSlabAllocSize = ::std::int64_t();
  this->__fbthrift_field_currAllocSize = ::std::int64_t();
  this->__fbthrift_field_acSizes.clear();
  this->__fbthrift_field_ac.clear();
  this->__fbthrift_field_numSlabResize = ::std::int64_t();
  this->__fbthrift_field_numSlabRebalance = ::std::int64_t();
  this->__fbthrift_field_freeSlabIdxs.clear();
  this->__fbthrift_field_numSlabsAdvised = ::std::int64_t();
  __isset = {};
}

bool MemoryPoolObject::__fbthrift_is_empty() const {
  return false;
}

bool MemoryPoolObject::operator==([[maybe_unused]] const MemoryPoolObject& rhs) const {
  return ::apache::thrift::op::detail::StructEquality{}(*this, rhs);
}

bool MemoryPoolObject::operator<([[maybe_unused]] const MemoryPoolObject& rhs) const {
  return ::apache::thrift::op::detail::StructLessThan{}(*this, rhs);
}


::std::int8_t MemoryPoolObject::get_id() const {
  return __fbthrift_field_id;
}

::std::int8_t& MemoryPoolObject::set_id(::std::int8_t id_) {
  id_ref() = id_;
  return __fbthrift_field_id;
}

::std::int64_t MemoryPoolObject::get_maxSize() const {
  return __fbthrift_field_maxSize;
}

::std::int64_t& MemoryPoolObject::set_maxSize(::std::int64_t maxSize_) {
  maxSize_ref() = maxSize_;
  return __fbthrift_field_maxSize;
}

::std::int64_t MemoryPoolObject::get_currSlabAllocSize() const {
  return __fbthrift_field_currSlabAllocSize;
}

::std::int64_t& MemoryPoolObject::set_currSlabAllocSize(::std::int64_t currSlabAllocSize_) {
  currSlabAllocSize_ref() = currSlabAllocSize_;
  return __fbthrift_field_currSlabAllocSize;
}

::std::int64_t MemoryPoolObject::get_currAllocSize() const {
  return __fbthrift_field_currAllocSize;
}

::std::int64_t& MemoryPoolObject::set_currAllocSize(::std::int64_t currAllocSize_) {
  currAllocSize_ref() = currAllocSize_;
  return __fbthrift_field_currAllocSize;
}

const ::std::vector<::std::int64_t>& MemoryPoolObject::get_acSizes() const& {
  return __fbthrift_field_acSizes;
}

::std::vector<::std::int64_t> MemoryPoolObject::get_acSizes() && {
  return static_cast<::std::vector<::std::int64_t>&&>(__fbthrift_field_acSizes);
}

const ::std::vector<::facebook::cachelib::serialization::AllocationClassObject>& MemoryPoolObject::get_ac() const& {
  return __fbthrift_field_ac;
}

::std::vector<::facebook::cachelib::serialization::AllocationClassObject> MemoryPoolObject::get_ac() && {
  return static_cast<::std::vector<::facebook::cachelib::serialization::AllocationClassObject>&&>(__fbthrift_field_ac);
}

::std::int64_t MemoryPoolObject::get_numSlabResize() const {
  return __fbthrift_field_numSlabResize;
}

::std::int64_t& MemoryPoolObject::set_numSlabResize(::std::int64_t numSlabResize_) {
  numSlabResize_ref() = numSlabResize_;
  return __fbthrift_field_numSlabResize;
}

::std::int64_t MemoryPoolObject::get_numSlabRebalance() const {
  return __fbthrift_field_numSlabRebalance;
}

::std::int64_t& MemoryPoolObject::set_numSlabRebalance(::std::int64_t numSlabRebalance_) {
  numSlabRebalance_ref() = numSlabRebalance_;
  return __fbthrift_field_numSlabRebalance;
}

const ::std::vector<::std::int32_t>& MemoryPoolObject::get_freeSlabIdxs() const& {
  return __fbthrift_field_freeSlabIdxs;
}

::std::vector<::std::int32_t> MemoryPoolObject::get_freeSlabIdxs() && {
  return static_cast<::std::vector<::std::int32_t>&&>(__fbthrift_field_freeSlabIdxs);
}

::std::int64_t MemoryPoolObject::get_numSlabsAdvised() const {
  return __fbthrift_field_numSlabsAdvised;
}

::std::int64_t& MemoryPoolObject::set_numSlabsAdvised(::std::int64_t numSlabsAdvised_) {
  numSlabsAdvised_ref() = numSlabsAdvised_;
  return __fbthrift_field_numSlabsAdvised;
}

void swap([[maybe_unused]] MemoryPoolObject& a, [[maybe_unused]] MemoryPoolObject& b) {
  using ::std::swap;
  swap(a.__fbthrift_field_id, b.__fbthrift_field_id);
  swap(a.__fbthrift_field_maxSize, b.__fbthrift_field_maxSize);
  swap(a.__fbthrift_field_currSlabAllocSize, b.__fbthrift_field_currSlabAllocSize);
  swap(a.__fbthrift_field_currAllocSize, b.__fbthrift_field_currAllocSize);
  swap(a.__fbthrift_field_acSizes, b.__fbthrift_field_acSizes);
  swap(a.__fbthrift_field_ac, b.__fbthrift_field_ac);
  swap(a.__fbthrift_field_numSlabResize, b.__fbthrift_field_numSlabResize);
  swap(a.__fbthrift_field_numSlabRebalance, b.__fbthrift_field_numSlabRebalance);
  swap(a.__fbthrift_field_freeSlabIdxs, b.__fbthrift_field_freeSlabIdxs);
  swap(a.__fbthrift_field_numSlabsAdvised, b.__fbthrift_field_numSlabsAdvised);
  swap(a.__isset, b.__isset);
}

static_assert(
    ::apache::thrift::detail::st::gen_check_json<
        MemoryPoolObject,
        ::apache::thrift::type_class::list<::apache::thrift::type_class::structure>,
        ::std::vector<::facebook::cachelib::serialization::AllocationClassObject>>,
    "inconsistent use of json option");

} // namespace facebook::cachelib::serialization


namespace facebook::cachelib::serialization {

std::string_view MemoryPoolManagerObject::__fbthrift_get_field_name(::apache::thrift::FieldOrdinal ord) {
  if (ord == ::apache::thrift::FieldOrdinal{0}) { return {}; }
  return apache::thrift::TStructDataStorage<MemoryPoolManagerObject>::fields_names[folly::to_underlying(ord) - 1];
}
std::string_view MemoryPoolManagerObject::__fbthrift_get_class_name() {
  return apache::thrift::TStructDataStorage<MemoryPoolManagerObject>::name;
}

MemoryPoolManagerObject::MemoryPoolManagerObject(const MemoryPoolManagerObject&) = default;
MemoryPoolManagerObject& MemoryPoolManagerObject::operator=(const MemoryPoolManagerObject&) = default;
MemoryPoolManagerObject::MemoryPoolManagerObject() :
    __fbthrift_field_nextPoolId() {
}


MemoryPoolManagerObject::~MemoryPoolManagerObject() {}

MemoryPoolManagerObject::MemoryPoolManagerObject([[maybe_unused]] MemoryPoolManagerObject&& other) noexcept :
    __fbthrift_field_pools(std::move(other.__fbthrift_field_pools)),
    __fbthrift_field_poolsByName(std::move(other.__fbthrift_field_poolsByName)),
    __fbthrift_field_nextPoolId(std::move(other.__fbthrift_field_nextPoolId)),
    __isset(other.__isset) {
}

MemoryPoolManagerObject& MemoryPoolManagerObject::operator=([[maybe_unused]] MemoryPoolManagerObject&& other) noexcept {
    this->__fbthrift_field_pools = std::move(other.__fbthrift_field_pools);
    this->__fbthrift_field_poolsByName = std::move(other.__fbthrift_field_poolsByName);
    this->__fbthrift_field_nextPoolId = std::move(other.__fbthrift_field_nextPoolId);
    __isset = other.__isset;
    return *this;
}


MemoryPoolManagerObject::MemoryPoolManagerObject(apache::thrift::FragileConstructor, ::std::vector<::facebook::cachelib::serialization::MemoryPoolObject> pools__arg, ::std::map<::std::string, ::std::int8_t> poolsByName__arg, ::std::int8_t nextPoolId__arg) :
    __fbthrift_field_pools(std::move(pools__arg)),
    __fbthrift_field_poolsByName(std::move(poolsByName__arg)),
    __fbthrift_field_nextPoolId(std::move(nextPoolId__arg)) { 
  __isset.set(folly::index_constant<0>(), true);
  __isset.set(folly::index_constant<1>(), true);
  __isset.set(folly::index_constant<2>(), true);
}

void MemoryPoolManagerObject::__fbthrift_clear() {
  // clear all fields
  this->__fbthrift_field_pools.clear();
  this->__fbthrift_field_poolsByName.clear();
  this->__fbthrift_field_nextPoolId = ::std::int8_t();
  __isset = {};
}

bool MemoryPoolManagerObject::__fbthrift_is_empty() const {
  return false;
}

bool MemoryPoolManagerObject::operator==([[maybe_unused]] const MemoryPoolManagerObject& rhs) const {
  return ::apache::thrift::op::detail::StructEquality{}(*this, rhs);
}

bool MemoryPoolManagerObject::operator<([[maybe_unused]] const MemoryPoolManagerObject& rhs) const {
  return ::apache::thrift::op::detail::StructLessThan{}(*this, rhs);
}


const ::std::vector<::facebook::cachelib::serialization::MemoryPoolObject>& MemoryPoolManagerObject::get_pools() const& {
  return __fbthrift_field_pools;
}

::std::vector<::facebook::cachelib::serialization::MemoryPoolObject> MemoryPoolManagerObject::get_pools() && {
  return static_cast<::std::vector<::facebook::cachelib::serialization::MemoryPoolObject>&&>(__fbthrift_field_pools);
}

const ::std::map<::std::string, ::std::int8_t>& MemoryPoolManagerObject::get_poolsByName() const& {
  return __fbthrift_field_poolsByName;
}

::std::map<::std::string, ::std::int8_t> MemoryPoolManagerObject::get_poolsByName() && {
  return static_cast<::std::map<::std::string, ::std::int8_t>&&>(__fbthrift_field_poolsByName);
}

::std::int8_t MemoryPoolManagerObject::get_nextPoolId() const {
  return __fbthrift_field_nextPoolId;
}

::std::int8_t& MemoryPoolManagerObject::set_nextPoolId(::std::int8_t nextPoolId_) {
  nextPoolId_ref() = nextPoolId_;
  return __fbthrift_field_nextPoolId;
}

void swap([[maybe_unused]] MemoryPoolManagerObject& a, [[maybe_unused]] MemoryPoolManagerObject& b) {
  using ::std::swap;
  swap(a.__fbthrift_field_pools, b.__fbthrift_field_pools);
  swap(a.__fbthrift_field_poolsByName, b.__fbthrift_field_poolsByName);
  swap(a.__fbthrift_field_nextPoolId, b.__fbthrift_field_nextPoolId);
  swap(a.__isset, b.__isset);
}

static_assert(
    ::apache::thrift::detail::st::gen_check_json<
        MemoryPoolManagerObject,
        ::apache::thrift::type_class::list<::apache::thrift::type_class::structure>,
        ::std::vector<::facebook::cachelib::serialization::MemoryPoolObject>>,
    "inconsistent use of json option");

} // namespace facebook::cachelib::serialization


namespace facebook::cachelib::serialization {

std::string_view MemoryAllocatorObject::__fbthrift_get_field_name(::apache::thrift::FieldOrdinal ord) {
  if (ord == ::apache::thrift::FieldOrdinal{0}) { return {}; }
  return apache::thrift::TStructDataStorage<MemoryAllocatorObject>::fields_names[folly::to_underlying(ord) - 1];
}
std::string_view MemoryAllocatorObject::__fbthrift_get_class_name() {
  return apache::thrift::TStructDataStorage<MemoryAllocatorObject>::name;
}

MemoryAllocatorObject::MemoryAllocatorObject(const MemoryAllocatorObject&) = default;
MemoryAllocatorObject& MemoryAllocatorObject::operator=(const MemoryAllocatorObject&) = default;
MemoryAllocatorObject::MemoryAllocatorObject() :
    __fbthrift_field_enableZeroedSlabAllocs(),
    __fbthrift_field_lockMemory(false) {
}


MemoryAllocatorObject::~MemoryAllocatorObject() {}

MemoryAllocatorObject::MemoryAllocatorObject([[maybe_unused]] MemoryAllocatorObject&& other) noexcept :
    __fbthrift_field_allocSizes(std::move(other.__fbthrift_field_allocSizes)),
    __fbthrift_field_enableZeroedSlabAllocs(std::move(other.__fbthrift_field_enableZeroedSlabAllocs)),
    __fbthrift_field_lockMemory(std::move(other.__fbthrift_field_lockMemory)),
    __fbthrift_field_slabAllocator(std::move(other.__fbthrift_field_slabAllocator)),
    __fbthrift_field_memoryPoolManager(std::move(other.__fbthrift_field_memoryPoolManager)),
    __isset(other.__isset) {
}

MemoryAllocatorObject& MemoryAllocatorObject::operator=([[maybe_unused]] MemoryAllocatorObject&& other) noexcept {
    this->__fbthrift_field_allocSizes = std::move(other.__fbthrift_field_allocSizes);
    this->__fbthrift_field_enableZeroedSlabAllocs = std::move(other.__fbthrift_field_enableZeroedSlabAllocs);
    this->__fbthrift_field_lockMemory = std::move(other.__fbthrift_field_lockMemory);
    this->__fbthrift_field_slabAllocator = std::move(other.__fbthrift_field_slabAllocator);
    this->__fbthrift_field_memoryPoolManager = std::move(other.__fbthrift_field_memoryPoolManager);
    __isset = other.__isset;
    return *this;
}


MemoryAllocatorObject::MemoryAllocatorObject(apache::thrift::FragileConstructor, ::std::set<::std::int64_t> allocSizes__arg, bool enableZeroedSlabAllocs__arg, bool lockMemory__arg, ::facebook::cachelib::serialization::SlabAllocatorObject slabAllocator__arg, ::facebook::cachelib::serialization::MemoryPoolManagerObject memoryPoolManager__arg) :
    __fbthrift_field_allocSizes(std::move(allocSizes__arg)),
    __fbthrift_field_enableZeroedSlabAllocs(std::move(enableZeroedSlabAllocs__arg)),
    __fbthrift_field_lockMemory(std::move(lockMemory__arg)),
    __fbthrift_field_slabAllocator(std::move(slabAllocator__arg)),
    __fbthrift_field_memoryPoolManager(std::move(memoryPoolManager__arg)) { 
  __isset.set(folly::index_constant<0>(), true);
}

void MemoryAllocatorObject::__fbthrift_clear() {
  // clear all fields
  this->__fbthrift_field_allocSizes.clear();
  this->__fbthrift_field_enableZeroedSlabAllocs = bool();
  this->__fbthrift_field_lockMemory = bool();
  ::apache::thrift::clear(this->__fbthrift_field_slabAllocator);
  ::apache::thrift::clear(this->__fbthrift_field_memoryPoolManager);
  __isset = {};
}

bool MemoryAllocatorObject::__fbthrift_is_empty() const {
  return false;
}

bool MemoryAllocatorObject::operator==([[maybe_unused]] const MemoryAllocatorObject& rhs) const {
  return ::apache::thrift::op::detail::StructEquality{}(*this, rhs);
}

bool MemoryAllocatorObject::operator<([[maybe_unused]] const MemoryAllocatorObject& rhs) const {
  return ::apache::thrift::op::detail::StructLessThan{}(*this, rhs);
}


const ::std::set<::std::int64_t>& MemoryAllocatorObject::get_allocSizes() const& {
  return __fbthrift_field_allocSizes;
}

::std::set<::std::int64_t> MemoryAllocatorObject::get_allocSizes() && {
  return static_cast<::std::set<::std::int64_t>&&>(__fbthrift_field_allocSizes);
}

bool MemoryAllocatorObject::get_enableZeroedSlabAllocs() const {
  return __fbthrift_field_enableZeroedSlabAllocs;
}

bool& MemoryAllocatorObject::set_enableZeroedSlabAllocs(bool enableZeroedSlabAllocs_) {
  enableZeroedSlabAllocs_ref() = enableZeroedSlabAllocs_;
  return __fbthrift_field_enableZeroedSlabAllocs;
}

bool MemoryAllocatorObject::get_lockMemory() const {
  return __fbthrift_field_lockMemory;
}

bool& MemoryAllocatorObject::set_lockMemory(bool lockMemory_) {
  lockMemory_ref() = lockMemory_;
  return __fbthrift_field_lockMemory;
}

const ::facebook::cachelib::serialization::SlabAllocatorObject& MemoryAllocatorObject::get_slabAllocator() const& {
  return __fbthrift_field_slabAllocator;
}

::facebook::cachelib::serialization::SlabAllocatorObject MemoryAllocatorObject::get_slabAllocator() && {
  return static_cast<::facebook::cachelib::serialization::SlabAllocatorObject&&>(__fbthrift_field_slabAllocator);
}

const ::facebook::cachelib::serialization::MemoryPoolManagerObject& MemoryAllocatorObject::get_memoryPoolManager() const& {
  return __fbthrift_field_memoryPoolManager;
}

::facebook::cachelib::serialization::MemoryPoolManagerObject MemoryAllocatorObject::get_memoryPoolManager() && {
  return static_cast<::facebook::cachelib::serialization::MemoryPoolManagerObject&&>(__fbthrift_field_memoryPoolManager);
}

void swap([[maybe_unused]] MemoryAllocatorObject& a, [[maybe_unused]] MemoryAllocatorObject& b) {
  using ::std::swap;
  swap(a.__fbthrift_field_allocSizes, b.__fbthrift_field_allocSizes);
  swap(a.__fbthrift_field_enableZeroedSlabAllocs, b.__fbthrift_field_enableZeroedSlabAllocs);
  swap(a.__fbthrift_field_lockMemory, b.__fbthrift_field_lockMemory);
  swap(a.__fbthrift_field_slabAllocator, b.__fbthrift_field_slabAllocator);
  swap(a.__fbthrift_field_memoryPoolManager, b.__fbthrift_field_memoryPoolManager);
  swap(a.__isset, b.__isset);
}

static_assert(
    ::apache::thrift::detail::st::gen_check_json<
        MemoryAllocatorObject,
        ::apache::thrift::type_class::structure,
        ::facebook::cachelib::serialization::SlabAllocatorObject>,
    "inconsistent use of json option");
static_assert(
    ::apache::thrift::detail::st::gen_check_json<
        MemoryAllocatorObject,
        ::apache::thrift::type_class::structure,
        ::facebook::cachelib::serialization::MemoryPoolManagerObject>,
    "inconsistent use of json option");

} // namespace facebook::cachelib::serialization

namespace facebook::cachelib::serialization { namespace {
[[maybe_unused]] FOLLY_ERASE void validateAdapters() {
}
}} // namespace facebook::cachelib::serialization
namespace apache::thrift::detail::annotation {
}
