/**
 * Autogenerated by Thrift for cachelib/allocator/memory/serialize/objects.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated @nocommit
 */
#pragma once

namespace apache::thrift {
  template <typename> class Client;
} // namespace apache::thrift



namespace apache::thrift {
} // namespace apache::thrift
