/**
 * Autogenerated by Thrift for cachelib/allocator/memory/serialize/objects.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated @nocommit
 */

#include "cachelib/allocator/memory/serialize/gen-cpp2/objects_constants.h"

#include <thrift/lib/cpp2/gen/module_constants_cpp.h>

#include "cachelib/allocator/datastruct/serialize/gen-cpp2/objects_constants.h"

namespace facebook::cachelib::serialization {
namespace objects_constants {


::std::string_view _fbthrift_schema_579593bad84cc3bd() {
  return "";
}
::folly::Range<const ::std::string_view*> _fbthrift_schema_579593bad84cc3bd_includes() {
  return {};
}
::folly::Range<const ::std::string_view*> _fbthrift_schema_579593bad84cc3bd_uris() {
  return {};
}

} // namespace objects_constants
} // namespace facebook::cachelib::serialization
