/**
 * Autogenerated by Thrift for cachelib/allocator/memory/serialize/objects.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated @nocommit
 */
#pragma once


/**
 * This header file includes the tcc files of the corresponding header file
 * and the header files of its dependent types. Include this header file
 * only when you need to use custom protocols (e.g. DebugProtocol,
 * VirtualProtocol) to read/write thrift structs.
 */

#include "cachelib/allocator/memory/serialize/gen-cpp2/objects_types.tcc"

#include "cachelib/allocator/datastruct/serialize/gen-cpp2/objects_types_custom_protocol.h"


namespace apache {
namespace thrift {
namespace detail {

template <>
struct TccStructTraits<::facebook::cachelib::serialization::SlabAllocatorObject> {
  static void translateFieldName(
      std::string_view _fname,
      int16_t& fid,
      apache::thrift::protocol::TType& _ftype);
};
template <>
struct TccStructTraits<::facebook::cachelib::serialization::AllocationClassObject> {
  static void translateFieldName(
      std::string_view _fname,
      int16_t& fid,
      apache::thrift::protocol::TType& _ftype);
};
template <>
struct TccStructTraits<::facebook::cachelib::serialization::MemoryPoolObject> {
  static void translateFieldName(
      std::string_view _fname,
      int16_t& fid,
      apache::thrift::protocol::TType& _ftype);
};
template <>
struct TccStructTraits<::facebook::cachelib::serialization::MemoryPoolManagerObject> {
  static void translateFieldName(
      std::string_view _fname,
      int16_t& fid,
      apache::thrift::protocol::TType& _ftype);
};
template <>
struct TccStructTraits<::facebook::cachelib::serialization::MemoryAllocatorObject> {
  static void translateFieldName(
      std::string_view _fname,
      int16_t& fid,
      apache::thrift::protocol::TType& _ftype);
};

} // namespace detail
} // namespace thrift
} // namespace apache

namespace facebook::cachelib::serialization {

template <class Protocol_>
void SlabAllocatorObject::readNoXfer(Protocol_* iprot) {
  apache::thrift::detail::ProtocolReaderStructReadState<Protocol_> _readState;

  _readState.readStructBegin(iprot);

  using apache::thrift::TProtocolException;


  if (UNLIKELY(!_readState.advanceToNextField(
          iprot,
          0,
          2,
          apache::thrift::protocol::TType::T_I64))) {
    goto _advance_failure;
  }
_readField_memorySize:
  {
    ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int64_t>::readWithContext(*iprot, this->__fbthrift_field_memorySize, _readState);
  }

  if (UNLIKELY(!_readState.advanceToNextField(
          iprot,
          2,
          4,
          apache::thrift::protocol::TType::T_BOOL))) {
    goto _advance_failure;
  }
_readField_canAllocate:
  {
    ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, bool>::readWithContext(*iprot, this->__fbthrift_field_canAllocate, _readState);
  }

  if (UNLIKELY(!_readState.advanceToNextField(
          iprot,
          4,
          5,
          apache::thrift::protocol::TType::T_MAP))) {
    goto _advance_failure;
  }
_readField_memoryPoolSize:
  {
    _readState.beforeSubobject(iprot);
    this->__fbthrift_field_memoryPoolSize = ::std::map<::std::int8_t, ::std::int64_t>();
    ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::map<::apache::thrift::type_class::integral, ::apache::thrift::type_class::integral>, ::std::map<::std::int8_t, ::std::int64_t>>::readWithContext(*iprot, this->__fbthrift_field_memoryPoolSize, _readState);
    _readState.afterSubobject(iprot);
  }

  if (UNLIKELY(!_readState.advanceToNextField(
          iprot,
          5,
          7,
          apache::thrift::protocol::TType::T_I64))) {
    goto _advance_failure;
  }
_readField_slabSize:
  {
    ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int64_t>::readWithContext(*iprot, this->__fbthrift_field_slabSize, _readState);
  }

  if (UNLIKELY(!_readState.advanceToNextField(
          iprot,
          7,
          8,
          apache::thrift::protocol::TType::T_I64))) {
    goto _advance_failure;
  }
_readField_minAllocSize:
  {
    ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int64_t>::readWithContext(*iprot, this->__fbthrift_field_minAllocSize, _readState);
  }

  if (UNLIKELY(!_readState.advanceToNextField(
          iprot,
          8,
          9,
          apache::thrift::protocol::TType::T_I32))) {
    goto _advance_failure;
  }
_readField_nextSlabIdx:
  {
    ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int32_t>::readWithContext(*iprot, this->__fbthrift_field_nextSlabIdx, _readState);
  }

  if (UNLIKELY(!_readState.advanceToNextField(
          iprot,
          9,
          10,
          apache::thrift::protocol::TType::T_LIST))) {
    goto _advance_failure;
  }
_readField_freeSlabIdxs:
  {
    _readState.beforeSubobject(iprot);
    this->__fbthrift_field_freeSlabIdxs = ::std::vector<::std::int32_t>();
    ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::list<::apache::thrift::type_class::integral>, ::std::vector<::std::int32_t>>::readWithContext(*iprot, this->__fbthrift_field_freeSlabIdxs, _readState);
    _readState.afterSubobject(iprot);
  }

  if (UNLIKELY(!_readState.advanceToNextField(
          iprot,
          10,
          11,
          apache::thrift::protocol::TType::T_LIST))) {
    goto _advance_failure;
  }
_readField_advisedSlabIdxs:
  {
    _readState.beforeSubobject(iprot);
    this->__fbthrift_field_advisedSlabIdxs = ::std::vector<::std::int32_t>();
    ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::list<::apache::thrift::type_class::integral>, ::std::vector<::std::int32_t>>::readWithContext(*iprot, this->__fbthrift_field_advisedSlabIdxs, _readState);
    _readState.afterSubobject(iprot);
  }
 this->__isset.set(0, true);

  if (UNLIKELY(!_readState.advanceToNextField(
          iprot,
          11,
          0,
          apache::thrift::protocol::T_STOP))) {
    goto _advance_failure;
  }

_end:
  _readState.readStructEnd(iprot);

  return;

  goto _advance_failure; // Avoid compiler warnings about unused labels.
  _advance_failure:
  _readState.afterAdvanceFailure(iprot);
_loop:
  if (_readState.atStop()) {
    goto _end;
  }
  if (iprot->kUsesFieldNames()) {
    _readState.template fillFieldTraitsFromName<apache::thrift::detail::TccStructTraits<SlabAllocatorObject>>();
  }

  switch (_readState.fieldId) {
    case 2:
    {
      if (LIKELY(_readState.isCompatibleWithType(iprot, apache::thrift::protocol::TType::T_I64))) {
        goto _readField_memorySize;
      } else {
        goto _skip;
      }
    }
    case 4:
    {
      if (LIKELY(_readState.isCompatibleWithType(iprot, apache::thrift::protocol::TType::T_BOOL))) {
        goto _readField_canAllocate;
      } else {
        goto _skip;
      }
    }
    case 5:
    {
      if (LIKELY(_readState.isCompatibleWithType(iprot, apache::thrift::protocol::TType::T_MAP))) {
        goto _readField_memoryPoolSize;
      } else {
        goto _skip;
      }
    }
    case 7:
    {
      if (LIKELY(_readState.isCompatibleWithType(iprot, apache::thrift::protocol::TType::T_I64))) {
        goto _readField_slabSize;
      } else {
        goto _skip;
      }
    }
    case 8:
    {
      if (LIKELY(_readState.isCompatibleWithType(iprot, apache::thrift::protocol::TType::T_I64))) {
        goto _readField_minAllocSize;
      } else {
        goto _skip;
      }
    }
    case 9:
    {
      if (LIKELY(_readState.isCompatibleWithType(iprot, apache::thrift::protocol::TType::T_I32))) {
        goto _readField_nextSlabIdx;
      } else {
        goto _skip;
      }
    }
    case 10:
    {
      if (LIKELY(_readState.isCompatibleWithType(iprot, apache::thrift::protocol::TType::T_LIST))) {
        goto _readField_freeSlabIdxs;
      } else {
        goto _skip;
      }
    }
    case 11:
    {
      if (LIKELY(_readState.isCompatibleWithType(iprot, apache::thrift::protocol::TType::T_LIST))) {
        goto _readField_advisedSlabIdxs;
      } else {
        goto _skip;
      }
    }
    default:
    {
_skip:
      _readState.skip(iprot);
      _readState.readFieldEnd(iprot);
      _readState.readFieldBeginNoInline(iprot);
      goto _loop;
    }
  }
}

template <class Protocol_>
uint32_t SlabAllocatorObject::serializedSize(Protocol_ const* prot_) const {
  uint32_t xfer = 0;
  xfer += prot_->serializedStructSize("SlabAllocatorObject");
  {
    xfer += prot_->serializedFieldSize("memorySize", apache::thrift::protocol::TType::T_I64, 2);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int64_t>::serializedSize<false>(*prot_, this->__fbthrift_field_memorySize);
  }
  {
    xfer += prot_->serializedFieldSize("canAllocate", apache::thrift::protocol::TType::T_BOOL, 4);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, bool>::serializedSize<false>(*prot_, this->__fbthrift_field_canAllocate);
  }
  {
    xfer += prot_->serializedFieldSize("memoryPoolSize", apache::thrift::protocol::TType::T_MAP, 5);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::map<::apache::thrift::type_class::integral, ::apache::thrift::type_class::integral>, ::std::map<::std::int8_t, ::std::int64_t>>::serializedSize<false>(*prot_, this->__fbthrift_field_memoryPoolSize);
  }
  {
    xfer += prot_->serializedFieldSize("slabSize", apache::thrift::protocol::TType::T_I64, 7);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int64_t>::serializedSize<false>(*prot_, this->__fbthrift_field_slabSize);
  }
  {
    xfer += prot_->serializedFieldSize("minAllocSize", apache::thrift::protocol::TType::T_I64, 8);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int64_t>::serializedSize<false>(*prot_, this->__fbthrift_field_minAllocSize);
  }
  {
    xfer += prot_->serializedFieldSize("nextSlabIdx", apache::thrift::protocol::TType::T_I32, 9);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int32_t>::serializedSize<false>(*prot_, this->__fbthrift_field_nextSlabIdx);
  }
  {
    xfer += prot_->serializedFieldSize("freeSlabIdxs", apache::thrift::protocol::TType::T_LIST, 10);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::list<::apache::thrift::type_class::integral>, ::std::vector<::std::int32_t>>::serializedSize<false>(*prot_, this->__fbthrift_field_freeSlabIdxs);
  }
  {
    xfer += prot_->serializedFieldSize("advisedSlabIdxs", apache::thrift::protocol::TType::T_LIST, 11);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::list<::apache::thrift::type_class::integral>, ::std::vector<::std::int32_t>>::serializedSize<false>(*prot_, this->__fbthrift_field_advisedSlabIdxs);
  }
  xfer += prot_->serializedSizeStop();
  return xfer;
}

template <class Protocol_>
uint32_t SlabAllocatorObject::serializedSizeZC(Protocol_ const* prot_) const {
  uint32_t xfer = 0;
  xfer += prot_->serializedStructSize("SlabAllocatorObject");
  {
    xfer += prot_->serializedFieldSize("memorySize", apache::thrift::protocol::TType::T_I64, 2);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int64_t>::serializedSize<false>(*prot_, this->__fbthrift_field_memorySize);
  }
  {
    xfer += prot_->serializedFieldSize("canAllocate", apache::thrift::protocol::TType::T_BOOL, 4);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, bool>::serializedSize<false>(*prot_, this->__fbthrift_field_canAllocate);
  }
  {
    xfer += prot_->serializedFieldSize("memoryPoolSize", apache::thrift::protocol::TType::T_MAP, 5);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::map<::apache::thrift::type_class::integral, ::apache::thrift::type_class::integral>, ::std::map<::std::int8_t, ::std::int64_t>>::serializedSize<false>(*prot_, this->__fbthrift_field_memoryPoolSize);
  }
  {
    xfer += prot_->serializedFieldSize("slabSize", apache::thrift::protocol::TType::T_I64, 7);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int64_t>::serializedSize<false>(*prot_, this->__fbthrift_field_slabSize);
  }
  {
    xfer += prot_->serializedFieldSize("minAllocSize", apache::thrift::protocol::TType::T_I64, 8);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int64_t>::serializedSize<false>(*prot_, this->__fbthrift_field_minAllocSize);
  }
  {
    xfer += prot_->serializedFieldSize("nextSlabIdx", apache::thrift::protocol::TType::T_I32, 9);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int32_t>::serializedSize<false>(*prot_, this->__fbthrift_field_nextSlabIdx);
  }
  {
    xfer += prot_->serializedFieldSize("freeSlabIdxs", apache::thrift::protocol::TType::T_LIST, 10);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::list<::apache::thrift::type_class::integral>, ::std::vector<::std::int32_t>>::serializedSize<false>(*prot_, this->__fbthrift_field_freeSlabIdxs);
  }
  {
    xfer += prot_->serializedFieldSize("advisedSlabIdxs", apache::thrift::protocol::TType::T_LIST, 11);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::list<::apache::thrift::type_class::integral>, ::std::vector<::std::int32_t>>::serializedSize<false>(*prot_, this->__fbthrift_field_advisedSlabIdxs);
  }
  xfer += prot_->serializedSizeStop();
  return xfer;
}

template <class Protocol_>
uint32_t SlabAllocatorObject::write(Protocol_* prot_) const {
  // If the protocol requests field-id-ascending order and it differs from
  // the codegen serialization order, delegate to the generic StructEncode
  // which respects FieldOrder::IdAscending.
  if constexpr (requires { prot_->fieldOrder(); }) {
    if (prot_->fieldOrder() == ::apache::thrift::FieldOrder::IdAscending) {
      return ::apache::thrift::op::detail::StructEncode<SlabAllocatorObject>{}(*prot_, *this);
    }
  }
  uint32_t xfer = 0;
  xfer += prot_->writeStructBegin("SlabAllocatorObject");
  bool previousFieldHasValue = true;
  {
    constexpr int16_t kPrevFieldId = 0;
    xfer += ::apache::thrift::detail::writeFieldBegin<apache::thrift::protocol::TType::T_I64, 2, kPrevFieldId>(*prot_, "memorySize", previousFieldHasValue);
    previousFieldHasValue = true;
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int64_t>::write(*prot_, this->__fbthrift_field_memorySize);
    xfer += prot_->writeFieldEnd();
  }
  {
    constexpr int16_t kPrevFieldId = 2;
    xfer += ::apache::thrift::detail::writeFieldBegin<apache::thrift::protocol::TType::T_BOOL, 4, kPrevFieldId>(*prot_, "canAllocate", previousFieldHasValue);
    previousFieldHasValue = true;
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, bool>::write(*prot_, this->__fbthrift_field_canAllocate);
    xfer += prot_->writeFieldEnd();
  }
  {
    constexpr int16_t kPrevFieldId = 4;
    xfer += ::apache::thrift::detail::writeFieldBegin<apache::thrift::protocol::TType::T_MAP, 5, kPrevFieldId>(*prot_, "memoryPoolSize", previousFieldHasValue);
    previousFieldHasValue = true;
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::map<::apache::thrift::type_class::integral, ::apache::thrift::type_class::integral>, ::std::map<::std::int8_t, ::std::int64_t>>::write(*prot_, this->__fbthrift_field_memoryPoolSize);
    xfer += prot_->writeFieldEnd();
  }
  {
    constexpr int16_t kPrevFieldId = 5;
    xfer += ::apache::thrift::detail::writeFieldBegin<apache::thrift::protocol::TType::T_I64, 7, kPrevFieldId>(*prot_, "slabSize", previousFieldHasValue);
    previousFieldHasValue = true;
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int64_t>::write(*prot_, this->__fbthrift_field_slabSize);
    xfer += prot_->writeFieldEnd();
  }
  {
    constexpr int16_t kPrevFieldId = 7;
    xfer += ::apache::thrift::detail::writeFieldBegin<apache::thrift::protocol::TType::T_I64, 8, kPrevFieldId>(*prot_, "minAllocSize", previousFieldHasValue);
    previousFieldHasValue = true;
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int64_t>::write(*prot_, this->__fbthrift_field_minAllocSize);
    xfer += prot_->writeFieldEnd();
  }
  {
    constexpr int16_t kPrevFieldId = 8;
    xfer += ::apache::thrift::detail::writeFieldBegin<apache::thrift::protocol::TType::T_I32, 9, kPrevFieldId>(*prot_, "nextSlabIdx", previousFieldHasValue);
    previousFieldHasValue = true;
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int32_t>::write(*prot_, this->__fbthrift_field_nextSlabIdx);
    xfer += prot_->writeFieldEnd();
  }
  {
    constexpr int16_t kPrevFieldId = 9;
    xfer += ::apache::thrift::detail::writeFieldBegin<apache::thrift::protocol::TType::T_LIST, 10, kPrevFieldId>(*prot_, "freeSlabIdxs", previousFieldHasValue);
    previousFieldHasValue = true;
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::list<::apache::thrift::type_class::integral>, ::std::vector<::std::int32_t>>::write(*prot_, this->__fbthrift_field_freeSlabIdxs);
    xfer += prot_->writeFieldEnd();
  }
  {
    constexpr int16_t kPrevFieldId = 10;
    xfer += ::apache::thrift::detail::writeFieldBegin<apache::thrift::protocol::TType::T_LIST, 11, kPrevFieldId>(*prot_, "advisedSlabIdxs", previousFieldHasValue);
    previousFieldHasValue = true;
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::list<::apache::thrift::type_class::integral>, ::std::vector<::std::int32_t>>::write(*prot_, this->__fbthrift_field_advisedSlabIdxs);
    xfer += prot_->writeFieldEnd();
  }
  xfer += prot_->writeFieldStop();
  xfer += prot_->writeStructEnd();
  return xfer;
}

extern template void SlabAllocatorObject::readNoXfer<>(apache::thrift::BinaryProtocolReader*);
extern template uint32_t SlabAllocatorObject::write<>(apache::thrift::BinaryProtocolWriter*) const;
extern template uint32_t SlabAllocatorObject::serializedSize<>(apache::thrift::BinaryProtocolWriter const*) const;
extern template uint32_t SlabAllocatorObject::serializedSizeZC<>(apache::thrift::BinaryProtocolWriter const*) const;
extern template void SlabAllocatorObject::readNoXfer<>(apache::thrift::CompactProtocolReader*);
extern template uint32_t SlabAllocatorObject::write<>(apache::thrift::CompactProtocolWriter*) const;
extern template uint32_t SlabAllocatorObject::serializedSize<>(apache::thrift::CompactProtocolWriter const*) const;
extern template uint32_t SlabAllocatorObject::serializedSizeZC<>(apache::thrift::CompactProtocolWriter const*) const;


template <class Protocol_>
void AllocationClassObject::readNoXfer(Protocol_* iprot) {
  apache::thrift::detail::ProtocolReaderStructReadState<Protocol_> _readState;

  _readState.readStructBegin(iprot);

  using apache::thrift::TProtocolException;


  if (UNLIKELY(!_readState.advanceToNextField(
          iprot,
          0,
          1,
          apache::thrift::protocol::TType::T_BYTE))) {
    goto _advance_failure;
  }
_readField_classId:
  {
    ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int8_t>::readWithContext(*iprot, this->__fbthrift_field_classId, _readState);
  }

  if (UNLIKELY(!_readState.advanceToNextField(
          iprot,
          1,
          2,
          apache::thrift::protocol::TType::T_I64))) {
    goto _advance_failure;
  }
_readField_allocationSize:
  {
    ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int64_t>::readWithContext(*iprot, this->__fbthrift_field_allocationSize, _readState);
  }

  if (UNLIKELY(!_readState.advanceToNextField(
          iprot,
          2,
          4,
          apache::thrift::protocol::TType::T_I64))) {
    goto _advance_failure;
  }
_readField_currOffset:
  {
    ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int64_t>::readWithContext(*iprot, this->__fbthrift_field_currOffset, _readState);
  }

  if (UNLIKELY(!_readState.advanceToNextField(
          iprot,
          4,
          8,
          apache::thrift::protocol::TType::T_BOOL))) {
    goto _advance_failure;
  }
_readField_canAllocate:
  {
    ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, bool>::readWithContext(*iprot, this->__fbthrift_field_canAllocate, _readState);
  }

  if (UNLIKELY(!_readState.advanceToNextField(
          iprot,
          8,
          9,
          apache::thrift::protocol::TType::T_STRUCT))) {
    goto _advance_failure;
  }
_readField_freedAllocationsObject:
  {
    _readState.beforeSubobject(iprot);
    ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::structure, ::facebook::cachelib::serialization::SListObject>::readWithContext(*iprot, this->__fbthrift_field_freedAllocationsObject, _readState);
    _readState.afterSubobject(iprot);
  }
 this->__isset.set(0, true);

  if (UNLIKELY(!_readState.advanceToNextField(
          iprot,
          9,
          10,
          apache::thrift::protocol::TType::T_I32))) {
    goto _advance_failure;
  }
_readField_currSlabIdx:
  {
    ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int32_t>::readWithContext(*iprot, this->__fbthrift_field_currSlabIdx, _readState);
  }

  if (UNLIKELY(!_readState.advanceToNextField(
          iprot,
          10,
          11,
          apache::thrift::protocol::TType::T_LIST))) {
    goto _advance_failure;
  }
_readField_allocatedSlabIdxs:
  {
    _readState.beforeSubobject(iprot);
    this->__fbthrift_field_allocatedSlabIdxs = ::std::vector<::std::int32_t>();
    ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::list<::apache::thrift::type_class::integral>, ::std::vector<::std::int32_t>>::readWithContext(*iprot, this->__fbthrift_field_allocatedSlabIdxs, _readState);
    _readState.afterSubobject(iprot);
  }

  if (UNLIKELY(!_readState.advanceToNextField(
          iprot,
          11,
          12,
          apache::thrift::protocol::TType::T_LIST))) {
    goto _advance_failure;
  }
_readField_freeSlabIdxs:
  {
    _readState.beforeSubobject(iprot);
    this->__fbthrift_field_freeSlabIdxs = ::std::vector<::std::int32_t>();
    ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::list<::apache::thrift::type_class::integral>, ::std::vector<::std::int32_t>>::readWithContext(*iprot, this->__fbthrift_field_freeSlabIdxs, _readState);
    _readState.afterSubobject(iprot);
  }

  if (UNLIKELY(!_readState.advanceToNextField(
          iprot,
          12,
          0,
          apache::thrift::protocol::T_STOP))) {
    goto _advance_failure;
  }

_end:
  _readState.readStructEnd(iprot);

  return;

  goto _advance_failure; // Avoid compiler warnings about unused labels.
  _advance_failure:
  _readState.afterAdvanceFailure(iprot);
_loop:
  if (_readState.atStop()) {
    goto _end;
  }
  if (iprot->kUsesFieldNames()) {
    _readState.template fillFieldTraitsFromName<apache::thrift::detail::TccStructTraits<AllocationClassObject>>();
  }

  switch (_readState.fieldId) {
    case 1:
    {
      if (LIKELY(_readState.isCompatibleWithType(iprot, apache::thrift::protocol::TType::T_BYTE))) {
        goto _readField_classId;
      } else {
        goto _skip;
      }
    }
    case 2:
    {
      if (LIKELY(_readState.isCompatibleWithType(iprot, apache::thrift::protocol::TType::T_I64))) {
        goto _readField_allocationSize;
      } else {
        goto _skip;
      }
    }
    case 4:
    {
      if (LIKELY(_readState.isCompatibleWithType(iprot, apache::thrift::protocol::TType::T_I64))) {
        goto _readField_currOffset;
      } else {
        goto _skip;
      }
    }
    case 8:
    {
      if (LIKELY(_readState.isCompatibleWithType(iprot, apache::thrift::protocol::TType::T_BOOL))) {
        goto _readField_canAllocate;
      } else {
        goto _skip;
      }
    }
    case 9:
    {
      if (LIKELY(_readState.isCompatibleWithType(iprot, apache::thrift::protocol::TType::T_STRUCT))) {
        goto _readField_freedAllocationsObject;
      } else {
        goto _skip;
      }
    }
    case 10:
    {
      if (LIKELY(_readState.isCompatibleWithType(iprot, apache::thrift::protocol::TType::T_I32))) {
        goto _readField_currSlabIdx;
      } else {
        goto _skip;
      }
    }
    case 11:
    {
      if (LIKELY(_readState.isCompatibleWithType(iprot, apache::thrift::protocol::TType::T_LIST))) {
        goto _readField_allocatedSlabIdxs;
      } else {
        goto _skip;
      }
    }
    case 12:
    {
      if (LIKELY(_readState.isCompatibleWithType(iprot, apache::thrift::protocol::TType::T_LIST))) {
        goto _readField_freeSlabIdxs;
      } else {
        goto _skip;
      }
    }
    default:
    {
_skip:
      _readState.skip(iprot);
      _readState.readFieldEnd(iprot);
      _readState.readFieldBeginNoInline(iprot);
      goto _loop;
    }
  }
}

template <class Protocol_>
uint32_t AllocationClassObject::serializedSize(Protocol_ const* prot_) const {
  uint32_t xfer = 0;
  xfer += prot_->serializedStructSize("AllocationClassObject");
  {
    xfer += prot_->serializedFieldSize("classId", apache::thrift::protocol::TType::T_BYTE, 1);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int8_t>::serializedSize<false>(*prot_, this->__fbthrift_field_classId);
  }
  {
    xfer += prot_->serializedFieldSize("allocationSize", apache::thrift::protocol::TType::T_I64, 2);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int64_t>::serializedSize<false>(*prot_, this->__fbthrift_field_allocationSize);
  }
  {
    xfer += prot_->serializedFieldSize("currOffset", apache::thrift::protocol::TType::T_I64, 4);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int64_t>::serializedSize<false>(*prot_, this->__fbthrift_field_currOffset);
  }
  {
    xfer += prot_->serializedFieldSize("canAllocate", apache::thrift::protocol::TType::T_BOOL, 8);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, bool>::serializedSize<false>(*prot_, this->__fbthrift_field_canAllocate);
  }
  {
    xfer += prot_->serializedFieldSize("freedAllocationsObject", apache::thrift::protocol::TType::T_STRUCT, 9);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::structure, ::facebook::cachelib::serialization::SListObject>::serializedSize<false>(*prot_, this->__fbthrift_field_freedAllocationsObject);
  }
  {
    xfer += prot_->serializedFieldSize("currSlabIdx", apache::thrift::protocol::TType::T_I32, 10);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int32_t>::serializedSize<false>(*prot_, this->__fbthrift_field_currSlabIdx);
  }
  {
    xfer += prot_->serializedFieldSize("allocatedSlabIdxs", apache::thrift::protocol::TType::T_LIST, 11);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::list<::apache::thrift::type_class::integral>, ::std::vector<::std::int32_t>>::serializedSize<false>(*prot_, this->__fbthrift_field_allocatedSlabIdxs);
  }
  {
    xfer += prot_->serializedFieldSize("freeSlabIdxs", apache::thrift::protocol::TType::T_LIST, 12);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::list<::apache::thrift::type_class::integral>, ::std::vector<::std::int32_t>>::serializedSize<false>(*prot_, this->__fbthrift_field_freeSlabIdxs);
  }
  xfer += prot_->serializedSizeStop();
  return xfer;
}

template <class Protocol_>
uint32_t AllocationClassObject::serializedSizeZC(Protocol_ const* prot_) const {
  uint32_t xfer = 0;
  xfer += prot_->serializedStructSize("AllocationClassObject");
  {
    xfer += prot_->serializedFieldSize("classId", apache::thrift::protocol::TType::T_BYTE, 1);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int8_t>::serializedSize<false>(*prot_, this->__fbthrift_field_classId);
  }
  {
    xfer += prot_->serializedFieldSize("allocationSize", apache::thrift::protocol::TType::T_I64, 2);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int64_t>::serializedSize<false>(*prot_, this->__fbthrift_field_allocationSize);
  }
  {
    xfer += prot_->serializedFieldSize("currOffset", apache::thrift::protocol::TType::T_I64, 4);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int64_t>::serializedSize<false>(*prot_, this->__fbthrift_field_currOffset);
  }
  {
    xfer += prot_->serializedFieldSize("canAllocate", apache::thrift::protocol::TType::T_BOOL, 8);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, bool>::serializedSize<false>(*prot_, this->__fbthrift_field_canAllocate);
  }
  {
    xfer += prot_->serializedFieldSize("freedAllocationsObject", apache::thrift::protocol::TType::T_STRUCT, 9);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::structure, ::facebook::cachelib::serialization::SListObject>::serializedSize<true>(*prot_, this->__fbthrift_field_freedAllocationsObject);
  }
  {
    xfer += prot_->serializedFieldSize("currSlabIdx", apache::thrift::protocol::TType::T_I32, 10);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int32_t>::serializedSize<false>(*prot_, this->__fbthrift_field_currSlabIdx);
  }
  {
    xfer += prot_->serializedFieldSize("allocatedSlabIdxs", apache::thrift::protocol::TType::T_LIST, 11);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::list<::apache::thrift::type_class::integral>, ::std::vector<::std::int32_t>>::serializedSize<false>(*prot_, this->__fbthrift_field_allocatedSlabIdxs);
  }
  {
    xfer += prot_->serializedFieldSize("freeSlabIdxs", apache::thrift::protocol::TType::T_LIST, 12);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::list<::apache::thrift::type_class::integral>, ::std::vector<::std::int32_t>>::serializedSize<false>(*prot_, this->__fbthrift_field_freeSlabIdxs);
  }
  xfer += prot_->serializedSizeStop();
  return xfer;
}

template <class Protocol_>
uint32_t AllocationClassObject::write(Protocol_* prot_) const {
  // If the protocol requests field-id-ascending order and it differs from
  // the codegen serialization order, delegate to the generic StructEncode
  // which respects FieldOrder::IdAscending.
  if constexpr (requires { prot_->fieldOrder(); }) {
    if (prot_->fieldOrder() == ::apache::thrift::FieldOrder::IdAscending) {
      return ::apache::thrift::op::detail::StructEncode<AllocationClassObject>{}(*prot_, *this);
    }
  }
  uint32_t xfer = 0;
  xfer += prot_->writeStructBegin("AllocationClassObject");
  bool previousFieldHasValue = true;
  {
    constexpr int16_t kPrevFieldId = 0;
    xfer += ::apache::thrift::detail::writeFieldBegin<apache::thrift::protocol::TType::T_BYTE, 1, kPrevFieldId>(*prot_, "classId", previousFieldHasValue);
    previousFieldHasValue = true;
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int8_t>::write(*prot_, this->__fbthrift_field_classId);
    xfer += prot_->writeFieldEnd();
  }
  {
    constexpr int16_t kPrevFieldId = 1;
    xfer += ::apache::thrift::detail::writeFieldBegin<apache::thrift::protocol::TType::T_I64, 2, kPrevFieldId>(*prot_, "allocationSize", previousFieldHasValue);
    previousFieldHasValue = true;
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int64_t>::write(*prot_, this->__fbthrift_field_allocationSize);
    xfer += prot_->writeFieldEnd();
  }
  {
    constexpr int16_t kPrevFieldId = 2;
    xfer += ::apache::thrift::detail::writeFieldBegin<apache::thrift::protocol::TType::T_I64, 4, kPrevFieldId>(*prot_, "currOffset", previousFieldHasValue);
    previousFieldHasValue = true;
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int64_t>::write(*prot_, this->__fbthrift_field_currOffset);
    xfer += prot_->writeFieldEnd();
  }
  {
    constexpr int16_t kPrevFieldId = 4;
    xfer += ::apache::thrift::detail::writeFieldBegin<apache::thrift::protocol::TType::T_BOOL, 8, kPrevFieldId>(*prot_, "canAllocate", previousFieldHasValue);
    previousFieldHasValue = true;
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, bool>::write(*prot_, this->__fbthrift_field_canAllocate);
    xfer += prot_->writeFieldEnd();
  }
  {
    constexpr int16_t kPrevFieldId = 8;
    xfer += ::apache::thrift::detail::writeFieldBegin<apache::thrift::protocol::TType::T_STRUCT, 9, kPrevFieldId>(*prot_, "freedAllocationsObject", previousFieldHasValue);
    previousFieldHasValue = true;
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::structure, ::facebook::cachelib::serialization::SListObject>::write(*prot_, this->__fbthrift_field_freedAllocationsObject);
    xfer += prot_->writeFieldEnd();
  }
  {
    constexpr int16_t kPrevFieldId = 9;
    xfer += ::apache::thrift::detail::writeFieldBegin<apache::thrift::protocol::TType::T_I32, 10, kPrevFieldId>(*prot_, "currSlabIdx", previousFieldHasValue);
    previousFieldHasValue = true;
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int32_t>::write(*prot_, this->__fbthrift_field_currSlabIdx);
    xfer += prot_->writeFieldEnd();
  }
  {
    constexpr int16_t kPrevFieldId = 10;
    xfer += ::apache::thrift::detail::writeFieldBegin<apache::thrift::protocol::TType::T_LIST, 11, kPrevFieldId>(*prot_, "allocatedSlabIdxs", previousFieldHasValue);
    previousFieldHasValue = true;
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::list<::apache::thrift::type_class::integral>, ::std::vector<::std::int32_t>>::write(*prot_, this->__fbthrift_field_allocatedSlabIdxs);
    xfer += prot_->writeFieldEnd();
  }
  {
    constexpr int16_t kPrevFieldId = 11;
    xfer += ::apache::thrift::detail::writeFieldBegin<apache::thrift::protocol::TType::T_LIST, 12, kPrevFieldId>(*prot_, "freeSlabIdxs", previousFieldHasValue);
    previousFieldHasValue = true;
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::list<::apache::thrift::type_class::integral>, ::std::vector<::std::int32_t>>::write(*prot_, this->__fbthrift_field_freeSlabIdxs);
    xfer += prot_->writeFieldEnd();
  }
  xfer += prot_->writeFieldStop();
  xfer += prot_->writeStructEnd();
  return xfer;
}

extern template void AllocationClassObject::readNoXfer<>(apache::thrift::BinaryProtocolReader*);
extern template uint32_t AllocationClassObject::write<>(apache::thrift::BinaryProtocolWriter*) const;
extern template uint32_t AllocationClassObject::serializedSize<>(apache::thrift::BinaryProtocolWriter const*) const;
extern template uint32_t AllocationClassObject::serializedSizeZC<>(apache::thrift::BinaryProtocolWriter const*) const;
extern template void AllocationClassObject::readNoXfer<>(apache::thrift::CompactProtocolReader*);
extern template uint32_t AllocationClassObject::write<>(apache::thrift::CompactProtocolWriter*) const;
extern template uint32_t AllocationClassObject::serializedSize<>(apache::thrift::CompactProtocolWriter const*) const;
extern template uint32_t AllocationClassObject::serializedSizeZC<>(apache::thrift::CompactProtocolWriter const*) const;


template <class Protocol_>
void MemoryPoolObject::readNoXfer(Protocol_* iprot) {
  apache::thrift::detail::ProtocolReaderStructReadState<Protocol_> _readState;

  _readState.readStructBegin(iprot);

  using apache::thrift::TProtocolException;


  if (UNLIKELY(!_readState.advanceToNextField(
          iprot,
          0,
          1,
          apache::thrift::protocol::TType::T_BYTE))) {
    goto _advance_failure;
  }
_readField_id:
  {
    ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int8_t>::readWithContext(*iprot, this->__fbthrift_field_id, _readState);
  }

  if (UNLIKELY(!_readState.advanceToNextField(
          iprot,
          1,
          2,
          apache::thrift::protocol::TType::T_I64))) {
    goto _advance_failure;
  }
_readField_maxSize:
  {
    ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int64_t>::readWithContext(*iprot, this->__fbthrift_field_maxSize, _readState);
  }

  if (UNLIKELY(!_readState.advanceToNextField(
          iprot,
          2,
          3,
          apache::thrift::protocol::TType::T_I64))) {
    goto _advance_failure;
  }
_readField_currSlabAllocSize:
  {
    ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int64_t>::readWithContext(*iprot, this->__fbthrift_field_currSlabAllocSize, _readState);
  }

  if (UNLIKELY(!_readState.advanceToNextField(
          iprot,
          3,
          4,
          apache::thrift::protocol::TType::T_I64))) {
    goto _advance_failure;
  }
_readField_currAllocSize:
  {
    ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int64_t>::readWithContext(*iprot, this->__fbthrift_field_currAllocSize, _readState);
  }

  if (UNLIKELY(!_readState.advanceToNextField(
          iprot,
          4,
          6,
          apache::thrift::protocol::TType::T_LIST))) {
    goto _advance_failure;
  }
_readField_acSizes:
  {
    _readState.beforeSubobject(iprot);
    this->__fbthrift_field_acSizes = ::std::vector<::std::int64_t>();
    ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::list<::apache::thrift::type_class::integral>, ::std::vector<::std::int64_t>>::readWithContext(*iprot, this->__fbthrift_field_acSizes, _readState);
    _readState.afterSubobject(iprot);
  }

  if (UNLIKELY(!_readState.advanceToNextField(
          iprot,
          6,
          7,
          apache::thrift::protocol::TType::T_LIST))) {
    goto _advance_failure;
  }
_readField_ac:
  {
    _readState.beforeSubobject(iprot);
    this->__fbthrift_field_ac = ::std::vector<::facebook::cachelib::serialization::AllocationClassObject>();
    ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::list<::apache::thrift::type_class::structure>, ::std::vector<::facebook::cachelib::serialization::AllocationClassObject>>::readWithContext(*iprot, this->__fbthrift_field_ac, _readState);
    _readState.afterSubobject(iprot);
  }

  if (UNLIKELY(!_readState.advanceToNextField(
          iprot,
          7,
          8,
          apache::thrift::protocol::TType::T_I64))) {
    goto _advance_failure;
  }
_readField_numSlabResize:
  {
    ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int64_t>::readWithContext(*iprot, this->__fbthrift_field_numSlabResize, _readState);
  }
 this->__isset.set(0, true);

  if (UNLIKELY(!_readState.advanceToNextField(
          iprot,
          8,
          9,
          apache::thrift::protocol::TType::T_I64))) {
    goto _advance_failure;
  }
_readField_numSlabRebalance:
  {
    ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int64_t>::readWithContext(*iprot, this->__fbthrift_field_numSlabRebalance, _readState);
  }
 this->__isset.set(1, true);

  if (UNLIKELY(!_readState.advanceToNextField(
          iprot,
          9,
          10,
          apache::thrift::protocol::TType::T_LIST))) {
    goto _advance_failure;
  }
_readField_freeSlabIdxs:
  {
    _readState.beforeSubobject(iprot);
    this->__fbthrift_field_freeSlabIdxs = ::std::vector<::std::int32_t>();
    ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::list<::apache::thrift::type_class::integral>, ::std::vector<::std::int32_t>>::readWithContext(*iprot, this->__fbthrift_field_freeSlabIdxs, _readState);
    _readState.afterSubobject(iprot);
  }

  if (UNLIKELY(!_readState.advanceToNextField(
          iprot,
          10,
          11,
          apache::thrift::protocol::TType::T_I64))) {
    goto _advance_failure;
  }
_readField_numSlabsAdvised:
  {
    ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int64_t>::readWithContext(*iprot, this->__fbthrift_field_numSlabsAdvised, _readState);
  }
 this->__isset.set(2, true);

  if (UNLIKELY(!_readState.advanceToNextField(
          iprot,
          11,
          0,
          apache::thrift::protocol::T_STOP))) {
    goto _advance_failure;
  }

_end:
  _readState.readStructEnd(iprot);

  return;

  goto _advance_failure; // Avoid compiler warnings about unused labels.
  _advance_failure:
  _readState.afterAdvanceFailure(iprot);
_loop:
  if (_readState.atStop()) {
    goto _end;
  }
  if (iprot->kUsesFieldNames()) {
    _readState.template fillFieldTraitsFromName<apache::thrift::detail::TccStructTraits<MemoryPoolObject>>();
  }

  switch (_readState.fieldId) {
    case 1:
    {
      if (LIKELY(_readState.isCompatibleWithType(iprot, apache::thrift::protocol::TType::T_BYTE))) {
        goto _readField_id;
      } else {
        goto _skip;
      }
    }
    case 2:
    {
      if (LIKELY(_readState.isCompatibleWithType(iprot, apache::thrift::protocol::TType::T_I64))) {
        goto _readField_maxSize;
      } else {
        goto _skip;
      }
    }
    case 3:
    {
      if (LIKELY(_readState.isCompatibleWithType(iprot, apache::thrift::protocol::TType::T_I64))) {
        goto _readField_currSlabAllocSize;
      } else {
        goto _skip;
      }
    }
    case 4:
    {
      if (LIKELY(_readState.isCompatibleWithType(iprot, apache::thrift::protocol::TType::T_I64))) {
        goto _readField_currAllocSize;
      } else {
        goto _skip;
      }
    }
    case 6:
    {
      if (LIKELY(_readState.isCompatibleWithType(iprot, apache::thrift::protocol::TType::T_LIST))) {
        goto _readField_acSizes;
      } else {
        goto _skip;
      }
    }
    case 7:
    {
      if (LIKELY(_readState.isCompatibleWithType(iprot, apache::thrift::protocol::TType::T_LIST))) {
        goto _readField_ac;
      } else {
        goto _skip;
      }
    }
    case 8:
    {
      if (LIKELY(_readState.isCompatibleWithType(iprot, apache::thrift::protocol::TType::T_I64))) {
        goto _readField_numSlabResize;
      } else {
        goto _skip;
      }
    }
    case 9:
    {
      if (LIKELY(_readState.isCompatibleWithType(iprot, apache::thrift::protocol::TType::T_I64))) {
        goto _readField_numSlabRebalance;
      } else {
        goto _skip;
      }
    }
    case 10:
    {
      if (LIKELY(_readState.isCompatibleWithType(iprot, apache::thrift::protocol::TType::T_LIST))) {
        goto _readField_freeSlabIdxs;
      } else {
        goto _skip;
      }
    }
    case 11:
    {
      if (LIKELY(_readState.isCompatibleWithType(iprot, apache::thrift::protocol::TType::T_I64))) {
        goto _readField_numSlabsAdvised;
      } else {
        goto _skip;
      }
    }
    default:
    {
_skip:
      _readState.skip(iprot);
      _readState.readFieldEnd(iprot);
      _readState.readFieldBeginNoInline(iprot);
      goto _loop;
    }
  }
}

template <class Protocol_>
uint32_t MemoryPoolObject::serializedSize(Protocol_ const* prot_) const {
  uint32_t xfer = 0;
  xfer += prot_->serializedStructSize("MemoryPoolObject");
  {
    xfer += prot_->serializedFieldSize("id", apache::thrift::protocol::TType::T_BYTE, 1);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int8_t>::serializedSize<false>(*prot_, this->__fbthrift_field_id);
  }
  {
    xfer += prot_->serializedFieldSize("maxSize", apache::thrift::protocol::TType::T_I64, 2);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int64_t>::serializedSize<false>(*prot_, this->__fbthrift_field_maxSize);
  }
  {
    xfer += prot_->serializedFieldSize("currSlabAllocSize", apache::thrift::protocol::TType::T_I64, 3);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int64_t>::serializedSize<false>(*prot_, this->__fbthrift_field_currSlabAllocSize);
  }
  {
    xfer += prot_->serializedFieldSize("currAllocSize", apache::thrift::protocol::TType::T_I64, 4);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int64_t>::serializedSize<false>(*prot_, this->__fbthrift_field_currAllocSize);
  }
  {
    xfer += prot_->serializedFieldSize("acSizes", apache::thrift::protocol::TType::T_LIST, 6);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::list<::apache::thrift::type_class::integral>, ::std::vector<::std::int64_t>>::serializedSize<false>(*prot_, this->__fbthrift_field_acSizes);
  }
  {
    xfer += prot_->serializedFieldSize("ac", apache::thrift::protocol::TType::T_LIST, 7);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::list<::apache::thrift::type_class::structure>, ::std::vector<::facebook::cachelib::serialization::AllocationClassObject>>::serializedSize<false>(*prot_, this->__fbthrift_field_ac);
  }
  {
    xfer += prot_->serializedFieldSize("numSlabResize", apache::thrift::protocol::TType::T_I64, 8);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int64_t>::serializedSize<false>(*prot_, this->__fbthrift_field_numSlabResize);
  }
  {
    xfer += prot_->serializedFieldSize("numSlabRebalance", apache::thrift::protocol::TType::T_I64, 9);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int64_t>::serializedSize<false>(*prot_, this->__fbthrift_field_numSlabRebalance);
  }
  {
    xfer += prot_->serializedFieldSize("freeSlabIdxs", apache::thrift::protocol::TType::T_LIST, 10);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::list<::apache::thrift::type_class::integral>, ::std::vector<::std::int32_t>>::serializedSize<false>(*prot_, this->__fbthrift_field_freeSlabIdxs);
  }
  {
    xfer += prot_->serializedFieldSize("numSlabsAdvised", apache::thrift::protocol::TType::T_I64, 11);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int64_t>::serializedSize<false>(*prot_, this->__fbthrift_field_numSlabsAdvised);
  }
  xfer += prot_->serializedSizeStop();
  return xfer;
}

template <class Protocol_>
uint32_t MemoryPoolObject::serializedSizeZC(Protocol_ const* prot_) const {
  uint32_t xfer = 0;
  xfer += prot_->serializedStructSize("MemoryPoolObject");
  {
    xfer += prot_->serializedFieldSize("id", apache::thrift::protocol::TType::T_BYTE, 1);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int8_t>::serializedSize<false>(*prot_, this->__fbthrift_field_id);
  }
  {
    xfer += prot_->serializedFieldSize("maxSize", apache::thrift::protocol::TType::T_I64, 2);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int64_t>::serializedSize<false>(*prot_, this->__fbthrift_field_maxSize);
  }
  {
    xfer += prot_->serializedFieldSize("currSlabAllocSize", apache::thrift::protocol::TType::T_I64, 3);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int64_t>::serializedSize<false>(*prot_, this->__fbthrift_field_currSlabAllocSize);
  }
  {
    xfer += prot_->serializedFieldSize("currAllocSize", apache::thrift::protocol::TType::T_I64, 4);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int64_t>::serializedSize<false>(*prot_, this->__fbthrift_field_currAllocSize);
  }
  {
    xfer += prot_->serializedFieldSize("acSizes", apache::thrift::protocol::TType::T_LIST, 6);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::list<::apache::thrift::type_class::integral>, ::std::vector<::std::int64_t>>::serializedSize<false>(*prot_, this->__fbthrift_field_acSizes);
  }
  {
    xfer += prot_->serializedFieldSize("ac", apache::thrift::protocol::TType::T_LIST, 7);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::list<::apache::thrift::type_class::structure>, ::std::vector<::facebook::cachelib::serialization::AllocationClassObject>>::serializedSize<true>(*prot_, this->__fbthrift_field_ac);
  }
  {
    xfer += prot_->serializedFieldSize("numSlabResize", apache::thrift::protocol::TType::T_I64, 8);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int64_t>::serializedSize<false>(*prot_, this->__fbthrift_field_numSlabResize);
  }
  {
    xfer += prot_->serializedFieldSize("numSlabRebalance", apache::thrift::protocol::TType::T_I64, 9);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int64_t>::serializedSize<false>(*prot_, this->__fbthrift_field_numSlabRebalance);
  }
  {
    xfer += prot_->serializedFieldSize("freeSlabIdxs", apache::thrift::protocol::TType::T_LIST, 10);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::list<::apache::thrift::type_class::integral>, ::std::vector<::std::int32_t>>::serializedSize<false>(*prot_, this->__fbthrift_field_freeSlabIdxs);
  }
  {
    xfer += prot_->serializedFieldSize("numSlabsAdvised", apache::thrift::protocol::TType::T_I64, 11);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int64_t>::serializedSize<false>(*prot_, this->__fbthrift_field_numSlabsAdvised);
  }
  xfer += prot_->serializedSizeStop();
  return xfer;
}

template <class Protocol_>
uint32_t MemoryPoolObject::write(Protocol_* prot_) const {
  // If the protocol requests field-id-ascending order and it differs from
  // the codegen serialization order, delegate to the generic StructEncode
  // which respects FieldOrder::IdAscending.
  if constexpr (requires { prot_->fieldOrder(); }) {
    if (prot_->fieldOrder() == ::apache::thrift::FieldOrder::IdAscending) {
      return ::apache::thrift::op::detail::StructEncode<MemoryPoolObject>{}(*prot_, *this);
    }
  }
  uint32_t xfer = 0;
  xfer += prot_->writeStructBegin("MemoryPoolObject");
  bool previousFieldHasValue = true;
  {
    constexpr int16_t kPrevFieldId = 0;
    xfer += ::apache::thrift::detail::writeFieldBegin<apache::thrift::protocol::TType::T_BYTE, 1, kPrevFieldId>(*prot_, "id", previousFieldHasValue);
    previousFieldHasValue = true;
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int8_t>::write(*prot_, this->__fbthrift_field_id);
    xfer += prot_->writeFieldEnd();
  }
  {
    constexpr int16_t kPrevFieldId = 1;
    xfer += ::apache::thrift::detail::writeFieldBegin<apache::thrift::protocol::TType::T_I64, 2, kPrevFieldId>(*prot_, "maxSize", previousFieldHasValue);
    previousFieldHasValue = true;
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int64_t>::write(*prot_, this->__fbthrift_field_maxSize);
    xfer += prot_->writeFieldEnd();
  }
  {
    constexpr int16_t kPrevFieldId = 2;
    xfer += ::apache::thrift::detail::writeFieldBegin<apache::thrift::protocol::TType::T_I64, 3, kPrevFieldId>(*prot_, "currSlabAllocSize", previousFieldHasValue);
    previousFieldHasValue = true;
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int64_t>::write(*prot_, this->__fbthrift_field_currSlabAllocSize);
    xfer += prot_->writeFieldEnd();
  }
  {
    constexpr int16_t kPrevFieldId = 3;
    xfer += ::apache::thrift::detail::writeFieldBegin<apache::thrift::protocol::TType::T_I64, 4, kPrevFieldId>(*prot_, "currAllocSize", previousFieldHasValue);
    previousFieldHasValue = true;
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int64_t>::write(*prot_, this->__fbthrift_field_currAllocSize);
    xfer += prot_->writeFieldEnd();
  }
  {
    constexpr int16_t kPrevFieldId = 4;
    xfer += ::apache::thrift::detail::writeFieldBegin<apache::thrift::protocol::TType::T_LIST, 6, kPrevFieldId>(*prot_, "acSizes", previousFieldHasValue);
    previousFieldHasValue = true;
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::list<::apache::thrift::type_class::integral>, ::std::vector<::std::int64_t>>::write(*prot_, this->__fbthrift_field_acSizes);
    xfer += prot_->writeFieldEnd();
  }
  {
    constexpr int16_t kPrevFieldId = 6;
    xfer += ::apache::thrift::detail::writeFieldBegin<apache::thrift::protocol::TType::T_LIST, 7, kPrevFieldId>(*prot_, "ac", previousFieldHasValue);
    previousFieldHasValue = true;
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::list<::apache::thrift::type_class::structure>, ::std::vector<::facebook::cachelib::serialization::AllocationClassObject>>::write(*prot_, this->__fbthrift_field_ac);
    xfer += prot_->writeFieldEnd();
  }
  {
    constexpr int16_t kPrevFieldId = 7;
    xfer += ::apache::thrift::detail::writeFieldBegin<apache::thrift::protocol::TType::T_I64, 8, kPrevFieldId>(*prot_, "numSlabResize", previousFieldHasValue);
    previousFieldHasValue = true;
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int64_t>::write(*prot_, this->__fbthrift_field_numSlabResize);
    xfer += prot_->writeFieldEnd();
  }
  {
    constexpr int16_t kPrevFieldId = 8;
    xfer += ::apache::thrift::detail::writeFieldBegin<apache::thrift::protocol::TType::T_I64, 9, kPrevFieldId>(*prot_, "numSlabRebalance", previousFieldHasValue);
    previousFieldHasValue = true;
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int64_t>::write(*prot_, this->__fbthrift_field_numSlabRebalance);
    xfer += prot_->writeFieldEnd();
  }
  {
    constexpr int16_t kPrevFieldId = 9;
    xfer += ::apache::thrift::detail::writeFieldBegin<apache::thrift::protocol::TType::T_LIST, 10, kPrevFieldId>(*prot_, "freeSlabIdxs", previousFieldHasValue);
    previousFieldHasValue = true;
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::list<::apache::thrift::type_class::integral>, ::std::vector<::std::int32_t>>::write(*prot_, this->__fbthrift_field_freeSlabIdxs);
    xfer += prot_->writeFieldEnd();
  }
  {
    constexpr int16_t kPrevFieldId = 10;
    xfer += ::apache::thrift::detail::writeFieldBegin<apache::thrift::protocol::TType::T_I64, 11, kPrevFieldId>(*prot_, "numSlabsAdvised", previousFieldHasValue);
    previousFieldHasValue = true;
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int64_t>::write(*prot_, this->__fbthrift_field_numSlabsAdvised);
    xfer += prot_->writeFieldEnd();
  }
  xfer += prot_->writeFieldStop();
  xfer += prot_->writeStructEnd();
  return xfer;
}

extern template void MemoryPoolObject::readNoXfer<>(apache::thrift::BinaryProtocolReader*);
extern template uint32_t MemoryPoolObject::write<>(apache::thrift::BinaryProtocolWriter*) const;
extern template uint32_t MemoryPoolObject::serializedSize<>(apache::thrift::BinaryProtocolWriter const*) const;
extern template uint32_t MemoryPoolObject::serializedSizeZC<>(apache::thrift::BinaryProtocolWriter const*) const;
extern template void MemoryPoolObject::readNoXfer<>(apache::thrift::CompactProtocolReader*);
extern template uint32_t MemoryPoolObject::write<>(apache::thrift::CompactProtocolWriter*) const;
extern template uint32_t MemoryPoolObject::serializedSize<>(apache::thrift::CompactProtocolWriter const*) const;
extern template uint32_t MemoryPoolObject::serializedSizeZC<>(apache::thrift::CompactProtocolWriter const*) const;


template <class Protocol_>
void MemoryPoolManagerObject::readNoXfer(Protocol_* iprot) {
  apache::thrift::detail::ProtocolReaderStructReadState<Protocol_> _readState;

  _readState.readStructBegin(iprot);

  using apache::thrift::TProtocolException;


  if (UNLIKELY(!_readState.advanceToNextField(
          iprot,
          0,
          1,
          apache::thrift::protocol::TType::T_LIST))) {
    goto _advance_failure;
  }
_readField_pools:
  {
    _readState.beforeSubobject(iprot);
    this->__fbthrift_field_pools = ::std::vector<::facebook::cachelib::serialization::MemoryPoolObject>();
    ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::list<::apache::thrift::type_class::structure>, ::std::vector<::facebook::cachelib::serialization::MemoryPoolObject>>::readWithContext(*iprot, this->__fbthrift_field_pools, _readState);
    _readState.afterSubobject(iprot);
  }
 this->__isset.set(0, true);

  if (UNLIKELY(!_readState.advanceToNextField(
          iprot,
          1,
          2,
          apache::thrift::protocol::TType::T_MAP))) {
    goto _advance_failure;
  }
_readField_poolsByName:
  {
    _readState.beforeSubobject(iprot);
    this->__fbthrift_field_poolsByName = ::std::map<::std::string, ::std::int8_t>();
    ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::map<::apache::thrift::type_class::string, ::apache::thrift::type_class::integral>, ::std::map<::std::string, ::std::int8_t>>::readWithContext(*iprot, this->__fbthrift_field_poolsByName, _readState);
    _readState.afterSubobject(iprot);
  }
 this->__isset.set(1, true);

  if (UNLIKELY(!_readState.advanceToNextField(
          iprot,
          2,
          3,
          apache::thrift::protocol::TType::T_BYTE))) {
    goto _advance_failure;
  }
_readField_nextPoolId:
  {
    ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int8_t>::readWithContext(*iprot, this->__fbthrift_field_nextPoolId, _readState);
  }
 this->__isset.set(2, true);

  if (UNLIKELY(!_readState.advanceToNextField(
          iprot,
          3,
          0,
          apache::thrift::protocol::T_STOP))) {
    goto _advance_failure;
  }

_end:
  _readState.readStructEnd(iprot);

  return;

  goto _advance_failure; // Avoid compiler warnings about unused labels.
  _advance_failure:
  _readState.afterAdvanceFailure(iprot);
_loop:
  if (_readState.atStop()) {
    goto _end;
  }
  if (iprot->kUsesFieldNames()) {
    _readState.template fillFieldTraitsFromName<apache::thrift::detail::TccStructTraits<MemoryPoolManagerObject>>();
  }

  switch (_readState.fieldId) {
    case 1:
    {
      if (LIKELY(_readState.isCompatibleWithType(iprot, apache::thrift::protocol::TType::T_LIST))) {
        goto _readField_pools;
      } else {
        goto _skip;
      }
    }
    case 2:
    {
      if (LIKELY(_readState.isCompatibleWithType(iprot, apache::thrift::protocol::TType::T_MAP))) {
        goto _readField_poolsByName;
      } else {
        goto _skip;
      }
    }
    case 3:
    {
      if (LIKELY(_readState.isCompatibleWithType(iprot, apache::thrift::protocol::TType::T_BYTE))) {
        goto _readField_nextPoolId;
      } else {
        goto _skip;
      }
    }
    default:
    {
_skip:
      _readState.skip(iprot);
      _readState.readFieldEnd(iprot);
      _readState.readFieldBeginNoInline(iprot);
      goto _loop;
    }
  }
}

template <class Protocol_>
uint32_t MemoryPoolManagerObject::serializedSize(Protocol_ const* prot_) const {
  uint32_t xfer = 0;
  xfer += prot_->serializedStructSize("MemoryPoolManagerObject");
  {
    xfer += prot_->serializedFieldSize("pools", apache::thrift::protocol::TType::T_LIST, 1);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::list<::apache::thrift::type_class::structure>, ::std::vector<::facebook::cachelib::serialization::MemoryPoolObject>>::serializedSize<false>(*prot_, this->__fbthrift_field_pools);
  }
  {
    xfer += prot_->serializedFieldSize("poolsByName", apache::thrift::protocol::TType::T_MAP, 2);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::map<::apache::thrift::type_class::string, ::apache::thrift::type_class::integral>, ::std::map<::std::string, ::std::int8_t>>::serializedSize<false>(*prot_, this->__fbthrift_field_poolsByName);
  }
  {
    xfer += prot_->serializedFieldSize("nextPoolId", apache::thrift::protocol::TType::T_BYTE, 3);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int8_t>::serializedSize<false>(*prot_, this->__fbthrift_field_nextPoolId);
  }
  xfer += prot_->serializedSizeStop();
  return xfer;
}

template <class Protocol_>
uint32_t MemoryPoolManagerObject::serializedSizeZC(Protocol_ const* prot_) const {
  uint32_t xfer = 0;
  xfer += prot_->serializedStructSize("MemoryPoolManagerObject");
  {
    xfer += prot_->serializedFieldSize("pools", apache::thrift::protocol::TType::T_LIST, 1);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::list<::apache::thrift::type_class::structure>, ::std::vector<::facebook::cachelib::serialization::MemoryPoolObject>>::serializedSize<true>(*prot_, this->__fbthrift_field_pools);
  }
  {
    xfer += prot_->serializedFieldSize("poolsByName", apache::thrift::protocol::TType::T_MAP, 2);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::map<::apache::thrift::type_class::string, ::apache::thrift::type_class::integral>, ::std::map<::std::string, ::std::int8_t>>::serializedSize<false>(*prot_, this->__fbthrift_field_poolsByName);
  }
  {
    xfer += prot_->serializedFieldSize("nextPoolId", apache::thrift::protocol::TType::T_BYTE, 3);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int8_t>::serializedSize<false>(*prot_, this->__fbthrift_field_nextPoolId);
  }
  xfer += prot_->serializedSizeStop();
  return xfer;
}

template <class Protocol_>
uint32_t MemoryPoolManagerObject::write(Protocol_* prot_) const {
  // If the protocol requests field-id-ascending order and it differs from
  // the codegen serialization order, delegate to the generic StructEncode
  // which respects FieldOrder::IdAscending.
  if constexpr (requires { prot_->fieldOrder(); }) {
    if (prot_->fieldOrder() == ::apache::thrift::FieldOrder::IdAscending) {
      return ::apache::thrift::op::detail::StructEncode<MemoryPoolManagerObject>{}(*prot_, *this);
    }
  }
  uint32_t xfer = 0;
  xfer += prot_->writeStructBegin("MemoryPoolManagerObject");
  bool previousFieldHasValue = true;
  {
    constexpr int16_t kPrevFieldId = 0;
    xfer += ::apache::thrift::detail::writeFieldBegin<apache::thrift::protocol::TType::T_LIST, 1, kPrevFieldId>(*prot_, "pools", previousFieldHasValue);
    previousFieldHasValue = true;
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::list<::apache::thrift::type_class::structure>, ::std::vector<::facebook::cachelib::serialization::MemoryPoolObject>>::write(*prot_, this->__fbthrift_field_pools);
    xfer += prot_->writeFieldEnd();
  }
  {
    constexpr int16_t kPrevFieldId = 1;
    xfer += ::apache::thrift::detail::writeFieldBegin<apache::thrift::protocol::TType::T_MAP, 2, kPrevFieldId>(*prot_, "poolsByName", previousFieldHasValue);
    previousFieldHasValue = true;
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::map<::apache::thrift::type_class::string, ::apache::thrift::type_class::integral>, ::std::map<::std::string, ::std::int8_t>>::write(*prot_, this->__fbthrift_field_poolsByName);
    xfer += prot_->writeFieldEnd();
  }
  {
    constexpr int16_t kPrevFieldId = 2;
    xfer += ::apache::thrift::detail::writeFieldBegin<apache::thrift::protocol::TType::T_BYTE, 3, kPrevFieldId>(*prot_, "nextPoolId", previousFieldHasValue);
    previousFieldHasValue = true;
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, ::std::int8_t>::write(*prot_, this->__fbthrift_field_nextPoolId);
    xfer += prot_->writeFieldEnd();
  }
  xfer += prot_->writeFieldStop();
  xfer += prot_->writeStructEnd();
  return xfer;
}

extern template void MemoryPoolManagerObject::readNoXfer<>(apache::thrift::BinaryProtocolReader*);
extern template uint32_t MemoryPoolManagerObject::write<>(apache::thrift::BinaryProtocolWriter*) const;
extern template uint32_t MemoryPoolManagerObject::serializedSize<>(apache::thrift::BinaryProtocolWriter const*) const;
extern template uint32_t MemoryPoolManagerObject::serializedSizeZC<>(apache::thrift::BinaryProtocolWriter const*) const;
extern template void MemoryPoolManagerObject::readNoXfer<>(apache::thrift::CompactProtocolReader*);
extern template uint32_t MemoryPoolManagerObject::write<>(apache::thrift::CompactProtocolWriter*) const;
extern template uint32_t MemoryPoolManagerObject::serializedSize<>(apache::thrift::CompactProtocolWriter const*) const;
extern template uint32_t MemoryPoolManagerObject::serializedSizeZC<>(apache::thrift::CompactProtocolWriter const*) const;


template <class Protocol_>
void MemoryAllocatorObject::readNoXfer(Protocol_* iprot) {
  apache::thrift::detail::ProtocolReaderStructReadState<Protocol_> _readState;

  _readState.readStructBegin(iprot);

  using apache::thrift::TProtocolException;


  if (UNLIKELY(!_readState.advanceToNextField(
          iprot,
          0,
          1,
          apache::thrift::protocol::TType::T_SET))) {
    goto _advance_failure;
  }
_readField_allocSizes:
  {
    _readState.beforeSubobject(iprot);
    this->__fbthrift_field_allocSizes = ::std::set<::std::int64_t>();
    ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::set<::apache::thrift::type_class::integral>, ::std::set<::std::int64_t>>::readWithContext(*iprot, this->__fbthrift_field_allocSizes, _readState);
    _readState.afterSubobject(iprot);
  }

  if (UNLIKELY(!_readState.advanceToNextField(
          iprot,
          1,
          4,
          apache::thrift::protocol::TType::T_BOOL))) {
    goto _advance_failure;
  }
_readField_enableZeroedSlabAllocs:
  {
    ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, bool>::readWithContext(*iprot, this->__fbthrift_field_enableZeroedSlabAllocs, _readState);
  }

  if (UNLIKELY(!_readState.advanceToNextField(
          iprot,
          4,
          5,
          apache::thrift::protocol::TType::T_BOOL))) {
    goto _advance_failure;
  }
_readField_lockMemory:
  {
    ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, bool>::readWithContext(*iprot, this->__fbthrift_field_lockMemory, _readState);
  }
 this->__isset.set(0, true);

  if (UNLIKELY(!_readState.advanceToNextField(
          iprot,
          5,
          2,
          apache::thrift::protocol::TType::T_STRUCT))) {
    goto _advance_failure;
  }
_readField_slabAllocator:
  {
    _readState.beforeSubobject(iprot);
    ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::structure, ::facebook::cachelib::serialization::SlabAllocatorObject>::readWithContext(*iprot, this->__fbthrift_field_slabAllocator, _readState);
    _readState.afterSubobject(iprot);
  }

  if (UNLIKELY(!_readState.advanceToNextField(
          iprot,
          2,
          3,
          apache::thrift::protocol::TType::T_STRUCT))) {
    goto _advance_failure;
  }
_readField_memoryPoolManager:
  {
    _readState.beforeSubobject(iprot);
    ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::structure, ::facebook::cachelib::serialization::MemoryPoolManagerObject>::readWithContext(*iprot, this->__fbthrift_field_memoryPoolManager, _readState);
    _readState.afterSubobject(iprot);
  }

  if (UNLIKELY(!_readState.advanceToNextField(
          iprot,
          3,
          0,
          apache::thrift::protocol::T_STOP))) {
    goto _advance_failure;
  }

_end:
  _readState.readStructEnd(iprot);

  return;

  goto _advance_failure; // Avoid compiler warnings about unused labels.
  _advance_failure:
  _readState.afterAdvanceFailure(iprot);
_loop:
  if (_readState.atStop()) {
    goto _end;
  }
  if (iprot->kUsesFieldNames()) {
    _readState.template fillFieldTraitsFromName<apache::thrift::detail::TccStructTraits<MemoryAllocatorObject>>();
  }

  switch (_readState.fieldId) {
    case 1:
    {
      if (LIKELY(_readState.isCompatibleWithType(iprot, apache::thrift::protocol::TType::T_SET))) {
        goto _readField_allocSizes;
      } else {
        goto _skip;
      }
    }
    case 4:
    {
      if (LIKELY(_readState.isCompatibleWithType(iprot, apache::thrift::protocol::TType::T_BOOL))) {
        goto _readField_enableZeroedSlabAllocs;
      } else {
        goto _skip;
      }
    }
    case 5:
    {
      if (LIKELY(_readState.isCompatibleWithType(iprot, apache::thrift::protocol::TType::T_BOOL))) {
        goto _readField_lockMemory;
      } else {
        goto _skip;
      }
    }
    case 2:
    {
      if (LIKELY(_readState.isCompatibleWithType(iprot, apache::thrift::protocol::TType::T_STRUCT))) {
        goto _readField_slabAllocator;
      } else {
        goto _skip;
      }
    }
    case 3:
    {
      if (LIKELY(_readState.isCompatibleWithType(iprot, apache::thrift::protocol::TType::T_STRUCT))) {
        goto _readField_memoryPoolManager;
      } else {
        goto _skip;
      }
    }
    default:
    {
_skip:
      _readState.skip(iprot);
      _readState.readFieldEnd(iprot);
      _readState.readFieldBeginNoInline(iprot);
      goto _loop;
    }
  }
}

template <class Protocol_>
uint32_t MemoryAllocatorObject::serializedSize(Protocol_ const* prot_) const {
  uint32_t xfer = 0;
  xfer += prot_->serializedStructSize("MemoryAllocatorObject");
  {
    xfer += prot_->serializedFieldSize("allocSizes", apache::thrift::protocol::TType::T_SET, 1);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::set<::apache::thrift::type_class::integral>, ::std::set<::std::int64_t>>::serializedSize<false>(*prot_, this->__fbthrift_field_allocSizes);
  }
  {
    xfer += prot_->serializedFieldSize("enableZeroedSlabAllocs", apache::thrift::protocol::TType::T_BOOL, 4);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, bool>::serializedSize<false>(*prot_, this->__fbthrift_field_enableZeroedSlabAllocs);
  }
  {
    xfer += prot_->serializedFieldSize("lockMemory", apache::thrift::protocol::TType::T_BOOL, 5);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, bool>::serializedSize<false>(*prot_, this->__fbthrift_field_lockMemory);
  }
  {
    xfer += prot_->serializedFieldSize("slabAllocator", apache::thrift::protocol::TType::T_STRUCT, 2);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::structure, ::facebook::cachelib::serialization::SlabAllocatorObject>::serializedSize<false>(*prot_, this->__fbthrift_field_slabAllocator);
  }
  {
    xfer += prot_->serializedFieldSize("memoryPoolManager", apache::thrift::protocol::TType::T_STRUCT, 3);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::structure, ::facebook::cachelib::serialization::MemoryPoolManagerObject>::serializedSize<false>(*prot_, this->__fbthrift_field_memoryPoolManager);
  }
  xfer += prot_->serializedSizeStop();
  return xfer;
}

template <class Protocol_>
uint32_t MemoryAllocatorObject::serializedSizeZC(Protocol_ const* prot_) const {
  uint32_t xfer = 0;
  xfer += prot_->serializedStructSize("MemoryAllocatorObject");
  {
    xfer += prot_->serializedFieldSize("allocSizes", apache::thrift::protocol::TType::T_SET, 1);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::set<::apache::thrift::type_class::integral>, ::std::set<::std::int64_t>>::serializedSize<false>(*prot_, this->__fbthrift_field_allocSizes);
  }
  {
    xfer += prot_->serializedFieldSize("enableZeroedSlabAllocs", apache::thrift::protocol::TType::T_BOOL, 4);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, bool>::serializedSize<false>(*prot_, this->__fbthrift_field_enableZeroedSlabAllocs);
  }
  {
    xfer += prot_->serializedFieldSize("lockMemory", apache::thrift::protocol::TType::T_BOOL, 5);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, bool>::serializedSize<false>(*prot_, this->__fbthrift_field_lockMemory);
  }
  {
    xfer += prot_->serializedFieldSize("slabAllocator", apache::thrift::protocol::TType::T_STRUCT, 2);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::structure, ::facebook::cachelib::serialization::SlabAllocatorObject>::serializedSize<true>(*prot_, this->__fbthrift_field_slabAllocator);
  }
  {
    xfer += prot_->serializedFieldSize("memoryPoolManager", apache::thrift::protocol::TType::T_STRUCT, 3);
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::structure, ::facebook::cachelib::serialization::MemoryPoolManagerObject>::serializedSize<true>(*prot_, this->__fbthrift_field_memoryPoolManager);
  }
  xfer += prot_->serializedSizeStop();
  return xfer;
}

template <class Protocol_>
uint32_t MemoryAllocatorObject::write(Protocol_* prot_) const {
  // If the protocol requests field-id-ascending order and it differs from
  // the codegen serialization order, delegate to the generic StructEncode
  // which respects FieldOrder::IdAscending.
  if constexpr (requires { prot_->fieldOrder(); }) {
    if (prot_->fieldOrder() == ::apache::thrift::FieldOrder::IdAscending) {
      return ::apache::thrift::op::detail::StructEncode<MemoryAllocatorObject>{}(*prot_, *this);
    }
  }
  uint32_t xfer = 0;
  xfer += prot_->writeStructBegin("MemoryAllocatorObject");
  bool previousFieldHasValue = true;
  {
    constexpr int16_t kPrevFieldId = 0;
    xfer += ::apache::thrift::detail::writeFieldBegin<apache::thrift::protocol::TType::T_SET, 1, kPrevFieldId>(*prot_, "allocSizes", previousFieldHasValue);
    previousFieldHasValue = true;
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::set<::apache::thrift::type_class::integral>, ::std::set<::std::int64_t>>::write(*prot_, this->__fbthrift_field_allocSizes);
    xfer += prot_->writeFieldEnd();
  }
  {
    constexpr int16_t kPrevFieldId = 1;
    xfer += ::apache::thrift::detail::writeFieldBegin<apache::thrift::protocol::TType::T_BOOL, 4, kPrevFieldId>(*prot_, "enableZeroedSlabAllocs", previousFieldHasValue);
    previousFieldHasValue = true;
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, bool>::write(*prot_, this->__fbthrift_field_enableZeroedSlabAllocs);
    xfer += prot_->writeFieldEnd();
  }
  {
    constexpr int16_t kPrevFieldId = 4;
    xfer += ::apache::thrift::detail::writeFieldBegin<apache::thrift::protocol::TType::T_BOOL, 5, kPrevFieldId>(*prot_, "lockMemory", previousFieldHasValue);
    previousFieldHasValue = true;
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::integral, bool>::write(*prot_, this->__fbthrift_field_lockMemory);
    xfer += prot_->writeFieldEnd();
  }
  {
    constexpr int16_t kPrevFieldId = 5;
    xfer += ::apache::thrift::detail::writeFieldBegin<apache::thrift::protocol::TType::T_STRUCT, 2, kPrevFieldId>(*prot_, "slabAllocator", previousFieldHasValue);
    previousFieldHasValue = true;
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::structure, ::facebook::cachelib::serialization::SlabAllocatorObject>::write(*prot_, this->__fbthrift_field_slabAllocator);
    xfer += prot_->writeFieldEnd();
  }
  {
    constexpr int16_t kPrevFieldId = 2;
    xfer += ::apache::thrift::detail::writeFieldBegin<apache::thrift::protocol::TType::T_STRUCT, 3, kPrevFieldId>(*prot_, "memoryPoolManager", previousFieldHasValue);
    previousFieldHasValue = true;
    xfer += ::apache::thrift::detail::pm::protocol_methods<::apache::thrift::type_class::structure, ::facebook::cachelib::serialization::MemoryPoolManagerObject>::write(*prot_, this->__fbthrift_field_memoryPoolManager);
    xfer += prot_->writeFieldEnd();
  }
  xfer += prot_->writeFieldStop();
  xfer += prot_->writeStructEnd();
  return xfer;
}

extern template void MemoryAllocatorObject::readNoXfer<>(apache::thrift::BinaryProtocolReader*);
extern template uint32_t MemoryAllocatorObject::write<>(apache::thrift::BinaryProtocolWriter*) const;
extern template uint32_t MemoryAllocatorObject::serializedSize<>(apache::thrift::BinaryProtocolWriter const*) const;
extern template uint32_t MemoryAllocatorObject::serializedSizeZC<>(apache::thrift::BinaryProtocolWriter const*) const;
extern template void MemoryAllocatorObject::readNoXfer<>(apache::thrift::CompactProtocolReader*);
extern template uint32_t MemoryAllocatorObject::write<>(apache::thrift::CompactProtocolWriter*) const;
extern template uint32_t MemoryAllocatorObject::serializedSize<>(apache::thrift::CompactProtocolWriter const*) const;
extern template uint32_t MemoryAllocatorObject::serializedSizeZC<>(apache::thrift::CompactProtocolWriter const*) const;


} // namespace facebook::cachelib::serialization
