/**
 * Autogenerated by Thrift for cachelib/allocator/memory/serialize/objects.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated @nocommit
 */
#include "cachelib/allocator/memory/serialize/gen-cpp2/objects_types_custom_protocol.h"

namespace facebook::cachelib::serialization {

template void SlabAllocatorObject::readNoXfer<>(apache::thrift::BinaryProtocolReader*);
template uint32_t SlabAllocatorObject::write<>(apache::thrift::BinaryProtocolWriter*) const;
template uint32_t SlabAllocatorObject::serializedSize<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t SlabAllocatorObject::serializedSizeZC<>(apache::thrift::BinaryProtocolWriter const*) const;

template void AllocationClassObject::readNoXfer<>(apache::thrift::BinaryProtocolReader*);
template uint32_t AllocationClassObject::write<>(apache::thrift::BinaryProtocolWriter*) const;
template uint32_t AllocationClassObject::serializedSize<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t AllocationClassObject::serializedSizeZC<>(apache::thrift::BinaryProtocolWriter const*) const;

template void MemoryPoolObject::readNoXfer<>(apache::thrift::BinaryProtocolReader*);
template uint32_t MemoryPoolObject::write<>(apache::thrift::BinaryProtocolWriter*) const;
template uint32_t MemoryPoolObject::serializedSize<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t MemoryPoolObject::serializedSizeZC<>(apache::thrift::BinaryProtocolWriter const*) const;

template void MemoryPoolManagerObject::readNoXfer<>(apache::thrift::BinaryProtocolReader*);
template uint32_t MemoryPoolManagerObject::write<>(apache::thrift::BinaryProtocolWriter*) const;
template uint32_t MemoryPoolManagerObject::serializedSize<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t MemoryPoolManagerObject::serializedSizeZC<>(apache::thrift::BinaryProtocolWriter const*) const;

template void MemoryAllocatorObject::readNoXfer<>(apache::thrift::BinaryProtocolReader*);
template uint32_t MemoryAllocatorObject::write<>(apache::thrift::BinaryProtocolWriter*) const;
template uint32_t MemoryAllocatorObject::serializedSize<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t MemoryAllocatorObject::serializedSizeZC<>(apache::thrift::BinaryProtocolWriter const*) const;

} // namespace facebook::cachelib::serialization
