/**
 * Autogenerated by Thrift for cachelib/allocator/memory/serialize/objects.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated @nocommit
 */

#include "cachelib/allocator/memory/serialize/gen-cpp2/objects_data.h"
#include "cachelib/allocator/memory/serialize/gen-cpp2/objects_constants.h"

#include <thrift/lib/cpp2/gen/module_data_cpp.h>

namespace apache::thrift {

THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::string_view TStructDataStorage<::facebook::cachelib::serialization::SlabAllocatorObject>::name = "SlabAllocatorObject";
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<std::string_view, 8> TStructDataStorage<::facebook::cachelib::serialization::SlabAllocatorObject>::fields_names = { {
  "memorySize"sv,
  "canAllocate"sv,
  "memoryPoolSize"sv,
  "slabSize"sv,
  "minAllocSize"sv,
  "nextSlabIdx"sv,
  "freeSlabIdxs"sv,
  "advisedSlabIdxs"sv,
}};
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<int16_t, 8> TStructDataStorage<::facebook::cachelib::serialization::SlabAllocatorObject>::fields_ids = { {
  2,
  4,
  5,
  7,
  8,
  9,
  10,
  11,
}};
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<protocol::TType, 8> TStructDataStorage<::facebook::cachelib::serialization::SlabAllocatorObject>::fields_types = { {
  apache::thrift::protocol::TType::T_I64,
  apache::thrift::protocol::TType::T_BOOL,
  apache::thrift::protocol::TType::T_MAP,
  apache::thrift::protocol::TType::T_I64,
  apache::thrift::protocol::TType::T_I64,
  apache::thrift::protocol::TType::T_I32,
  apache::thrift::protocol::TType::T_LIST,
  apache::thrift::protocol::TType::T_LIST,
}};
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<int, 8> TStructDataStorage<::facebook::cachelib::serialization::SlabAllocatorObject>::isset_indexes = { {
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  0,
}};

THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::string_view TStructDataStorage<::facebook::cachelib::serialization::AllocationClassObject>::name = "AllocationClassObject";
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<std::string_view, 8> TStructDataStorage<::facebook::cachelib::serialization::AllocationClassObject>::fields_names = { {
  "classId"sv,
  "allocationSize"sv,
  "currOffset"sv,
  "canAllocate"sv,
  "freedAllocationsObject"sv,
  "currSlabIdx"sv,
  "allocatedSlabIdxs"sv,
  "freeSlabIdxs"sv,
}};
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<int16_t, 8> TStructDataStorage<::facebook::cachelib::serialization::AllocationClassObject>::fields_ids = { {
  1,
  2,
  4,
  8,
  9,
  10,
  11,
  12,
}};
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<protocol::TType, 8> TStructDataStorage<::facebook::cachelib::serialization::AllocationClassObject>::fields_types = { {
  apache::thrift::protocol::TType::T_BYTE,
  apache::thrift::protocol::TType::T_I64,
  apache::thrift::protocol::TType::T_I64,
  apache::thrift::protocol::TType::T_BOOL,
  apache::thrift::protocol::TType::T_STRUCT,
  apache::thrift::protocol::TType::T_I32,
  apache::thrift::protocol::TType::T_LIST,
  apache::thrift::protocol::TType::T_LIST,
}};
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<int, 8> TStructDataStorage<::facebook::cachelib::serialization::AllocationClassObject>::isset_indexes = { {
  -1,
  -1,
  -1,
  -1,
  0,
  -1,
  -1,
  -1,
}};

THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::string_view TStructDataStorage<::facebook::cachelib::serialization::MemoryPoolObject>::name = "MemoryPoolObject";
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<std::string_view, 10> TStructDataStorage<::facebook::cachelib::serialization::MemoryPoolObject>::fields_names = { {
  "id"sv,
  "maxSize"sv,
  "currSlabAllocSize"sv,
  "currAllocSize"sv,
  "acSizes"sv,
  "ac"sv,
  "numSlabResize"sv,
  "numSlabRebalance"sv,
  "freeSlabIdxs"sv,
  "numSlabsAdvised"sv,
}};
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<int16_t, 10> TStructDataStorage<::facebook::cachelib::serialization::MemoryPoolObject>::fields_ids = { {
  1,
  2,
  3,
  4,
  6,
  7,
  8,
  9,
  10,
  11,
}};
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<protocol::TType, 10> TStructDataStorage<::facebook::cachelib::serialization::MemoryPoolObject>::fields_types = { {
  apache::thrift::protocol::TType::T_BYTE,
  apache::thrift::protocol::TType::T_I64,
  apache::thrift::protocol::TType::T_I64,
  apache::thrift::protocol::TType::T_I64,
  apache::thrift::protocol::TType::T_LIST,
  apache::thrift::protocol::TType::T_LIST,
  apache::thrift::protocol::TType::T_I64,
  apache::thrift::protocol::TType::T_I64,
  apache::thrift::protocol::TType::T_LIST,
  apache::thrift::protocol::TType::T_I64,
}};
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<int, 10> TStructDataStorage<::facebook::cachelib::serialization::MemoryPoolObject>::isset_indexes = { {
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  0,
  1,
  -1,
  2,
}};

THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::string_view TStructDataStorage<::facebook::cachelib::serialization::MemoryPoolManagerObject>::name = "MemoryPoolManagerObject";
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<std::string_view, 3> TStructDataStorage<::facebook::cachelib::serialization::MemoryPoolManagerObject>::fields_names = { {
  "pools"sv,
  "poolsByName"sv,
  "nextPoolId"sv,
}};
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<int16_t, 3> TStructDataStorage<::facebook::cachelib::serialization::MemoryPoolManagerObject>::fields_ids = { {
  1,
  2,
  3,
}};
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<protocol::TType, 3> TStructDataStorage<::facebook::cachelib::serialization::MemoryPoolManagerObject>::fields_types = { {
  apache::thrift::protocol::TType::T_LIST,
  apache::thrift::protocol::TType::T_MAP,
  apache::thrift::protocol::TType::T_BYTE,
}};
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<int, 3> TStructDataStorage<::facebook::cachelib::serialization::MemoryPoolManagerObject>::isset_indexes = { {
  0,
  1,
  2,
}};

THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::string_view TStructDataStorage<::facebook::cachelib::serialization::MemoryAllocatorObject>::name = "MemoryAllocatorObject";
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<std::string_view, 5> TStructDataStorage<::facebook::cachelib::serialization::MemoryAllocatorObject>::fields_names = { {
  "allocSizes"sv,
  "enableZeroedSlabAllocs"sv,
  "lockMemory"sv,
  "slabAllocator"sv,
  "memoryPoolManager"sv,
}};
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<int16_t, 5> TStructDataStorage<::facebook::cachelib::serialization::MemoryAllocatorObject>::fields_ids = { {
  1,
  4,
  5,
  2,
  3,
}};
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<protocol::TType, 5> TStructDataStorage<::facebook::cachelib::serialization::MemoryAllocatorObject>::fields_types = { {
  apache::thrift::protocol::TType::T_SET,
  apache::thrift::protocol::TType::T_BOOL,
  apache::thrift::protocol::TType::T_BOOL,
  apache::thrift::protocol::TType::T_STRUCT,
  apache::thrift::protocol::TType::T_STRUCT,
}};
THRIFT_DATA_MEMBER FOLLY_ATTR_WEAK const std::array<int, 5> TStructDataStorage<::facebook::cachelib::serialization::MemoryAllocatorObject>::isset_indexes = { {
  -1,
  -1,
  0,
  -1,
  -1,
}};

namespace detail {

::folly::Range<const ::std::string_view*> TSchemaAssociation<::facebook::cachelib::serialization::SlabAllocatorObject, false>::bundle() {
    return ::facebook::cachelib::serialization::objects_constants::_fbthrift_schema_579593bad84cc3bd_includes();
}

::folly::Range<const ::std::string_view*> TSchemaAssociation<::facebook::cachelib::serialization::AllocationClassObject, false>::bundle() {
    return ::facebook::cachelib::serialization::objects_constants::_fbthrift_schema_579593bad84cc3bd_includes();
}

::folly::Range<const ::std::string_view*> TSchemaAssociation<::facebook::cachelib::serialization::MemoryPoolObject, false>::bundle() {
    return ::facebook::cachelib::serialization::objects_constants::_fbthrift_schema_579593bad84cc3bd_includes();
}

::folly::Range<const ::std::string_view*> TSchemaAssociation<::facebook::cachelib::serialization::MemoryPoolManagerObject, false>::bundle() {
    return ::facebook::cachelib::serialization::objects_constants::_fbthrift_schema_579593bad84cc3bd_includes();
}

::folly::Range<const ::std::string_view*> TSchemaAssociation<::facebook::cachelib::serialization::MemoryAllocatorObject, false>::bundle() {
    return ::facebook::cachelib::serialization::objects_constants::_fbthrift_schema_579593bad84cc3bd_includes();
}

} // namespace detail
} // namespace apache::thrift
